import { deterministicUuid } from "./random";
import type { SyntheticIncident, SyntheticIncidentCategory, SyntheticWorld } from "./types";

type PermanentIncidentCategory = Extract<
  SyntheticIncidentCategory,
  "ENVIRONMENT_ISSUE" | "NEEDS_PRODUCT_DECISION" | "PRODUCT_BUG" | "SIMULATION_BUG" | "TESTABILITY_GAP"
>;

type KnownIncident = {
  actual: string;
  category: PermanentIncidentCategory;
  evidence: string[];
  expected: string;
  fixed: boolean;
  id: string;
  operation: string;
  regressionVerified: boolean;
  reproductionSteps: string[];
  severity: SyntheticIncident["severity"];
  status?: SyntheticIncident["status"];
};

// SW-0004 through SW-0008 were fixed before the permanent incident-first rule was introduced.
// They remain here deliberately so regeneration can never erase that discovery history.
export const KNOWN_SYNTHETIC_INCIDENTS: KnownIncident[] = [
  {
    actual: "The user's global Supabase profile produced Unsupported Config Type.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["Local CLI succeeds with isolated HOME=/tmp/pachangas-synthetic-home."],
    expected: "Supabase CLI can start an isolated local stack without reading incompatible global state.",
    fixed: true,
    id: "SW-0001",
    operation: "environment.supabase_cli_profile",
    regressionVerified: true,
    reproductionSteps: ["Run Supabase CLI with the global profile", "Observe Unsupported Config Type", "Repeat with isolated HOME"],
    severity: "low",
  },
  {
    actual: "Historical migrations fail on an empty database because pachanga_admin_invites is expected before its baseline definition.",
    category: "TESTABILITY_GAP",
    evidence: ["Local rebuild requires supabase/pachangas.sql before the 20260803+ migrations."],
    expected: "The committed migration chain rebuilds an empty database in order.",
    fixed: false,
    id: "SW-0002",
    operation: "database.empty_rebuild",
    regressionVerified: false,
    reproductionSteps: ["Start an empty local Supabase database", "Apply historical migrations in filename order", "Observe missing pachanga_admin_invites"],
    severity: "medium",
  },
  {
    actual: "Supabase local containers publish their unique development ports on 0.0.0.0.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The application URL remains loopback-only and ports 55320-55329 are dedicated to this world."],
    expected: "All synthetic infrastructure binds only to loopback.",
    fixed: false,
    id: "SW-0003",
    operation: "environment.local_port_binding",
    regressionVerified: false,
    reproductionSteps: ["Start the synthetic Supabase stack", "Inspect Docker port bindings"],
    severity: "medium",
  },
  {
    actual: "The match scheduler read SyntheticVenue.provinceCode although the canonical field is code.",
    category: "SIMULATION_BUG",
    evidence: ["npm run typecheck passes", "Five-seed world smoke covers venue lookup."],
    expected: "Venue selection uses the SyntheticProvince code field.",
    fixed: true,
    id: "SW-0004",
    operation: "simulation.match_venue_lookup",
    regressionVerified: true,
    reproductionSteps: ["Compile the initial synthetic match scheduler", "Observe TS2339 on provinceCode"],
    severity: "low",
  },
  {
    actual: "SeededRandom lacked deterministic child streams required by independent daily flows.",
    category: "SIMULATION_BUG",
    evidence: ["Determinism test compares two 45-day worlds deeply.", "npm run typecheck passes."],
    expected: "Every flow can derive a deterministic substream without global randomness.",
    fixed: true,
    id: "SW-0005",
    operation: "simulation.random_fork",
    regressionVerified: true,
    reproductionSteps: ["Compile engine.ts before SeededRandom.fork", "Observe TS2339 on fork"],
    severity: "medium",
  },
  {
    actual: "Guest selection attempted random.pick([]) after every local guest was already in a match.",
    category: "SIMULATION_BUG",
    evidence: ["Full-season seed 20260811 completes with more than 1,000 matches."],
    expected: "Guest fill stops when the remaining candidate pool is empty.",
    fixed: true,
    id: "SW-0006",
    operation: "simulation.match_guest_fill",
    regressionVerified: true,
    reproductionSteps: ["Run full season with seed 20260811", "Reach a high-volume match with exhausted local guests", "Observe Cannot pick from an empty collection"],
    severity: "high",
  },
  {
    actual: "Technical-team roster replacement displaced players and raised free agents from configured 40 to 103.",
    category: "SIMULATION_BUG",
    evidence: ["Population regression asserts exactly 40 free registered agents after ring construction."],
    expected: "The persistent base starts with 30-60 free agents and preserves the configured 40.",
    fixed: true,
    id: "SW-0007",
    operation: "simulation.initial_free_agents",
    regressionVerified: true,
    reproductionSteps: ["Generate seed 20260809 before displaced-player reassignment", "Count registered agents with no team", "Observe 103"],
    severity: "medium",
  },
  {
    actual: "tsx -e emitted CommonJS and rejected top-level await in an ad-hoc persistence probe.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The same probe passes inside an async function; committed CLI does not use top-level await."],
    expected: "Diagnostic commands use an execution form supported by tsx -e.",
    fixed: true,
    id: "SW-0008",
    operation: "environment.tsx_eval_mode",
    regressionVerified: true,
    reproductionSteps: ["Run tsx -e with top-level await", "Observe cjs output format error", "Wrap probe in async function"],
    severity: "info",
  },
  {
    actual: "npm ci reports 21 dependency advisories inherited from the base branch.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["1 low, 4 moderate and 16 high advisories were reported; no unrelated automatic upgrade was attempted."],
    expected: "Synthetic World should not silently modify shared dependency versions.",
    fixed: false,
    id: "SW-0009",
    operation: "environment.dependency_advisories",
    regressionVerified: false,
    reproductionSteps: ["Run npm ci on base commit 4c75d52e", "Review npm audit summary"],
    severity: "medium",
  },
  {
    actual: "The first save_world guard checks current_user inside SECURITY DEFINER, which always resolves to the function owner.",
    category: "SIMULATION_BUG",
    evidence: ["tests/synthetic-world-db.sql verifies that an explicit authenticated request role is rejected before table access."],
    expected: "save_world validates session_user or JWT role independently of function ownership.",
    fixed: true,
    id: "SW-0010",
    operation: "simulation.save_world_authorization_guard",
    regressionVerified: true,
    reproductionSteps: ["Inspect simulation.save_world", "Compare current_user under SECURITY DEFINER with session_user"],
    severity: "high",
  },
  {
    actual: "The snapshot unique constraint includes nullable entity_kind/entity_id, so PostgreSQL can accept duplicate world snapshots for one virtual date.",
    category: "SIMULATION_BUG",
    evidence: ["tests/synthetic-world-db.sql writes two same-date world checkpoints and verifies that exactly one canonical snapshot remains."],
    expected: "One canonical snapshot exists per world, kind, date and entity identity.",
    fixed: true,
    id: "SW-0011",
    operation: "simulation.snapshot_uniqueness",
    regressionVerified: true,
    reproductionSteps: ["Insert two world snapshots with null entity_kind and entity_id", "Observe both rows can coexist"],
    severity: "high",
  },
  {
    actual: "A premature semicolon split SyntheticIncidentCategory before the three permanent incident classifications.",
    category: "SIMULATION_BUG",
    evidence: ["Pending TypeScript regression."],
    expected: "PRODUCT_BUG, SIMULATION_BUG and ENVIRONMENT_ISSUE belong to the same valid type union.",
    fixed: true,
    id: "SW-0012",
    operation: "simulation.incident_category_union",
    regressionVerified: true,
    reproductionSteps: ["Compile types.ts after adding permanent incident classifications", "Observe the union terminated before PRODUCT_BUG"],
    severity: "low",
  },
  {
    actual: "SyntheticWorldStore declared a default public-schema SupabaseClient while constructing a simulation-schema client.",
    category: "SIMULATION_BUG",
    evidence: ["TypeScript reports simulation is not assignable to public at store.ts."],
    expected: "The stored client type is inferred from the simulation-schema factory.",
    fixed: true,
    id: "SW-0013",
    operation: "simulation.store_schema_typing",
    regressionVerified: true,
    reproductionSteps: ["Run npm run typecheck", "Observe TS2322 in SyntheticWorldStore"],
    severity: "low",
  },
  {
    actual: "A broad status patch marked SW-0002, SW-0003 and SW-0009 as fixed although their underlying gaps remain open.",
    category: "SIMULATION_BUG",
    evidence: ["Pending catalog-state regression."],
    expected: "Only explicitly verified incident IDs may change resolution state.",
    fixed: true,
    id: "SW-0014",
    operation: "simulation.incident_status_update_scope",
    regressionVerified: true,
    reproductionSteps: ["Apply a non-ID-scoped fixed-status patch", "Inspect SW-0002, SW-0003 and SW-0009", "Observe incorrect fixed=true"],
    severity: "medium",
  },
  {
    actual: "The first repeat-no-show summary counted every agent with one no-show instead of requiring at least two.",
    category: "SIMULATION_BUG",
    evidence: ["tests/synthetic-world.test.ts verifies that one possible no-show is excluded and two possible no-shows are counted once."],
    expected: "possibleRepeatNoShowAgents includes only agents with two or more possible no-shows.",
    fixed: true,
    id: "SW-0015",
    operation: "simulation.summary_repeat_no_show",
    regressionVerified: true,
    reproductionSteps: ["Create attendance records with one no-show for A and two for B", "Read syntheticWorldSummary", "Observe both A and B counted"],
    severity: "medium",
  },
  {
    actual: "The local PostgreSQL role rejects SET SESSION AUTHORIZATION, so the first defense-in-depth regression could not emulate an authenticated session that way.",
    category: "TESTABILITY_GAP",
    evidence: ["tests/synthetic-world-db.sql now emulates PostgREST with SET ROLE plus request.jwt.claim.role and passes locally."],
    expected: "The SQL regression emulates PostgREST authorization without requiring session-authorization superuser capability.",
    fixed: true,
    id: "SW-0016",
    operation: "simulation.save_world_guard_test_harness",
    regressionVerified: true,
    reproductionSteps: ["Run test:synthetic-world:db", "Attempt SET SESSION AUTHORIZATION authenticated", "Observe permission denied"],
    severity: "low",
  },
  {
    actual: "save_world ignored request.jwt.claim.role when auth.jwt() returned no role and then trusted the underlying postgres session_user.",
    category: "SIMULATION_BUG",
    evidence: ["simulation.save_world resolves the explicit PostgREST role before JWT/session fallbacks; the authenticated SQL regression passes."],
    expected: "An explicit authenticated request role is rejected before any table access, even in a local postgres session using SET ROLE.",
    fixed: true,
    id: "SW-0017",
    operation: "simulation.save_world_effective_role",
    regressionVerified: true,
    reproductionSteps: ["SET ROLE authenticated", "Set request.jwt.claim.role=authenticated", "Call simulation.save_world", "Observe insert attempted"],
    severity: "high",
  },
  {
    actual: "The first local SQL verification sourced simulation/synthetic-world/.env.local even though the ignored environment file lives at the worktree root, so psql fell back to the default socket.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The corrected command sources the root .env.local and both schema application and SQL regressions pass."],
    expected: "Synthetic World database commands load the documented root .env.local before invoking psql.",
    fixed: true,
    id: "SW-0018",
    operation: "environment.local_database_configuration",
    regressionVerified: true,
    reproductionSteps: ["Source simulation/synthetic-world/.env.local", "Run the SQL contract", "Observe fallback to the missing default PostgreSQL socket"],
    severity: "low",
  },
  {
    actual: "advanceSyntheticWorld only processes full virtual days, so a dashboard request to advance one hour would leave currentDate and revision unchanged.",
    category: "SIMULATION_BUG",
    evidence: ["The focused hourly-clock regression advances 08:00 to 09:00 and then 10:00 with one monotonic revision per request."],
    expected: "The virtual clock can advance one hour monotonically and persist a new revision without executing a duplicate daily cycle.",
    fixed: true,
    id: "SW-0019",
    operation: "simulation.clock.advance_hour",
    regressionVerified: true,
    reproductionSteps: ["Create a world at 2026-09-01T08:00Z", "Advance to 09:00Z", "Observe the daily engine returns 08:00Z at the same revision"],
    severity: "medium",
  },
  {
    actual: "The first hourly-clock patch compared the advanced revision with itself, which would add an unnecessary extra revision whenever an hourly step crossed a day boundary.",
    category: "SIMULATION_BUG",
    evidence: ["The focused day-boundary regression advances 23:00 to 00:00 with exactly one revision."],
    expected: "An hourly step adds a revision only when the daily engine has not already advanced one.",
    fixed: true,
    id: "SW-0020",
    operation: "simulation.clock.revision_boundary",
    regressionVerified: true,
    reproductionSteps: ["Start at 2026-09-01T23:00Z", "Advance one virtual hour", "Observe two revisions for one day-boundary step"],
    severity: "medium",
  },
  {
    actual: "The first persistent-season command lost its runner session after the April checkpoint without returning a SQL or application error.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The run resumed from revision 212 without replay and completed at revision 302 with 1,432 matches and 69,234 unique events."],
    expected: "A long local season run remains attached, or can resume from its last committed monthly checkpoint without replay or corruption.",
    fixed: true,
    id: "SW-0021",
    operation: "environment.persistent_season_runner",
    regressionVerified: true,
    reproductionSteps: ["Run synthetic:season from revision 0", "Observe monthly checkpoints through April", "Observe runner session disappear before season end", "Reload the canonical world"],
    severity: "medium",
  },
  {
    actual: "The Synthetic World CLI rendered structured Supabase failures as [object Object], hiding code, details and hints needed to diagnose a failed monthly save.",
    category: "SIMULATION_BUG",
    evidence: ["The focused error-format regression preserves SQLSTATE and timeout details while filtering secret-like fields."],
    expected: "CLI failures preserve structured database diagnostics without exposing secrets.",
    fixed: true,
    id: "SW-0022",
    operation: "simulation.cli.error_diagnostics",
    regressionVerified: true,
    reproductionSteps: ["Make a store operation reject with a Supabase error object", "Pass it to the CLI catch handler", "Observe String(error) returns [object Object]"],
    severity: "medium",
  },
  {
    actual: "simulation.save_world reprocessed the complete event and entity history on every checkpoint and exceeded the PostgREST statement timeout at 50,921 events.",
    category: "SIMULATION_BUG",
    evidence: ["Incremental event persistence, set-based entity upserts and the local-only function timeout completed revisions 242, 273 and 302."],
    expected: "Checkpoint cost scales with the current delta where possible and uses set-based upserts for canonical current-state entities.",
    fixed: true,
    id: "SW-0023",
    operation: "simulation.save_world_incremental_performance",
    regressionVerified: true,
    reproductionSteps: ["Persist a world through revision 212 with 50,921 events", "Advance one month", "Call simulation.save_world through local PostgREST", "Observe SQLSTATE 57014"],
    severity: "high",
  },
  {
    actual: "The first set-based entity upsert exposed duplicate (entity_kind, id) values inside one world snapshot and failed with SQLSTATE 21000.",
    category: "SIMULATION_BUG",
    evidence: ["Set-based persistence selects one final row per kind and ID; SQL contracts and the completed season pass."],
    expected: "Current-state persistence selects one deterministic canonical representation for each entity kind and synthetic ID.",
    fixed: true,
    id: "SW-0024",
    operation: "simulation.entity_snapshot_deduplication",
    regressionVerified: true,
    reproductionSteps: ["Load the revision 212 world", "Advance one month", "Use the set-based entity upsert", "Observe SQLSTATE 21000"],
    severity: "high",
  },
  {
    actual: "The first ad-hoc duplicate diagnostic used top-level await in tsx -e, whose eval output is CommonJS, and failed before reading the world.",
    category: "TESTABILITY_GAP",
    evidence: ["The corrected async IIFE diagnostic loaded revision 212 and reported duplicate counts for every entity collection."],
    expected: "One-off diagnostics use an explicit async entrypoint or a checked-in test harness.",
    fixed: true,
    id: "SW-0025",
    operation: "simulation.diagnostic_async_entrypoint",
    regressionVerified: true,
    reproductionSteps: ["Run tsx -e with top-level await", "Observe the CJS transform error before any database read"],
    severity: "low",
  },
  {
    actual: "The revision 212 world contains 11 duplicate attendance record IDs, while every other canonical entity collection is unique by ID.",
    category: "SIMULATION_BUG",
    evidence: ["Generator, normalizer and invariants are covered; the resumed world completed after canonicalizing the 11 historical duplicates."],
    expected: "Every attendance transition has a globally unique deterministic ID and daily invariants reject duplicates.",
    fixed: true,
    id: "SW-0026",
    operation: "simulation.attendance_record_identity",
    regressionVerified: true,
    reproductionSteps: ["Load seed 20260809 at revision 212", "Group attendanceRecords by id", "Observe 11 IDs with count 2"],
    severity: "high",
  },
  {
    actual: "The first dashboard render serialized all player and match inspectors through the Server Component payload, producing two Next.js Single item size exceeds maxSize warnings.",
    category: "SIMULATION_BUG",
    evidence: ["After moving heavy data behind the no-store API and using the compact summary view, a clean desktop reload has no payload-size warnings."],
    expected: "The initial administrative shell remains compact and heavy world details load from the no-store local API after hydration.",
    fixed: true,
    id: "SW-0027",
    operation: "simulation.dashboard.initial_payload_size",
    regressionVerified: true,
    reproductionSteps: ["Open /admin/simulation-world with the completed season", "Inspect the browser console", "Observe Single item size exceeds maxSize twice"],
    severity: "medium",
  },
  {
    actual: "The first compact world-summary view omitted updated_at while listWorlds still orders by that column.",
    category: "SIMULATION_BUG",
    evidence: ["The SQL contract and synthetic:world list pass with deterministic updated_at ordering and exact normalized counts."],
    expected: "The compact read model exposes every field used for deterministic world ordering.",
    fixed: true,
    id: "SW-0028",
    operation: "simulation.world_summary_ordering",
    regressionVerified: true,
    reproductionSteps: ["Create simulation_world_summaries without updated_at", "Call listWorlds ordered by updated_at", "Observe the missing-column contract"],
    severity: "low",
  },
  {
    actual: "The first horizontal player-view QA waited for the text Jugador sintético and timed out after the tab click reported success.",
    category: "TESTABILITY_GAP",
    evidence: ["The player inspector was present; the corrected QA targets the uppercase textbox role and FACETAS heading, verifies 670 options and no horizontal overflow."],
    expected: "The QA waits on an unambiguous player-inspector element or reports the actual navigation failure.",
    fixed: true,
    id: "SW-0029",
    operation: "simulation.dashboard.player_view_qa_selector",
    regressionVerified: true,
    reproductionSteps: ["Use the 844x390 viewport", "Click Jugadores", "Wait for Jugador sintético", "Observe timeout"],
    severity: "low",
  },
  {
    actual: "The first dashboard advance API derived operationId after loading the current world, so retrying the same HTTP intention after success could advance a second hour at a newer revision.",
    category: "PRODUCT_BUG",
    evidence: ["The committed dashboard API regression advances once, replays the immutable operation without a second write, and rejects a distinct stale operation with HTTP 409."],
    expected: "The client supplies one immutable operationId and expectedRevision; replay returns the receipt and a distinct stale write is rejected." ,
    fixed: true,
    id: "SW-0030",
    operation: "simulation.dashboard.advance_idempotency",
    regressionVerified: true,
    reproductionSteps: ["Send an hour advance", "Retry the same HTTP body after confirmation", "Observe the old API derives a new operation from the newer revision"],
    severity: "high",
  },
  {
    actual: "The permanent known-incident catalog accepted only environment, simulation and testability categories, so recording SW-0030 as PRODUCT_BUG failed typecheck.",
    category: "SIMULATION_BUG",
    evidence: ["npm run typecheck passes with PRODUCT_BUG in the catalog.", "The focused catalog regression verifies all five incident-first classifications."],
    expected: "The permanent incident registry accepts every canonical category required by the incident-first policy, including PRODUCT_BUG and NEEDS_PRODUCT_DECISION.",
    fixed: true,
    id: "SW-0031",
    operation: "simulation.known_incident_category_contract",
    regressionVerified: true,
    reproductionSteps: ["Record a known PRODUCT_BUG in known-incidents.ts", "Run npm run typecheck", "Observe TS2322 from the restricted Extract union"],
    severity: "medium",
  },
  {
    actual: "The completed reference season generated conduct demand, but did not materialize every required scenario class; repeat offenders, coordinated false reports and independent source teams were absent from the final distribution.",
    category: "SIMULATION_BUG",
    evidence: ["The full-season regression verifies all nine required scenario kinds, no self-report, same-team concentration, independent-source evidence and Rating V2 isolation."],
    expected: "Every required conduct archetype has deterministic season evidence while unavailable report and sanction capabilities remain explicitly pending.",
    fixed: true,
    id: "SW-0032",
    operation: "simulation.conduct_required_scenario_coverage",
    regressionVerified: true,
    reproductionSteps: ["Load reference world 3df9494d", "Group conductScenarios by kind", "Observe required scenario classes missing"],
    severity: "high",
  },
  {
    actual: "The reference world predates the expanded attendance and conduct personas; its compatibility fallback persisted only normal/late/occasional attendance and fair/occasional conduct profiles.",
    category: "SIMULATION_BUG",
    evidence: ["The regression restores all eight attendance and six conduct archetypes, preserves match history and verifies that a second reconciliation is a no-op."],
    expected: "The persistent reference world contains every required attendance and conduct behavior archetype without replacing its sporting history.",
    fixed: true,
    id: "SW-0033",
    operation: "simulation.legacy_behavior_profile_reconciliation",
    regressionVerified: true,
    reproductionSteps: ["Load reference world revision 304", "Group agents by attendanceProfile and conductProfile", "Observe missing required archetypes"],
    severity: "high",
  },
  {
    actual: "The 30-seed soak found a match whose scorer-goal sum differed from the final score in seed 20261001 after 35 virtual days.",
    category: "SIMULATION_BUG",
    evidence: ["The exact seed regression assigns guest scorers to the side they complete and matches.scorers_equal_score passes."],
    expected: "Every finalized or reconciled match has scorer totals exactly equal to homeGoals plus awayGoals for every seed.",
    fixed: true,
    id: "SW-0034",
    operation: "simulation.match_scorer_total_soak",
    regressionVerified: true,
    reproductionSteps: ["Create ephemeral world seed 20261001", "Advance 35 virtual days", "Run dailyInvariantChecks", "Observe matches.scorers_equal_score failure"],
    severity: "high",
  },
  {
    actual: "New permanent incidents are merged when a world is read, but a completed world with no other state change had no explicit command to persist the updated catalog into simulation_incidents.",
    category: "TESTABILITY_GAP",
    evidence: ["The first sync-incidents run persisted the catalog at revision 306; an immediate second run returned changed=false without advancing revision."],
    expected: "A local idempotent command compares and persists the canonical incident registry without advancing virtual time or fabricating a product event.",
    fixed: true,
    id: "SW-0035",
    operation: "simulation.incident_catalog_persistence",
    regressionVerified: true,
    reproductionSteps: ["Add a permanent known incident", "Load a completed world", "Compare in-memory incidents with simulation_incidents", "Observe the new row is not yet persisted"],
    severity: "medium",
  },
  {
    actual: "The direct agent-browser command was unavailable in the worktree PATH during the final visual QA rerun.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The packaged Browser runtime connected to the in-app browser and completed desktop/mobile QA."],
    expected: "Visual QA uses the installed browser automation launcher available in the Codex runtime.",
    fixed: true,
    id: "SW-0036",
    operation: "environment.agent_browser_launcher",
    regressionVerified: true,
    reproductionSteps: ["Run agent-browser session list from the worktree", "Observe command not found", "Locate and invoke the packaged launcher"],
    severity: "low",
  },
  {
    actual: "The selected in-app browser backend rejected waitForLoadState(networkidle) during final local QA despite that state appearing in the generic browser contract.",
    category: "TESTABILITY_GAP",
    evidence: ["domcontentloaded plus a visible Synthetic World heading completed successfully on the selected backend."],
    expected: "Local QA waits for domcontentloaded and then for a stable visible dashboard element supported by the selected backend.",
    fixed: true,
    id: "SW-0037",
    operation: "simulation.dashboard.browser_load_wait",
    regressionVerified: true,
    reproductionSteps: ["Open the local Synthetic World dashboard", "Call waitForLoadState with networkidle", "Observe backend rejection", "Use domcontentloaded plus visible locator"],
    severity: "low",
  },
  {
    actual: "The first final-QA visible wait found no exact PACHANGAS IQ heading after the local dashboard navigation.",
    category: "TESTABILITY_GAP",
    evidence: ["DOM inspection found the actual eyebrow text and the stable Synthetic World heading; the corrected landmark completed successfully."],
    expected: "QA inspects the current URL and rendered body before choosing a stable dashboard landmark.",
    fixed: true,
    id: "SW-0038",
    operation: "simulation.dashboard.final_qa_landmark",
    regressionVerified: true,
    reproductionSteps: ["Navigate to the local dashboard", "Wait for exact text PACHANGAS IQ", "Observe no matching locator", "Inspect URL and rendered body"],
    severity: "low",
  },
  {
    actual: "The first screenshot retry referenced a filesystem binding that was never initialized because the earlier browser operation stopped at its visibility timeout.",
    category: "TESTABILITY_GAP",
    evidence: ["Desktop and mobile PNGs were written after each capture initialized its own artifact writer."],
    expected: "Each screenshot operation initializes its own artifact writer and does not depend on bindings after a failed browser step.",
    fixed: true,
    id: "SW-0039",
    operation: "simulation.dashboard.screenshot_artifact_writer",
    regressionVerified: true,
    reproductionSteps: ["Let a browser step fail before initializing its file binding", "Retry capture using that binding", "Observe undefined binding", "Initialize the writer in the retry itself"],
    severity: "low",
  },
  {
    actual: "At 390x844 the final dashboard had no document-level horizontal scroll, but long header, selector and conduct-card content was visibly clipped beyond the viewport.",
    category: "PRODUCT_BUG",
    evidence: ["Bounding-box diagnostics prove the header and conduct title are fully inside the viewport; only the intentionally scrollable clock and tab rails exceed their client width."],
    expected: "The local administrative dashboard remains readable and navigable at a 390px mobile viewport without clipped text or controls.",
    fixed: false,
    id: "SW-0040",
    operation: "simulation.dashboard.mobile_content_clipping",
    regressionVerified: false,
    reproductionSteps: ["Open the dashboard at 390x844", "Select Conducta", "Capture the full page", "Observe text and controls clipped at the right edge"],
    severity: "high",
    status: "false_positive",
  },
  {
    actual: "The first 844x390 screenshot appeared to render the dashboard only in an upper strip with a light area below it despite reporting the requested viewport and no horizontal overflow.",
    category: "TESTABILITY_GAP",
    evidence: ["DOM bounds prove html, body and main are 844x390 with the footer at the bottom; the screenshot backend instead emitted a 180x390 JPEG."],
    expected: "Landscape QA distinguishes a real viewport-height defect from screenshot orientation or renderer presentation artifacts.",
    fixed: true,
    id: "SW-0041",
    operation: "simulation.dashboard.landscape_capture_bounds",
    regressionVerified: true,
    reproductionSteps: ["Set viewport to 844x390", "Capture the Conducta tab", "Observe an apparent light region below the dashboard", "Compare DOM bounds and PNG dimensions"],
    severity: "medium",
  },
  {
    actual: "The completed reference season produced 133 provincial ranking rows but zero eligible certifications: 79 not_eligible and 54 pending_integrity_review.",
    category: "TESTABILITY_GAP",
    evidence: ["The full-season regression reproduces zero eligible rows before reconciliation, then verifies at least one eligible row and retained integrity holds without Rating V2 changes."],
    expected: "The persistent world exercises ranking, Top 10 and trophy eligibility with enough legitimate evidence for at least one eligible player while retaining integrity holds for attacks.",
    fixed: true,
    id: "SW-0042",
    operation: "simulation.ranking.eligible_population_coverage",
    regressionVerified: true,
    reproductionSteps: ["Load reference world revision 307", "Group ranking rows by certification", "Observe zero eligible rows", "Inspect evidence thresholds and per-player match distribution"],
    severity: "high",
  },
  {
    actual: "The first deterministic eligibility-control implementation added canonical challenge evidence but the full-season regression still produced zero eligible ranking rows.",
    category: "SIMULATION_BUG",
    evidence: ["test:synthetic-world now passes the original full-season scenario; the control targets the sole insufficient_challenges deficit and preserves all player ratingV2/facets."],
    expected: "The control cohort satisfies every unchanged provincial trophy threshold and proves eligibility without modifying Rating V2.",
    fixed: true,
    id: "SW-0043",
    operation: "simulation.ranking.eligibility_control_thresholds",
    regressionVerified: true,
    reproductionSteps: ["Generate seed 20260811 through season end with eligibility control disabled", "Apply reconcileSyntheticRankingCoverage", "Recalculate rankings", "Observe zero eligible rows"],
    severity: "high",
  },
  {
    actual: "A final metrics diagnostic attempted to read rankingHistory from the world snapshot even though ranking history is persisted in a separate canonical relation.",
    category: "TESTABILITY_GAP",
    evidence: ["The corrected diagnostic uses SyntheticWorldStore.rankingHistory and returned 574 persisted rows for the reference world."],
    expected: "Final diagnostics query ranking history through SyntheticWorldStore instead of assuming it is embedded in the world snapshot.",
    fixed: true,
    id: "SW-0044",
    operation: "simulation.diagnostics.ranking_history_source",
    regressionVerified: true,
    reproductionSteps: ["Load a persisted world", "Read world.state.rankingHistory.length", "Observe TypeError", "Query the dedicated ranking history relation"],
    severity: "low",
  },
  {
    actual: "A final SQL metrics query referenced simulation_worlds.current_date, which is not a column in the local persistence schema.",
    category: "TESTABILITY_GAP",
    evidence: ["The corrected read-only query uses virtual_current_date and returned both persisted worlds with their exact revisions."],
    expected: "Operational diagnostics derive the virtual date from the persisted state or use the schema's exact columns.",
    fixed: true,
    id: "SW-0045",
    operation: "simulation.diagnostics.world_schema_columns",
    regressionVerified: true,
    reproductionSteps: ["Query simulation.simulation_worlds.current_date", "Observe SQLSTATE 42703", "Inspect the local schema", "Run the corrected read-only query"],
    severity: "low",
  },
  {
    actual: "The corrected SQL diagnostics then referenced simulation_snapshots.kind instead of the canonical snapshot_kind column.",
    category: "TESTABILITY_GAP",
    evidence: ["The corrected read-only query uses snapshot_kind and returned 2 checkpoint, 9 monthly and 1 season_end snapshots."],
    expected: "Snapshot diagnostics use the exact persisted schema and remain repeatable as a single read-only check.",
    fixed: true,
    id: "SW-0046",
    operation: "simulation.diagnostics.snapshot_schema_columns",
    regressionVerified: true,
    reproductionSteps: ["Query simulation.simulation_snapshots.kind", "Observe SQLSTATE 42703", "Inspect the local schema", "Run the corrected read-only query"],
    severity: "low",
  },
  {
    actual: "The command runner rejected a dashboard health check because its cleanup step used rm -f for a temporary curl output file.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The replacement curl command wrote to /dev/null and received HTTP 200 from the local dashboard."],
    expected: "The health check writes directly to /dev/null and does not create or delete a temporary file.",
    fixed: true,
    id: "SW-0047",
    operation: "simulation.qa.dashboard_health_command",
    regressionVerified: true,
    reproductionSteps: ["Run curl with a temporary output path followed by rm -f", "Observe command-policy rejection", "Repeat with output directed to /dev/null"],
    severity: "info",
  },
  {
    actual: "The first final dashboard API regression invocation omitted SYNTHETIC_WORLD_ID and stopped before issuing any request.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The corrected run against QA world dbb4943a-a160-495d-a1ba-e11af273c8a9 passed replay idempotency and stale revision rejection at confirmed revision 4."],
    expected: "The regression is invoked explicitly against the disposable QA clock world, never implicitly against the reference season.",
    fixed: true,
    id: "SW-0048",
    operation: "simulation.qa.dashboard_api_world_selection",
    regressionVerified: true,
    reproductionSteps: ["Run test:synthetic-world:dashboard-api without SYNTHETIC_WORLD_ID", "Observe the preflight error", "Repeat with the QA world id"],
    severity: "info",
  },
  {
    actual: "Focused ESLint reported an unused world parameter in the synthetic ranking teamProfiles helper.",
    category: "SIMULATION_BUG",
    evidence: ["Focused ESLint passes with zero warnings after removing the unused helper parameter."],
    expected: "Synthetic World source passes focused lint with zero errors and zero warnings.",
    fixed: true,
    id: "SW-0049",
    operation: "simulation.ranking.team_profiles_signature",
    regressionVerified: true,
    reproductionSteps: ["Run focused ESLint for simulation/synthetic-world", "Observe the unused world parameter warning", "Remove the unused parameter and rerun lint"],
    severity: "info",
  },
  {
    actual: "Repository-wide ESLint fails on pre-existing application files outside Synthetic World, including legal-data.tsx, mercado/page.tsx, page.tsx and theme-toggle.tsx.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The first final run reported 44 findings; one Synthetic World warning was fixed independently and focused lint now passes."],
    expected: "Global lint debt is reported without silently refactoring unrelated product code; Synthetic World remains lint-clean in isolation.",
    fixed: false,
    id: "SW-0050",
    operation: "environment.preexisting_global_lint_debt",
    regressionVerified: false,
    reproductionSteps: ["Run npm run lint at base-compatible HEAD", "Observe findings in unrelated application files", "Run focused lint for Synthetic World", "Observe zero findings"],
    severity: "medium",
  },
  {
    actual: "The achievements-crests SQL suite did not award the expected match and win achievements for the first external victory on the current local schema.",
    category: "TESTABILITY_GAP",
    evidence: ["tests/achievements-crests-db.sql failed at line 253: The first external win must award the match and win achievements once."],
    expected: "The current achievement catalog and its historical SQL regression agree on the first external-win awards, or the legacy contract is explicitly retired.",
    fixed: false,
    id: "SW-0051",
    operation: "product.achievements.external_first_win_regression",
    regressionVerified: false,
    reproductionSteps: ["Apply the current local schema", "Run test:achievements-crests:db", "Observe the assertion at line 253"],
    severity: "high",
  },
  {
    actual: "The achievement catalog V2 SQL suite found a number of active threshold rows different from its expected 101 on the current V3 schema.",
    category: "TESTABILITY_GAP",
    evidence: ["tests/achievement-catalog-v2-db.sql failed at line 119: The definitive catalog must expose 101 active threshold rows."],
    expected: "Catalog-version regressions state whether they validate a historical snapshot or the current active catalog and remain deterministic after V3 activation.",
    fixed: false,
    id: "SW-0052",
    operation: "product.achievements.v2_catalog_version_contract",
    regressionVerified: false,
    reproductionSteps: ["Apply the current local V3 schema", "Run test:achievement-catalog:db", "Observe the active-row-count assertion at line 119"],
    severity: "medium",
  },
  {
    actual: "The collective reward boxes SQL suite did not create the expected forty boxes for four collective achievements and ten participants on the current schema.",
    category: "TESTABILITY_GAP",
    evidence: ["tests/collective-reward-boxes-db.sql failed at line 230: Four collective achievements and ten participants must create forty boxes."],
    expected: "The active collective catalog creates the documented per-participant box grants, or the regression fixture targets an explicit catalog version.",
    fixed: false,
    id: "SW-0053",
    operation: "product.rewards.collective_box_count_regression",
    regressionVerified: false,
    reproductionSteps: ["Apply the current local schema", "Run test:collective-boxes:db", "Observe the expected forty-box assertion at line 230"],
    severity: "high",
  },
  {
    actual: "The final screenshot attempt called playwright.setViewportSize, which is not exposed by the selected in-app browser tab binding.",
    category: "TESTABILITY_GAP",
    evidence: ["The supported tab screenshot API captured the refreshed dashboard successfully using the existing desktop viewport."],
    expected: "Final QA reuses the already configured viewport and captures the page through the supported tab screenshot API.",
    fixed: true,
    id: "SW-0054",
    operation: "simulation.qa.viewport_api_binding",
    regressionVerified: true,
    reproductionSteps: ["Call qaTab.playwright.setViewportSize", "Observe the unsupported-method error", "Capture using the existing configured viewport"],
    severity: "info",
  },
  {
    actual: "The browser screenshot call returned success but the requested local path still contained the older revision 307 capture instead of the loaded revision 310 page.",
    category: "TESTABILITY_GAP",
    evidence: ["The live viewport bytes were persisted explicitly and the local file was re-opened showing revision 310, 1,441 matches and 59 incidents."],
    expected: "Final evidence uses the screenshot bytes returned by the live browser or persists them through a verified supported writer.",
    fixed: true,
    id: "SW-0055",
    operation: "simulation.qa.screenshot_file_persistence",
    regressionVerified: true,
    reproductionSteps: ["Reload revision 310", "Call tab screenshot with a path", "Inspect that path", "Observe revision 307 remains"],
    severity: "low",
  },
  {
    actual: "The live full-page screenshot bytes rendered as a uniform dark canvas although the same tab exposed a complete revision 310 DOM snapshot.",
    category: "TESTABILITY_GAP",
    evidence: ["A viewport-only capture rendered the complete dashboard and was visually verified after persistence."],
    expected: "Viewport capture renders the visible dashboard and is cross-checked against the semantic DOM snapshot.",
    fixed: true,
    id: "SW-0056",
    operation: "simulation.qa.full_page_capture_blank",
    regressionVerified: true,
    reproductionSteps: ["Load the completed dashboard", "Verify the DOM snapshot", "Capture with fullPage true", "Observe a uniform dark canvas"],
    severity: "medium",
  },
  {
    actual: "A final ranking-history summary read snake_case properties from store rows that are normalized to camelCase, collapsing dates and territories to one undefined key.",
    category: "TESTABILITY_GAP",
    evidence: ["The corrected contract fields returned 574 rows, 10 dates, 7 territories, 16 distinct leaders and 12 leader changes."],
    expected: "Ranking-history diagnostics use the SyntheticRankingHistoryPoint contract returned by the store.",
    fixed: true,
    id: "SW-0057",
    operation: "simulation.diagnostics.ranking_history_field_names",
    regressionVerified: true,
    reproductionSteps: ["Load ranking history through SyntheticWorldStore", "Read virtual_date and territory_code", "Observe undefined-key collapse", "Repeat with normalized camelCase fields"],
    severity: "low",
  },
  {
    actual: "The first staged git diff check found an extra blank line at the end of synthetic-world/src/config.ts.",
    category: "SIMULATION_BUG",
    evidence: ["After removing the extra line, git diff --cached --check completed with no findings."],
    expected: "The complete staged Synthetic World diff passes Git whitespace validation.",
    fixed: true,
    id: "SW-0058",
    operation: "simulation.source.whitespace_validation",
    regressionVerified: true,
    reproductionSteps: ["Stage the complete change", "Run git diff --cached --check", "Observe the EOF whitespace warning", "Remove the extra line and rerun"],
    severity: "info",
  },
  {
    actual: "syntheticWorldSummary labels 950 non-excluded challenge matches as valid ranking evidence, while Season Score consumes one player-match evidence row per participant; the two units are not interchangeable.",
    category: "SIMULATION_BUG",
    evidence: ["Regression verifies match-level marked-valid + marked-excluded totals and reconciles accepted + excluded player-match evidence to the complete source population."],
    expected: "Diagnostics name match-level evidence and player-match evidence separately and reconcile both counts.",
    fixed: true,
    id: "SW-0059",
    operation: "simulation.ranking.evidence_unit_ambiguity",
    regressionVerified: true,
    reproductionSteps: ["Load world 3df9494d-3b8c-4447-96e8-d5244892af78 at revision 313", "Read syntheticWorldSummary.validRankingEvidence", "Compare the 950 match rows with the participant-level Season Score records", "Observe the units differ"],
    severity: "high",
  },
  {
    actual: "The persisted V1 baseline contains nine canonical matches tagged syntheticEligibilityControl, added after the organic season specifically to turn one player from 18 into 27 valid challenges.",
    category: "SIMULATION_BUG",
    evidence: ["Full-season regression verifies default generation emits no ranking.eligibility_control event; explicit reconciliation remains separately tested."],
    expected: "A baseline synthetic season never adds matches to improve eligibility; control fixtures are explicit and reported separately without rewriting the preserved V1 world.",
    fixed: true,
    id: "SW-0060",
    operation: "simulation.ranking.control_cohort_baseline_contamination",
    regressionVerified: true,
    reproductionSteps: ["Load the preserved V1 world at revision 313", "Find ranking.eligibility_control events", "Resolve their match IDs", "Observe nine post-season control matches and one persisted eligible player", "Recalculate without those tagged matches and observe zero organic trophy-eligible players"],
    severity: "high",
  },
  {
    actual: "The first Ranking Funnel confidence aggregation classified a whole match as attacker evidence when any one participant had an attack profile, mixing legitimate player evidence with attacker evidence.",
    category: "SIMULATION_BUG",
    evidence: ["Regression reconciles every player-match evidence row as exactly normal or attacker while retaining a separate match distribution."],
    expected: "Match confidence is counted once per match, while attacker comparison classifies each player-match evidence by the owning agent.",
    fixed: true,
    id: "SW-0061",
    operation: "simulation.ranking.confidence_cohort_unit",
    regressionVerified: true,
    reproductionSteps: ["Aggregate confidence by match", "Mark a match attacker when any participant is synthetic attacker", "Compare with player-evidence ownership", "Observe legitimate participant evidence is mislabeled attacker"],
    severity: "medium",
  },
  {
    actual: "Synthetic World declared the certified Season Score V3 contract but used opponentDecay [1,1,0.75,0.5,0.25,0] and densityTop10Minimum 30 instead of the V3 baseline [1,1,0.5,0.25,0] and 50.",
    category: "SIMULATION_BUG",
    evidence: ["Exact-config regression verifies V3 opponent decay, density gate, weights and recent_30; recalculation is limited to audit reads and isolated clones."],
    expected: "Synthetic World imports or exactly mirrors the approved V3 scoring configuration while keeping historical V1 evidence immutable.",
    fixed: true,
    id: "SW-0062",
    operation: "simulation.ranking.v3_config_drift",
    regressionVerified: true,
    reproductionSteps: ["Compare SYNTHETIC_SEASON_SCORE_CONFIG with v3Baseline(candidate_e_recent20)", "Inspect opponentDecay and densityTop10Minimum", "Observe the adapter drift despite the V3 intact claim"],
    severity: "high",
  },
  {
    actual: "The first V1.1 report serialized Object.values(distribution), whose object insertion order starts with max, under the label p10/p25/p50/p75/p90/p95/max; it therefore printed 492 as p10. Its Barcelona narrative also called the final Season Score an opposition value.",
    category: "SIMULATION_BUG",
    evidence: ["Regression verifies p10 through max are rendered in explicit order and every Barcelona narrative labels the value as Season Score, never opposition."],
    expected: "Every percentile is rendered under its matching label, max is last, and narrative labels distinguish Season Score from opposition inputs.",
    fixed: true,
    id: "SW-0063",
    operation: "simulation.ranking.report_metric_labeling",
    regressionVerified: true,
    reproductionSteps: ["Generate RANKING_FUNNEL_V1_1_REPORT.md", "Read the participation percentile line", "Observe p10 is shown as 492 while the 0-player bucket contains 112 players", "Read a Barcelona narrative and observe Season Score is labeled opposition"],
    severity: "medium",
  },
  {
    actual: "Ranking funnel rendered both ranking-recency and trophy-recency stages with the React key 'Actividad <= 12 semanas', producing a duplicate-key console error and unstable row identity.",
    category: "SIMULATION_BUG",
    evidence: ["Source regression enforces index-plus-label keys and a fresh browser session loads Ranking funnel with no warning or error logs."],
    expected: "Every funnel stage has a stable unique render key even when two product gates share the same visible label.",
    fixed: true,
    id: "SW-0064",
    operation: "simulation.dashboard.ranking_funnel_stage_identity",
    regressionVerified: true,
    reproductionSteps: ["Open the local Synthetic World dashboard", "Select Ranking funnel", "Inspect the browser console", "Observe duplicate key Actividad <= 12 semanas"],
    severity: "medium",
  },
  {
    actual: "The first dashboard API concurrency invocation stopped before execution because SYNTHETIC_WORLD_ID was not exported for the standalone regression runner.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["Rerun targets the disposable local QA clock world explicitly and verifies first write, idempotent replay and stale-revision rejection; preserved V1 remains untouched."],
    expected: "The validation command supplies its target local world explicitly and completes without touching hosted environments.",
    fixed: true,
    id: "SW-0065",
    operation: "simulation.validation.dashboard_api_environment",
    regressionVerified: true,
    reproductionSteps: ["Run npm run test:synthetic-world:dashboard-api with only PACHANGAS_SYNTHETIC_DB_URL", "Observe SYNTHETIC_WORLD_ID is required before any request is sent"],
    severity: "info",
  },
  {
    actual: "Focused lint found two V1.1 symbols with no runtime consumer: SeasonPlayerInput in the report runner and playerById in the funnel builder.",
    category: "TESTABILITY_GAP",
    evidence: ["Focused ESLint rerun over every V1.1 source and test file completed with zero errors and zero warnings."],
    expected: "The V1.1 implementation passes focused lint without unused-code warnings that can obscure future diagnostics.",
    fixed: true,
    id: "SW-0066",
    operation: "simulation.validation.ranking_funnel_focused_lint",
    regressionVerified: true,
    reproductionSteps: ["Run ESLint over the V1.1 touched source and test files", "Observe @typescript-eslint/no-unused-vars for SeasonPlayerInput and playerById"],
    severity: "info",
  },
  {
    actual: "The first local-server readiness loop assigned to zsh's reserved read-only variable status; after correcting that name, the detached nohup launcher was reaped before it could bind port 3090.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["A controlled dev-server session reached Next.js ready state and a non-reserved http_code readiness probe confirmed HTTP 200 on the local dashboard."],
    expected: "The local dashboard readiness probe reaches HTTP 200 without shell-variable collisions.",
    fixed: true,
    id: "SW-0067",
    operation: "simulation.validation.local_dashboard_readiness_shell",
    regressionVerified: true,
    reproductionSteps: ["Run the zsh readiness loop assigning curl output to status", "Observe zsh: read-only variable: status", "Retry with a detached nohup child", "Observe the child is reaped with no listener or log before the readiness poll"],
    severity: "info",
  },
  {
    actual: "Season Score V3 exposes competitionNetworkDiversity as one aggregate value, so the audit cannot distinguish a healthy connected local league from a closed collusion ring or explain how externalNetworkRatio penalizes each network.",
    category: "TESTABILITY_GAP",
    evidence: ["The V3.1 network lab exposes every requested component and reconstructs the exact V3 aggregate; 30-seed regressions separate healthy and manipulated 50-team ecosystems while disconnected future teams leave the core decision unchanged."],
    expected: "The laboratory exposes the exact network-diversity components, ecosystem opportunity and relative context per player, with regressions covering healthy local networks, legitimate clubs, collusion rings, fake farms and sybil networks.",
    fixed: true,
    id: "SW-0068",
    operation: "simulation.ranking.network_diversity_explainability",
    regressionVerified: true,
    reproductionSteps: ["Evaluate a player through summarizeCompetitiveEvidence", "Read competitionNetworkDiversity", "Observe that structural diversity, external exposure, concentration, entropy and territorial opportunity are not returned", "Compare a connected local league with a collusion ring and observe that the aggregate alone cannot explain the distinction"],
    severity: "high",
  },
  {
    actual: "The first V3.1 matrix runner rebuilt each player's province and volume cohort by filtering the entire population, making contextualization quadratic and holding one CPU core at roughly 100% before the 10k reference completed.",
    category: "SIMULATION_BUG",
    evidence: ["The indexed-cohort implementation completes 810 ecosystems, 30 seeds per size/scenario and the 10k reference in a bounded run; focused V3.1 tests pass."],
    expected: "Contextual cohorts are indexed once and the 30-seed multi-size matrix plus 10k reference complete in bounded time with identical decisions.",
    fixed: true,
    id: "SW-0069",
    operation: "simulation.ranking.v31_context_cohort_complexity",
    regressionVerified: true,
    reproductionSteps: ["Run npm run synthetic:network-v31", "Observe the process remain CPU-bound during the matrix and 10k contextualization", "Inspect contextualizeNetworkCandidates", "Observe a full rows.filter call for every player"],
    severity: "medium",
  },
  {
    actual: "The first completed V3.1 calculation generated seven keyed Model 1 threshold variants, but the Markdown summary requested a non-existent unqualified model_1_absolute aggregate and failed after local clones were saved.",
    category: "SIMULATION_BUG",
    evidence: ["The complete runner now renders all seven absolute controls in a dedicated table and writes both JSON summaries plus NETWORK_DIVERSITY_V3_1_REPORT.md."],
    expected: "The report renders Model 0 and Models 2-5 as primary rows while presenting all seven Model 1 thresholds in their dedicated control table.",
    fixed: true,
    id: "SW-0070",
    operation: "simulation.ranking.v31_report_absolute_model_key",
    regressionVerified: true,
    reproductionSteps: ["Run npm run synthetic:network-v31", "Allow all model clones to persist", "Enter report generation", "Observe TypeError reading falsePositiveRate from healthy.model_1_absolute"],
    severity: "low",
  },
  {
    actual: "The first V3.1 contamination metric selected one global Top 10 across all provinces even though trophy eligibility and awards are territorial.",
    category: "SIMULATION_BUG",
    evidence: ["A focused regression places executed abuse inside Barcelona's Top 10 but outside the global Top 10 and verifies 5% contamination across two territorial Top 10 lists."],
    expected: "Top 10 contamination is calculated independently inside each province and then aggregated over the territorial positions actually exposed to awards.",
    fixed: true,
    id: "SW-0071",
    operation: "simulation.ranking.v31_territorial_top10_scope",
    regressionVerified: true,
    reproductionSteps: ["Evaluate multiple provinces with ranking-eligible players", "Place an executed-abuse player inside one provincial Top 10 but outside the global Top 10", "Observe top10Contamination remains zero"],
    severity: "high",
  },
  {
    actual: "The first V3.1 Top 20 report labeled every network decision without a HOLD as CERTIFICABLE even when the player failed a non-network trophy gate.",
    category: "SIMULATION_BUG",
    evidence: ["The status helper and focused regression return NO CANDIDATO whenever non-network trophy eligibility is false; the regenerated Barcelona table uses that status."],
    expected: "The report distinguishes NO CANDIDATO from a network candidate that is held or certifiable and never presents a network-only result as complete trophy eligibility.",
    fixed: true,
    id: "SW-0072",
    operation: "simulation.ranking.v31_report_candidate_status",
    regressionVerified: true,
    reproductionSteps: ["Generate the V3.1 Top 20 table", "Find a player with nonNetworkTrophyEligible=false and no network HOLD", "Observe the row is labeled CERTIFICABLE"],
    severity: "medium",
  },
  {
    actual: "The first V3.1 report generated each growth size as an independent ecosystem and only reported Top 10 contamination, so it did not demonstrate one territory growing through the requested stages or expose Top 20 and Top 50 prize-surface contamination.",
    category: "TESTABILITY_GAP",
    evidence: ["A regression follows nested Team IDs through all six growth stages and independently verifies Top 10, Top 20 and Top 50 territorial contamination for raw and certified surfaces."],
    expected: "The V3.1 laboratory follows one nested territory through 10, 20, 35, 50, 80 and 150 teams and reports territorial Top 10, Top 20 and Top 50 contamination for every model.",
    fixed: true,
    id: "SW-0073",
    operation: "simulation.ranking.v31_growth_and_prize_surfaces",
    regressionVerified: true,
    reproductionSteps: ["Run npm run synthetic:network-v31", "Inspect growthStages in the full export and observe each size was generated independently", "Inspect ModelMetrics and observe only Top 10 contamination is available"],
    severity: "high",
  },
  {
    actual: "The first V3.1 report labeled technicalOpponentCount as Team IDs in the 50-legitimate-HOLD table and omitted both the player's actual team IDs and match confidence.",
    category: "SIMULATION_BUG",
    evidence: ["Every candidate now carries its real teamIds and server-calculated competitiveConfidence; the regenerated 50-HOLD and 44-attacker tables show both values with distinct technical/logical opponent columns."],
    expected: "Every audited legitimate HOLD row identifies its actual team IDs, technical and logical opponent counts, and match confidence without misleading column labels.",
    fixed: true,
    id: "SW-0074",
    operation: "simulation.ranking.v31_hold_evidence_traceability",
    regressionVerified: true,
    reproductionSteps: ["Generate NETWORK_DIVERSITY_V3_1_REPORT.md", "Open the 50 legitimate HOLD table", "Observe the Team IDs column contains a number and match confidence is absent"],
    severity: "medium",
  },
  {
    actual: "SYNTHETIC_WORLD_V1_REPORT still described the pre-V1.1 incident and test totals as final after V3.1 added seven regression-verified findings and expanded npm test to 162 TypeScript tests.",
    category: "SIMULATION_BUG",
    evidence: ["A regression reads the root report, verifies the V1 counts are explicitly historical and confirms the current build + 7 HTML + 163 TypeScript validation total."],
    expected: "The root report labels historical checkpoint totals as historical and states the exact current V3.1 validation count without rewriting the preserved V1 evidence.",
    fixed: true,
    id: "SW-0075",
    operation: "simulation.reporting.v31_validation_totals",
    regressionVerified: true,
    reproductionSteps: ["Open SYNTHETIC_WORLD_V1_REPORT.md after V3.1", "Compare its Estado final and npm test lines with the permanent incident catalog and the current npm test output", "Observe the pre-V1.1 counts are presented as current"],
    severity: "low",
  },
  {
    actual: "The first territory-readiness adapter counted match rows for validChallenges while ranking eligibility counts accepted player-match evidence, leaving Barcelona ranking_inactive despite 44 ranking-eligible players.",
    category: "SIMULATION_BUG",
    evidence: ["tests/territory-award-readiness.test.ts verifies that 300 accepted player-match evidence rows remain 300 even when the fixture has no match-level rows."],
    expected: "Territorial validChallenges uses the same accepted player-match evidence unit as Season Score eligibility and labels match-level volume separately if exposed.",
    fixed: true,
    id: "SW-0076",
    operation: "simulation.ranking.readiness_evidence_unit",
    regressionVerified: true,
    reproductionSteps: ["Load Synthetic World V1 revision 313", "Build territory readiness for province 08", "Observe 44 ranking-eligible players but only 65 match rows assigned to validChallenges", "Observe ranking_inactive from the mismatched unit"],
    severity: "high",
  },
  {
    actual: "The generated JSON import widened readinessState to string, so the provincial pilot could not safely index the closed four-state label map and failed TypeScript with TS7053.",
    category: "SIMULATION_BUG",
    evidence: ["npm run typecheck passes; the focused regression validates every source, temporal, healthy-growth and manipulated-growth state before the pilot renders it."],
    expected: "The pilot validates or narrows every generated readiness state to the closed TerritoryReadinessState contract before rendering it.",
    fixed: true,
    id: "SW-0077",
    operation: "simulation.dashboard.readiness_state_typing",
    regressionVerified: true,
    reproductionSteps: ["Import territory-award-readiness-v1-summary.json in the pilot client", "Index stateLabels with snapshot.readinessState", "Run npm run typecheck", "Observe TS7053"],
    severity: "medium",
  },
  {
    actual: "The first direct SQL source-preservation diagnostic guessed simulation.worlds and failed because that relation is not part of the canonical local schema.",
    category: "TESTABILITY_GAP",
    evidence: ["The catalog-backed query reads simulation.simulation_worlds and returns revision 313/eventSequence 69458; npm run synthetic:territory-readiness enforces both before generating any artifact."],
    expected: "Source-preservation diagnostics resolve the committed simulation schema and verify revision and event sequence without guessed relation names.",
    fixed: true,
    id: "SW-0078",
    operation: "simulation.diagnostics.source_world_relation",
    regressionVerified: true,
    reproductionSteps: ["Connect to the local Synthetic World database", "Query simulation.worlds for the preserved world ID", "Observe PostgreSQL 42P01 relation does not exist"],
    severity: "low",
  },
  {
    actual: "The local SQL/RLS command failed before connecting because the diagnostic shell had not loaded PACHANGAS_SYNTHETIC_DB_URL from .env.local and psql fell back to the missing default socket.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["Loading .env.local in the diagnostic shell runs tests/synthetic-world-db.sql to completion with its final ROLLBACK and no persistent database writes."],
    expected: "Local database validation loads the configured Synthetic World connection without exposing credentials and reaches the canonical SQL/RLS suite.",
    fixed: true,
    id: "SW-0079",
    operation: "simulation.diagnostics.local_database_environment",
    regressionVerified: true,
    reproductionSteps: ["Open a fresh shell without exporting PACHANGAS_SYNTHETIC_DB_URL", "Run npm run test:synthetic-world:db", "Observe psql attempts /tmp/.s.PGSQL.5432 and exits before running the suite"],
    severity: "low",
  },
  {
    actual: "A follow-up source-preservation query addressed the canonical table but guessed event_sequence as a physical column and PostgreSQL rejected the diagnostic before returning evidence.",
    category: "TESTABILITY_GAP",
    evidence: ["The catalog-backed read-only query now reads state->>'eventSequence' and returns the canonical world ID, revision 313 and sequence 69458."],
    expected: "Direct source-preservation SQL derives the event sequence from the schema location actually used by simulation.simulation_worlds.",
    fixed: true,
    id: "SW-0080",
    operation: "simulation.diagnostics.source_world_event_sequence",
    regressionVerified: true,
    reproductionSteps: ["Connect to the local Synthetic World database", "Select event_sequence from simulation.simulation_worlds", "Observe PostgreSQL 42703 column does not exist"],
    severity: "low",
  },
  {
    actual: "The first Supabase CLI migration-new invocation failed before creating a file because the local CLI profile contains an unsupported empty config type.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["Running the same CLI command with an isolated temporary HOME created 20260809162859_conduct_reports_no_show_v1.sql locally and left the global profile and remote projects untouched."],
    expected: "The local-only migration scaffold is created without consulting or changing any linked remote project or global profile.",
    fixed: true,
    id: "SW-0081",
    operation: "simulation.environment.supabase_migration_scaffold",
    regressionVerified: true,
    reproductionSteps: ["Run supabase migration new conduct_reports_no_show_v1 in the isolated worktree", "Observe Unsupported Config Type before any migration file is created"],
    severity: "low",
  },
  {
    actual: "The first conduct migration diagnostic printed line 820 in two overlapping sed ranges, making the single returns jsonb declaration look duplicated.",
    category: "TESTABILITY_GAP",
    evidence: ["nl -ba and sed -n 808,820l show one returns jsonb declaration at line 820; subsequent diagnostics use non-overlapping ranges."],
    expected: "Static migration diagnostics use non-overlapping line ranges and do not turn repeated output into a false product finding.",
    fixed: true,
    id: "SW-0082",
    operation: "simulation.diagnostics.non_overlapping_sql_ranges",
    regressionVerified: true,
    reproductionSteps: ["Print lines 630-820", "Immediately print lines 820-1120", "Observe line 820 twice in the concatenated output", "Inspect the file with numbered or escaped lines and confirm a single declaration"],
    severity: "low",
  },
  {
    actual: "The first attendance RPC draft checked an operation receipt before taking its row or advisory lock but did not replay the check after locking, so two concurrent copies of one operation could make the loser return a state conflict instead of the first canonical response.",
    category: "PRODUCT_BUG",
    evidence: ["tests/conduct-reports-no-show-v1-concurrency.mjs submits the same attendance closure operation concurrently and both callers receive one exact canonical response backed by one receipt."],
    expected: "An identical operationId submitted concurrently applies once and every caller receives the same canonical response.",
    fixed: true,
    id: "SW-0083",
    operation: "conduct.idempotency.concurrent_receipt_replay",
    regressionVerified: true,
    reproductionSteps: ["Start two transactions with the same operationId", "Let both read no receipt before either obtains the entity lock", "Commit the winner", "Observe the loser continuing into already-changed state without replaying the receipt"],
    severity: "critical",
  },
  {
    actual: "The first conduct SQL diagnostic resolved the target profile with a direct SELECT after switching to the reporter role, so profile RLS correctly hid the row and the RPC received a null fixture identifier.",
    category: "TESTABILITY_GAP",
    evidence: ["The diagnostic now assigns deterministic profile UUIDs before role switching and keeps the production RLS policy unchanged."],
    expected: "Authenticated conduct tests use predeclared fixture identifiers and never weaken profile RLS to discover another player's internal row.",
    fixed: true,
    id: "SW-0084",
    operation: "conduct.tests.target_profile_fixture_under_rls",
    regressionVerified: true,
    reproductionSteps: ["Create reporter and target profiles", "Switch to the reporter authenticated role", "Resolve the target with a direct SELECT on pachanga_player_profiles", "Observe RLS returning no row and the report RPC rejecting a null target"],
    severity: "low",
  },
  {
    actual: "The first report execution reached moderation-case creation but PostgreSQL rejected the partial-index ON CONFLICT target because target_profile_id could mean either the RPC parameter or the table column.",
    category: "PRODUCT_BUG",
    evidence: ["The SQL/RLS and concurrency suites submit valid reports, cluster same-team sources and converge one active report without ambiguous identifiers."],
    expected: "Case clustering serializes on the target/category key and selects or creates one open case without ambiguous identifiers.",
    fixed: true,
    id: "SW-0085",
    operation: "conduct.reports.case_cluster_upsert",
    regressionVerified: true,
    reproductionSteps: ["Enable conduct reports in the local database", "Submit a valid match-linked report", "Reach the partial-index ON CONFLICT clause", "Observe target_profile_id is ambiguous"],
    severity: "high",
  },
  {
    actual: "The first attendance closure contract accepted any non-empty subset of match participants and then closed the roster, leaving omitted players without a canonical post-match outcome.",
    category: "PRODUCT_BUG",
    evidence: ["tests/conduct-reports-no-show-v1-db.sql closes exactly three normalized participants and verifies three immutable facts; the RPC rejects any unequal set."],
    expected: "Closing attendance certifies each and every canonical match participant exactly once before the closure becomes immutable.",
    fixed: true,
    id: "SW-0086",
    operation: "conduct.attendance.complete_roster_closure",
    regressionVerified: true,
    reproductionSteps: ["Create a finalized match with three normalized participants", "Submit one valid attendance outcome", "Observe the draft RPC can close the roster while two participants remain uncertified"],
    severity: "high",
  },
  {
    actual: "The first conduct clients invoked async loaders directly from React effects and synchronously cleared evidence, triggering four react-hooks/set-state-in-effect errors in focused lint.",
    category: "PRODUCT_BUG",
    evidence: ["Focused ESLint over every new conduct client and notification-center.tsx passes after scheduling initial loads outside synchronous effect execution."],
    expected: "Initial loads and evidence refreshes are scheduled asynchronously and every effect remains subscription-oriented with deterministic cleanup.",
    fixed: true,
    id: "SW-0087",
    operation: "conduct.ui.react_effect_loading",
    regressionVerified: true,
    reproductionSteps: ["Run focused ESLint for the new conduct clients", "Inspect react-hooks/set-state-in-effect", "Observe direct loader calls and a synchronous setEvidence inside effects"],
    severity: "medium",
  },
  {
    actual: "The first ad-hoc source-world inspection used top-level await through tsx -e, whose CommonJS evaluation mode rejected the diagnostic before the database read began.",
    category: "TESTABILITY_GAP",
    evidence: ["The replacement diagnostic wraps the same read in an async function and verifies revision 313 and server sequence 69458 without mutating the source world."],
    expected: "Local source-world diagnostics run in the module mode they require and produce preservation evidence before the conduct replay is generated.",
    fixed: true,
    id: "SW-0088",
    operation: "simulation.diagnostics.tsx_eval_async_entrypoint",
    regressionVerified: true,
    reproductionSteps: ["Run tsx -e with a top-level await while the evaluator emits CommonJS", "Observe Transform failed: Top-level await is currently not supported with the cjs output format"],
    severity: "low",
  },
  {
    actual: "The first Conduct V1 SQL fixture used the invented group role member, which the canonical pachanga_group_members constraint rejected before any RPC behavior ran.",
    category: "TESTABILITY_GAP",
    evidence: ["The fixture now reads and uses the canonical non-admin role accepted by pachanga_group_members_role_check; the production constraint remains unchanged."],
    expected: "Conduct SQL fixtures use existing membership roles and never weaken product constraints to make a diagnostic pass.",
    fixed: true,
    id: "SW-0089",
    operation: "conduct.tests.canonical_group_member_role",
    regressionVerified: true,
    reproductionSteps: ["Insert a Conduct V1 target fixture with role member", "Observe pachanga_group_members_role_check rejecting the row", "Confirm the transaction rolls back"],
    severity: "low",
  },
  {
    actual: "The outsider-report regression expected the generic Registered reporter required error, while the canonical RPC reached the stricter group-membership check and returned Reporter must currently belong to the reporting group.",
    category: "TESTABILITY_GAP",
    evidence: ["The regression now requires the precise membership denial and still verifies that no report, case or receipt is created."],
    expected: "Negative report tests assert the authoritative rejection layer actually reached by each fixture without accepting an arbitrary error.",
    fixed: true,
    id: "SW-0090",
    operation: "conduct.tests.outsider_report_denial_layer",
    regressionVerified: true,
    reproductionSteps: ["Authenticate a user with no reporting-group membership", "Submit a match-linked conduct report", "Observe the membership denial instead of the test's expected generic registration denial"],
    severity: "low",
  },
  {
    actual: "The SQL fixture inserted an already-finalized match in one read-model sync and sent its storage match_version 0, while Conduct V1 normalizes the first valid sporting-context revision to 1.",
    category: "TESTABILITY_GAP",
    evidence: ["The fixture now uses greatest(match_version, 1), matching the report context contract without changing the production read model or revision checks."],
    expected: "Synthetic report fixtures send the canonical context revision accepted by the server, including the initial revision normalization.",
    fixed: true,
    id: "SW-0091",
    operation: "conduct.tests.initial_match_context_revision",
    regressionVerified: true,
    reproductionSteps: ["Insert a finalized match directly into a fresh normalized read model", "Read storage match_version 0", "Submit it to Conduct V1", "Observe the server requiring canonical revision 1"],
    severity: "low",
  },
  {
    actual: "The SQL harness tried to read caseReference from the reporter response, but the privacy-preserving report receipt exposes only the reporter's opaque reportReference and no internal moderation-case identifier.",
    category: "TESTABILITY_GAP",
    evidence: ["The regression resolves the case only after restoring the privileged test role and joining the private report by operationId; the authenticated response remains unchanged."],
    expected: "Tests obtain internal case identifiers through privileged fixtures, never by expanding the user-facing report response.",
    fixed: true,
    id: "SW-0092",
    operation: "conduct.tests.private_case_reference_lookup",
    regressionVerified: true,
    reproductionSteps: ["Submit a valid report as an authenticated player", "Read caseReference from the response", "Observe an empty value because only reportReference is public"],
    severity: "low",
  },
  {
    actual: "The first anonymity assertion searched for the bare word reporter and flagged the safe boolean reporterIdentityVisibleToTarget=false as an identity leak.",
    category: "TESTABILITY_GAP",
    evidence: ["The replacement assertion checks the actual reporter UUID, the absence of inbound report objects and the explicit false privacy flag."],
    expected: "Anonymity regressions distinguish privacy metadata from identifying values and fail only on a real or reversible identity disclosure.",
    fixed: true,
    id: "SW-0093",
    operation: "conduct.tests.anonymity_false_positive",
    regressionVerified: true,
    reproductionSteps: ["Read the target conduct model", "Search its serialized text for reporter", "Match reporterIdentityVisibleToTarget=false despite no reporter identifier being present"],
    severity: "low",
  },
  {
    actual: "Resolving a real warning appeal reached its database update but PostgreSQL rejected resolution_note as ambiguous between the RPC parameter and the appeal-table column.",
    category: "PRODUCT_BUG",
    evidence: ["The authenticated warning -> appeal -> moderator correction regression exercises the original statement and verifies the warning becomes corrected while audit events remain."],
    expected: "An authorized moderator can uphold or correct an appeal exactly once without ambiguous SQL identifiers.",
    fixed: true,
    id: "SW-0094",
    operation: "conduct.appeals.resolve_note_authority",
    regressionVerified: true,
    reproductionSteps: ["Confirm a conduct case", "Issue a warning", "Appeal as the target", "Resolve it as moderator", "Observe PostgreSQL ambiguous_column on resolution_note"],
    severity: "high",
  },
  {
    actual: "After adding the mutual-retaliation fixture, the anonymity test still expected the target's submittedReports array to be empty even though that user had now authored one reciprocal report.",
    category: "TESTABILITY_GAP",
    evidence: ["The actor matrix now expects one self-authored opaque report while continuing to reject every inbound reporter UUID and identity."],
    expected: "A player may inspect their own report without gaining access to reports or identities submitted against them.",
    fixed: true,
    id: "SW-0095",
    operation: "conduct.tests.own_vote_anonymity_matrix",
    regressionVerified: true,
    reproductionSteps: ["Submit a report against the target", "Submit one reciprocal report as the target", "Read the target conduct model", "Observe one legitimate self-authored submittedReports entry"],
    severity: "low",
  },
  {
    actual: "The explicit moderator restriction path qualified a PL/pgSQL loop variable as moderate_pachanga_conduct_case_v1.restriction_type, which PostgreSQL interpreted as a missing table reference.",
    category: "PRODUCT_BUG",
    evidence: ["The restriction/appeal/expiry regression reaches the original branch and verifies one explicit social restriction, no automatic restriction and deterministic gate recovery."],
    expected: "A confirmed case can receive a moderator-selected social restriction without SQL name-resolution errors or sporting side effects.",
    fixed: true,
    id: "SW-0096",
    operation: "conduct.moderation.apply_social_restriction",
    regressionVerified: true,
    reproductionSteps: ["Enable social restrictions", "Confirm a moderation case", "Apply public_market for seven days", "Observe missing FROM-clause entry for moderate_pachanga_conduct_case_v1"],
    severity: "high",
  },
  {
    actual: "The social-action gate invoked restriction expiry, whose target_user_id filter was ambiguous between the helper parameter and the table column.",
    category: "PRODUCT_BUG",
    evidence: ["The gate and explicit expiry regression run with an active finite restriction, then verify it expires once and restores only the affected social capability."],
    expected: "Reading social gates and expiring finite restrictions never fails SQL name resolution and never touches sporting state.",
    fixed: true,
    id: "SW-0097",
    operation: "conduct.restrictions.expiry_target_filter",
    regressionVerified: true,
    reproductionSteps: ["Apply a finite social restriction", "Call get_pachanga_social_action_gate_v1", "Observe ambiguous_column on target_user_id in the expiry helper"],
    severity: "high",
  },
  {
    actual: "The first expiry fix renamed an existing function parameter, so PostgreSQL rejected the idempotent CREATE OR REPLACE migration with cannot change name of input parameter.",
    category: "PRODUCT_BUG",
    evidence: ["The migration keeps the published parameter name, copies it to an unambiguous local variable and reapplies cleanly over the existing local schema."],
    expected: "Conduct V1 migration remains safely re-runnable during local diagnostics and never requires a destructive function drop for an internal name fix.",
    fixed: true,
    id: "SW-0098",
    operation: "conduct.migration.function_parameter_compatibility",
    regressionVerified: true,
    reproductionSteps: ["Apply the original migration", "Rename target_user_id in CREATE OR REPLACE FUNCTION", "Reapply the migration", "Observe PostgreSQL 42P13"],
    severity: "medium",
  },
  {
    actual: "The Conduct V1 soak command exited successfully without printing its summary or refreshing the generated artifact because the root async run was started without a top-level await.",
    category: "TESTABILITY_GAP",
    evidence: ["npm run synthetic:conduct-v1 now awaits the root run and refreshes generatedAt only after source hashes, replay counts and full-season invariants pass."],
    expected: "A successful soak command waits for source replay, full-season invariants and artifact persistence before exiting.",
    fixed: true,
    id: "SW-0099",
    operation: "simulation.conduct_v1.await_root_run",
    regressionVerified: true,
    reproductionSteps: ["Record the generated conduct summary timestamp", "Run npm run synthetic:conduct-v1", "Observe exit code 0 with no JSON output", "Confirm the generated artifact timestamp did not change"],
    severity: "high",
  },
  {
    actual: "The published source-world stateHash included the runtime known-incident projection, so registering a new diagnostic incident changed the hash even though stored revision 313 and sequence 69458 were untouched.",
    category: "TESTABILITY_GAP",
    evidence: ["The unit regression mutates only diagnostic incidents and preserves the canonical hash; a new full replay kept 2753ab8f...431a at revision 313 and sequence 69458."],
    expected: "The canonical source integrity hash excludes diagnostic projections while a separate full-state before/after comparison still detects replay mutations.",
    fixed: true,
    id: "SW-0100",
    operation: "simulation.conduct_v1.canonical_source_hash",
    regressionVerified: true,
    reproductionSteps: ["Run Conduct V1 and record stateHash", "Add an unrelated known incident", "Run the read-only replay again", "Observe stateHash changing despite unchanged stored world revision and sequence"],
    severity: "medium",
  },
  {
    actual: "The V1 restriction catalog exposed receive_public_challenges and public_guest_access, but only challenge creation and open-match requests had database enforcement, leaving challenge acceptance/counterproposal and direct guest access ungated.",
    category: "PRODUCT_BUG",
    evidence: ["The SQL/RLS suite now proves challenge acceptance and direct accepted guest access are both rejected by authoritative triggers for the restricted user."],
    expected: "Every selectable social restriction is enforced on the authoritative database write and cannot rely on a client-side gate.",
    fixed: true,
    id: "SW-0101",
    operation: "conduct.restrictions.complete_server_enforcement",
    regressionVerified: true,
    reproductionSteps: ["Apply receive_public_challenges or public_guest_access", "Invoke the corresponding authoritative social write", "Observe the write is not rejected by a conduct gate"],
    severity: "critical",
  },
  {
    actual: "The first complete social-gate regression reached pachanga_has_active_social_restriction_v1 through the challenge trigger, where target_user_id was ambiguous between the function parameter and the restriction-table column.",
    category: "PRODUCT_BUG",
    evidence: ["The helper preserves its published signature through local unambiguous variables; migration reapply and the full social-gate SQL regression both pass."],
    expected: "Every restriction gate resolves its target and restriction type unambiguously under real trigger execution.",
    fixed: true,
    id: "SW-0102",
    operation: "conduct.restrictions.active_gate_parameter_resolution",
    regressionVerified: true,
    reproductionSteps: ["Enable social restrictions", "Insert a challenge through the gated table", "Enter pachanga_has_active_social_restriction_v1", "Observe target_user_id is ambiguous"],
    severity: "critical",
  },
  {
    actual: "The first full production build failed before compilation because this isolated worktree inherited a node_modules symlink pointing to a sibling worktree outside Turbopack's filesystem root.",
    category: "ENVIRONMENT_ISSUE",
    evidence: ["The worktree now has its own npm ci dependency directory and the Next.js 16 production build compiles, typechecks and generates all 27 static pages."],
    expected: "The isolated worktree uses its own dependency directory so Turbopack can resolve every package inside the project root.",
    fixed: true,
    id: "SW-0103",
    operation: "environment.conduct_worktree_local_dependencies",
    regressionVerified: true,
    reproductionSteps: ["Run npm test in the Conduct V1 worktree", "Enter next build", "Observe Turbopack reject the external node_modules symlink before compiling application code"],
    severity: "medium",
  },
  {
    actual: "The first full suite showed that new Conduct V1 mutations were invoked as RPCs but were not classified as writes by the PWA client-version bridge, so an incompatible installed client could bypass the write update gate.",
    category: "PRODUCT_BUG",
    evidence: ["The focused bridge regression now scans all three Conduct V1 clients: seven mutations classify as writes and six read-model RPCs remain readable."],
    expected: "Every Conduct V1 mutation is classified as an authoritative write while read-model RPCs remain available as reads.",
    fixed: true,
    id: "SW-0104",
    operation: "conduct.pwa_bridge.classify_all_mutations",
    regressionVerified: true,
    reproductionSteps: ["Run the complete browser RPC classifier test", "Inspect a Conduct V1 response or moderation RPC", "Observe classifyBrowserWrite returning null"],
    severity: "critical",
  },
  {
    actual: "Conduct V1 classifies every received report as requiring human review and immediately notifies moderators, including one non-serious report from one source against a player with no history.",
    category: "PRODUCT_BUG",
    evidence: ["Pending Conduct V1.1 triage regression."],
    expected: "Report receipt, human-review eligibility and sanction remain separate; an isolated non-serious signal is retained as record_only without immediate moderator work.",
    fixed: false,
    id: "SW-0105",
    operation: "conduct.triage.report_receipt_separation",
    regressionVerified: false,
    reproductionSteps: ["Submit one non-serious report from one source", "Observe the case entering the V1 moderation queue", "Observe an immediate moderator notification"],
    severity: "high",
  },
  {
    actual: "Conduct V1 keeps one open case per target, source type and category without an active-risk window, explainable queue or category-specific triage policy.",
    category: "PRODUCT_BUG",
    evidence: ["Pending temporal-policy and reason-code regressions."],
    expected: "Triage uses category-specific rules and finite active windows while preserving older evidence as audit history outside current operational risk.",
    fixed: false,
    id: "SW-0106",
    operation: "conduct.triage.temporal_category_policy",
    regressionVerified: false,
    reproductionSteps: ["Create one non-serious report", "Advance three years", "Submit a same-category report", "Observe the old open case still accumulating operational priority"],
    severity: "high",
  },
  {
    actual: "Conduct V1 has no authoritative, revisioned operations to merge duplicate moderation cases or split an incorrectly grouped case while preserving event history.",
    category: "PRODUCT_BUG",
    evidence: ["Pending merge/split SQL, RLS and concurrency regressions."],
    expected: "A security moderator can merge compatible cases and split selected reports through idempotent case-by-case RPCs with immutable lineage and no bulk sanction path.",
    fixed: false,
    id: "SW-0107",
    operation: "conduct.moderation.case_merge_split",
    regressionVerified: false,
    reproductionSteps: ["Open two related cases or one wrongly grouped case", "Inspect public moderation RPCs", "Observe no canonical merge or split operation"],
    severity: "medium",
  },
  {
    actual: "The Conduct V1 soak creates 290 possible no-shows among 640 players in one season, but that synthetic rate has not been shown to represent real Pachangas usage.",
    category: "NEEDS_PRODUCT_DECISION",
    evidence: ["V1.1 must compare 2/90 and 3/180 variants without using this generated distribution to change product policy."],
    expected: "Synthetic no-show volume is labelled as stress data until real attendance data can establish a plausible behavioral distribution.",
    fixed: false,
    id: "SW-0108",
    operation: "simulation.conduct.no_show_distribution_realism",
    regressionVerified: false,
    reproductionSteps: ["Run seed 20260819 for a full season", "Count 290 possible no-shows among 640 registered players", "Observe no external calibration baseline"],
    severity: "medium",
  },
  {
    actual: "Conduct V1 extrapolates raw cases but cannot simulate moderator throughput, backlog age or urgent cases waiting at five and ten cases per day.",
    category: "TESTABILITY_GAP",
    evidence: ["Pending deterministic moderation-capacity regression."],
    expected: "Synthetic World reports queue backlog, mean age and urgent waiting for explicit moderator capacities without auto-resolving or sanctioning cases.",
    fixed: false,
    id: "SW-0109",
    operation: "simulation.conduct.moderation_capacity",
    regressionVerified: false,
    reproductionSteps: ["Build the Conduct V1 replay", "Request capacity at 5 or 10 cases per day", "Observe only a linear raw-case extrapolation is available"],
    severity: "medium",
  },
];

export function knownIncidentsForWorld(seed: number, virtualDate: string): SyntheticIncident[] {
  return KNOWN_SYNTHETIC_INCIDENTS.map((item) => ({
    actual: { behavior: item.actual },
    actorAgentId: null,
    afterState: { resolution: { fixed: item.fixed, regressionVerified: item.regressionVerified } },
    beforeState: {},
    category: item.category,
    expected: { behavior: item.expected },
    id: deterministicUuid(`${seed}:known-incident`, item.id),
    occurrenceCount: 1,
    operation: item.operation,
    relatedEntityIds: [],
    reproductionSteps: item.reproductionSteps,
    resolution: { evidence: item.evidence, fixed: item.fixed, regressionVerified: item.regressionVerified },
    severity: item.severity,
    status: item.status ?? (item.regressionVerified ? "regression_verified" : "open"),
    virtualDate,
  }));
}

export function mergeKnownIncidents(world: SyntheticWorld) {
  const known = knownIncidentsForWorld(world.seed, world.startDate);
  const knownIds = new Set(known.map(({ id }) => id));
  world.state.incidents = [
    ...known,
    ...world.state.incidents.filter(({ id }) => !knownIds.has(id)),
  ];
  return world;
}
