import Link from "next/link";
import { notFound } from "next/navigation";
import { DataTable, Definition, Identifier, PageHeader, Panel, StatusBadge, formatAdminDate } from "../../_components/platform-ui";
import { requirePlatformPage } from "../../_lib/platform-auth";
import { getPlatformChallengeDetail } from "../../_lib/platform-data";
import styles from "../../platform-admin.module.css";

type Params = Promise<{ challengeId: string }>;
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export default async function PlatformChallengeDetailPage({ params }: { params: Params }) {
  const session = await requirePlatformPage("challenges.read");
  const { challengeId } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(challengeId)) notFound();
  const detail = await getPlatformChallengeDetail(session, challengeId);
  const challenge = record(detail.challenge); const sender = record(detail.groups.sender); const receiver = record(detail.groups.receiver); const match = record(detail.externalMatch);
  return <>
    <PageHeader title={`${String(sender.name ?? "Equipo A")} vs ${String(receiver.name ?? "Equipo B")}`} subtitle="Timeline autoritativo del Reto, propuesta de resultado, confirmación y evidencia posterior." actions={<Link className={styles.secondaryButton} href="/admin/challenges">Volver</Link>} />
    <div className={styles.detailGrid}>
      <section><h2>Reto</h2><dl className={styles.definitionList}><Definition label="ID"><Identifier value={challengeId} /></Definition><Definition label="Estado"><StatusBadge>{String(challenge.status)}</StatusBadge></Definition><Definition label="Revisión">{String(challenge.revision)}</Definition><Definition label="Propuesta">#{String(challenge.proposal_number)}</Definition><Definition label="Actualizado">{formatAdminDate(challenge.updated_at)}</Definition></dl></section>
      <section><h2>Equipos</h2><dl className={styles.definitionList}><Definition label="Emisor"><Link href={`/admin/teams/${String(challenge.sender_group_id)}`}>{String(sender.name ?? "Equipo")}</Link></Definition><Definition label="Receptor"><Link href={`/admin/teams/${String(challenge.receiver_group_id)}`}>{String(receiver.name ?? "Equipo")}</Link></Definition><Definition label="Última propuesta"><Link href={`/admin/teams/${String(challenge.last_proposed_by_group_id)}`}><Identifier value={String(challenge.last_proposed_by_group_id)} /></Link></Definition></dl></section>
      <section><h2>Convocatoria</h2><dl className={styles.definitionList}><Definition label="Fecha">{formatAdminDate(challenge.scheduled_at)}</Definition><Definition label="Modalidad">{String(challenge.modality)}</Definition><Definition label="Campo">{String(challenge.field_name)}</Definition><Definition label="Dirección">{String(challenge.field_address)}</Definition></dl></section>
    </div>
    <Panel title={`Timeline del Reto (${detail.timeline.length})`}><DataTable label="Timeline del Reto"><thead><tr><th>Secuencia</th><th>Evento</th><th>Actor</th><th>Revisión</th><th>Snapshot</th><th>Fecha</th></tr></thead><tbody>{detail.timeline.map((item) => { const row = record(item); const snapshot = record(row.snapshot); return <tr key={String(row.id)}><td>{String(row.server_sequence)}</td><td><StatusBadge>{String(row.event_type)}</StatusBadge></td><td><Link href={`/admin/teams/${String(row.actor_group_id)}`}><Identifier value={String(row.actor_group_id)} /></Link></td><td>{String(row.challenge_revision)}</td><td>{String(snapshot.status ?? "-")} · {String(snapshot.modality ?? "-")} · {formatAdminDate(snapshot.scheduledAt)}</td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
    <Panel title="Partido externo"><dl className={`${styles.definitionList} ${styles.panelDefinitions}`}><Definition label="External match"><Identifier value={typeof match.id === "string" ? match.id : null} /></Definition><Definition label="Estado"><StatusBadge>{String(match.state ?? "no creado")}</StatusBadge></Definition><Definition label="Revisión">{String(match.revision ?? "-")}</Definition><Definition label="Versión oficial">{String(match.official_version ?? "-")}</Definition><Definition label="Marcador oficial">{match.canonical_score_home == null ? "Pendiente" : `${String(match.canonical_score_home)} - ${String(match.canonical_score_away)}`}</Definition><Definition label="Disputa">{formatAdminDate(match.disputed_at)}</Definition><Definition label="Oficial">{formatAdminDate(match.official_at)}</Definition></dl></Panel>
    <div className={styles.overviewColumns}>
      <Panel title={`Propuestas de resultado (${detail.versions.length})`}><DataTable label="Versiones de resultado"><thead><tr><th>Versión</th><th>Tipo</th><th>Proponente</th><th>Marcador</th><th>Fecha</th></tr></thead><tbody>{detail.versions.map((item) => { const row = record(item); return <tr key={String(row.version)}><td>{String(row.version)}</td><td>{String(row.proposal_kind)}</td><td><Identifier value={String(row.proposed_by_group_id)} /></td><td>{String(row.score_home)} - {String(row.score_away)}</td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
      <Panel title={`Confirmaciones (${detail.attestations.length})`}><DataTable label="Confirmaciones de resultado"><thead><tr><th>Equipo</th><th>Decisión</th><th>Versión</th><th>Jugadores</th><th>Fecha</th></tr></thead><tbody>{detail.attestations.map((item) => { const row = record(item); return <tr key={String(row.id)}><td><Identifier value={String(row.group_id)} /></td><td><StatusBadge>{String(row.decision)}</StatusBadge></td><td>{String(row.result_version)}</td><td>{String(row.participant_count)}</td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
    </div>
    <Panel title={`Eventos del resultado (${detail.resultEvents.length})`}><DataTable label="Eventos del resultado"><thead><tr><th>Secuencia</th><th>Evento</th><th>Equipo</th><th>Revisión</th><th>Versión</th><th>Fecha</th></tr></thead><tbody>{detail.resultEvents.map((item) => { const row = record(item); return <tr key={String(row.id)}><td>{String(row.server_sequence)}</td><td><StatusBadge>{String(row.event_type)}</StatusBadge></td><td><Identifier value={String(row.actor_group_id)} /></td><td>{String(row.match_revision)}</td><td>{String(row.result_version)}</td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
    <div className={styles.overviewColumns}>
      <Panel title={`Evidencia de progresión (${detail.progression.length})`}><DataTable label="Evidencia de progresión"><thead><tr><th>Estado</th><th>Resultado</th><th>Secuencia</th><th>Aplicado</th></tr></thead><tbody>{detail.progression.map((item) => { const row = record(item); return <tr key={String(row.id)}><td><StatusBadge>{String(row.state)}</StatusBadge></td><td>{String(row.outcome)} · {String(row.goals_for)}:{String(row.goals_against)}</td><td>{String(row.server_sequence)}</td><td>{formatAdminDate(row.applied_at)}</td></tr>; })}</tbody></DataTable></Panel>
      <Panel title={`Notificaciones (${detail.notifications.length})`}><DataTable label="Notificaciones del Reto"><thead><tr><th>Título</th><th>Categoría</th><th>Prioridad</th><th>Fecha</th></tr></thead><tbody>{detail.notifications.map((item) => { const row = record(item); return <tr key={String(row.id)}><td>{String(row.title)}</td><td>{String(row.category)}</td><td><StatusBadge>{String(row.priority)}</StatusBadge></td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
    </div>
  </>;
}
