import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds Pachangas IQ HTML", async () => {
  const html = await readFile(new URL("../.next/server/app/index.html", import.meta.url), "utf8");
  assert.match(html, /<html lang="es">/i);
  assert.match(html, /<title>Pachangas IQ<\/title>/i);
  assert.match(html, /El grupo del partido, pero con memoria\./);
  assert.match(html, /Confirmados/);
  assert.match(html, /Alineación/i);
  assert.match(html, /Alineación abierta/);
  assert.match(html, /Continuar con Google/);
  assert.match(html, /Mi equipo/);
  assert.match(html, /Finalizar partido/);
  assert.match(html, /Añadir foto del partido/);
  assert.match(html, /Comparte este partido!/);
  assert.match(html, /Tiempo previsto/);
  assert.match(html, /Copiar link/);
  assert.match(html, /Próximos partidos/);
  assert.match(html, /Temporada/);
  assert.match(html, /Ordenar por/);
  assert.match(html, /2025-2026/);
  assert.match(html, /Navegación principal móvil/);
  assert.match(html, /Abrir manual de usuario/);
  assert.match(html, /Mercado/);
  assert.match(html, /\/brand\/pachangas-logo-hero\.png/);
  assert.match(html, /\/manifest\.webmanifest/);
  assert.match(html, /\/apple-touch-icon\.png/);
  assert.match(html, /\/icon-192\.png/);
  assert.match(html, /Aviso legal/);
  assert.match(html, /Privacidad/);
  assert.match(html, /Cookies/);
  assert.match(html, /Condiciones de venta/);
  assert.doesNotMatch(html, /Manual de usuario<\/span>/);
  assert.doesNotMatch(html, /Registro/);
  assert.doesNotMatch(html, /Entra para crear tu equipo/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site|react-loading-skeleton/i);
});

test("builds the user manual as its own page", async () => {
  const html = await readFile(new URL("../.next/server/app/manual.html", import.meta.url), "utf8");
  assert.match(html, /Manual de usuario/);
  assert.match(html, /Primera entrada/);
  assert.match(html, /Crear o entrar en un grupo de pachangas/);
  assert.match(html, /Crear &gt; Grupo/);
  assert.match(html, /Crear &gt; Ficha jugador/);
  assert.match(html, /Campos y ajustes iniciales/);
  assert.match(html, /Prueba gratuita y suscripción/);
  assert.match(html, /2 partidos gratis/);
  assert.match(html, /Plan mensual: 5,99 € al mes/);
  assert.match(html, /Fórmula del trial/);
  assert.match(html, /Crear partido/);
  assert.match(html, /Crear &gt; Partido/);
  assert.match(html, /Guardar partido/);
  assert.match(html, /fecha, modalidad/);
  assert.match(html, /se calcula desde la fecha y se guarda en la ficha del partido/);
  assert.match(html, /empieza en septiembre y termina en agosto/);
  assert.match(html, /Jugador y admin/);
  assert.match(html, /Si cambias de Voy a Duda o No/);
  assert.match(html, /dólar dorado/);
  assert.match(html, /dólar en verde/);
  assert.match(html, /Cualquier miembro puede subir una foto del partido/);
  assert.match(html, /foto en miniatura/);
  assert.match(html, /copias automáticas al guardar o finalizar un partido/);
  assert.match(html, /Borrar jugador lo deja fuera del grupo/);
  assert.match(html, /El ranking se puede filtrar/);
  assert.match(html, /Media, forma y equilibrio/);
  assert.match(html, /Media real = promedio/);
  assert.match(html, /Forma actual = porcentaje temporal visible de 0 a 100/);
  assert.match(html, /Forma pendiente/);
  assert.match(html, /Valor para equilibrar = media real multiplicada por forma actual/);
  assert.match(html, /Fiabilidad = 100% menos 7 puntos/);
  assert.match(html, /Gestión de jugadores/);
  assert.match(html, /Configuración profunda y copias/);
  assert.match(html, /Mercado de fichajes/);
  assert.match(html, /Google Places/);
  assert.match(html, /página separada del grupo privado/);
  assert.match(html, /El nombre del campo debe elegirse desde una sugerencia/);
  assert.match(html, /Google Weather/);
  assert.match(html, /Tiempo previsto/);
  assert.match(html, /Volver/);
});

test("builds the transfer market as a separated page", async () => {
  const html = await readFile(new URL("../.next/server/app/mercado.html", import.meta.url), "utf8");
  assert.match(html, /Mercado de fichajes/);
  assert.match(html, /Filtros del mercado de fichajes/);
  assert.doesNotMatch(html, /Jugadores disponibles por zona y horario/);
  assert.doesNotMatch(html, /Un escaparate separado del grupo privado/);
  assert.match(html, /Zona/);
  assert.match(html, /Día/);
  assert.match(html, /Modalidad/);
  assert.match(html, /Posición/);
  assert.match(html, /Jugadores disponibles/);
  assert.match(html, /Partidos abiertos/);
  assert.match(html, /38 años/);
  assert.match(html, /Solo admins invitan/);
  assert.match(html, /Invitado puntual/);
  assert.doesNotMatch(html, /\/brand\/pachangas-logo-wide\.png/);
});

test("builds the legal pages", async () => {
  const [legal, privacy, cookies, terms, sales] = await Promise.all([
    readFile(new URL("../.next/server/app/aviso-legal.html", import.meta.url), "utf8"),
    readFile(new URL("../.next/server/app/privacidad.html", import.meta.url), "utf8"),
    readFile(new URL("../.next/server/app/cookies.html", import.meta.url), "utf8"),
    readFile(new URL("../.next/server/app/condiciones.html", import.meta.url), "utf8"),
    readFile(new URL("../.next/server/app/condiciones-venta.html", import.meta.url), "utf8"),
  ]);

  assert.match(legal, /Aviso legal/);
  assert.match(legal, /Datos legales del responsable pendientes de completar/);
  assert.match(legal, /Ley 34\/2002/);
  assert.match(privacy, /Política de privacidad/);
  assert.match(privacy, /Supabase/);
  assert.match(privacy, /Stripe/);
  assert.match(privacy, /Google Maps Platform/);
  assert.match(privacy, /Google Weather/);
  assert.match(privacy, /direcciones verificadas de instalaciones deportivas/);
  assert.match(privacy, /previsión meteorológica/);
  assert.match(privacy, /mercado de fichajes/);
  assert.match(cookies, /Política de cookies/);
  assert.match(cookies, /No usamos cookies de publicidad/);
  assert.match(terms, /Condiciones de uso/);
  assert.match(terms, /Owner/);
  assert.match(terms, /Mercado de fichajes/);
  assert.match(terms, /ubicación verificada del campo/);
  assert.match(sales, /Condiciones de contratación/);
  assert.match(sales, /Plan mensual: 5,99 € al mes/);
  assert.match(sales, /Plan anual: 64,99 € al año/);
  assert.match(sales, /Stripe/);
});

test("keeps the project wired to the Pachangas app", async () => {
  const [
    page,
    layout,
    legalData,
    packageJson,
    supabaseClient,
    globalsCss,
    googleAuthPage,
    supabaseSql,
    billingShared,
    billingCheckout,
    billingPortal,
    stripeWebhook,
    envExample,
    googlePlacesClient,
    marketPage,
    weatherRoute,
    manifest,
    pwaRuntime,
    adaptiveWindow,
    serviceWorker,
    nextConfig,
    adaptiveDocs,
  ] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/legal-data.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/supabaseClient.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/auth/google/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../supabase/pachangas.sql", import.meta.url), "utf8"),
    readFile(new URL("../app/api/billing/_shared.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/billing/checkout/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/billing/portal/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/api/stripe/webhook/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../.env.example", import.meta.url), "utf8"),
    readFile(new URL("../app/googlePlacesClient.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/mercado/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/api/weather/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/manifest.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/pwa-runtime.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/adaptive-window.ts", import.meta.url), "utf8"),
    readFile(new URL("../public/sw.js", import.meta.url), "utf8"),
    readFile(new URL("../next.config.ts", import.meta.url), "utf8"),
    readFile(new URL("../docs/android-adaptive-compatibility.md", import.meta.url), "utf8"),
  ]);

  assert.match(page, /join_pachanga_team/);
  assert.match(page, /MemberRole/);
  assert.match(page, /incomingSharedLinkFromSearch/);
  assert.match(page, /needsLoginForSharedLink/);
  assert.match(page, /Continuar con Google y volver/);
  assert.match(page, /GoogleLogo/);
  assert.match(page, /google-signin-button/);
  assert.match(page, /google-signout-button/);
  assert.match(page, /hero-account-row/);
  assert.match(page, /Cerrar sesión/);
  assert.match(page, /Crea tu ficha para poder marcar/);
  assert.match(page, /gated-shell/);
  assert.doesNotMatch(page, /match-focus-card/);
  assert.doesNotMatch(page, /Resumen del partido/);
  assert.match(page, /create-menu/);
  assert.match(page, /create-menu-panel/);
  assert.match(page, /createMenuRef/);
  assert.match(page, /document\.addEventListener\("pointerdown", closeCreateMenu\)/);
  assert.match(page, /document\.addEventListener\("keydown", closeCreateMenuWithKeyboard\)/);
  assert.match(page, /event\.key === "Escape"/);
  assert.match(page, /aria-haspopup="menu"/);
  assert.match(page, /personal-action-button/);
  assert.match(page, /Mi ficha/);
  assert.match(page, /Mi equipo/);
  assert.match(page, /openGroupSwitcher/);
  assert.match(page, /teamAccessPanelRef/);
  assert.match(page, /team-move-label/);
  assert.match(page, /Equipo 2/);
  assert.match(page, /Ficha jugador/);
  assert.match(page, /Grupo de pachangas/);
  assert.match(page, /mobile-account-sheet/);
  assert.match(page, /Perfil y ajustes/);
  assert.match(page, /canUseAdminControls \? \(/);
  assert.match(page, /closeSettingsPanelWithoutSave/);
  assert.match(page, /Cerrar sin guardar/);
  assert.match(page, /Admins · permisos solo owner/);
  assert.match(page, /canManageRoles/);
  assert.match(page, /Permisos de admin/);
  assert.match(page, /Solo owner/);
  assert.match(page, /Da o quita permisos de admin/);
  assert.match(page, /openOwnPlayerProfile/);
  assert.match(page, /type ProfilePane = "ficha" \| "ranking"/);
  assert.match(page, /setProfilePane\("ficha"\)/);
  assert.match(page, /type MatchManagerPane = "proximo" \| "alineacion" \| "resultado" \| "historico" \| "admin"/);
  assert.match(page, /matchManagerPaneLabels/);
  assert.match(page, /activeMatchManagerPane/);
  assert.match(page, /data-match-manager-pane=\{selectedMatchManagerPane\}/);
  assert.match(page, /className="match-manager-subnav"/);
  assert.match(page, /setActiveMatchManagerPane\(pane\)/);
  assert.match(page, /className="lineup-side-tools"/);
  assert.match(page, /Herramientas/);
  assert.doesNotMatch(page, /className="lineup-side-balance"/);
  assert.match(page, /className="lineup-side-actions"/);
  assert.match(page, /<button type="button" onClick=\{applyRandomTeams\} disabled=\{!canEditLineup\}>Aleatorio<\/button>/);
  assert.match(page, /<button type="button" onClick=\{applyBalancedTeams\} disabled=\{!canEditLineup\}>Equilibrado<\/button>/);
  assert.match(page, /lineupClosed \? "Abrir" : "Cerrar"/);
  assert.match(page, /pitch-board-mode/);
  assert.match(page, /Entrar en modo pizarra/);
  assert.match(page, /Dibujar con color del equipo 1/);
  assert.match(page, /Dibujar con color del equipo 2/);
  assert.match(page, /Ocultar fichas de la pizarra/);
  assert.match(page, /Borrar pizarra/);
  assert.match(page, /match-manager-admin-block/);
  assert.match(page, /lineup-title-result/);
  assert.match(page, /nextMatchStatusGroups/);
  assert.match(page, /className="next-match-roster-rail"/);
  assert.match(page, /Reservas/);
  assert.match(page, /label = null/);
  assert.doesNotMatch(page, /Recuperando ritmo/);
  assert.doesNotMatch(page, /label = "Volviendo"/);
  assert.match(page, /renderPlayerCard\(player, undefined, "reserve"\)/);
  assert.match(page, /renderPlayerCard\(player, undefined, "waiting"\)/);
  assert.match(page, /isReserve && context !== "reserve"/);
  assert.match(page, /isWaiting && context !== "waiting"/);
  assert.doesNotMatch(page, /overallScore\(playerMediaScore\(player\)\)\}\)\{mediaSource \? ` · \$\{mediaSource\}` : ""\}/);
  const nextMatchStatsStart = page.indexOf('<div className="stats-row">');
  const nextMatchStatsEnd = page.indexOf("{siteSettings.subscriptionContributionEnabled", nextMatchStatsStart);
  assert.ok(nextMatchStatsStart > 0 && nextMatchStatsEnd > nextMatchStatsStart);
  assert.doesNotMatch(page.slice(nextMatchStatsStart, nextMatchStatsEnd), /<span>Faltan<\/span>/);
  assert.match(page, /Otros estados/);
  assert.match(page, /Sin respuesta/);
  assert.match(page, /Lesionados/);
  assert.match(page, /function openRankingPanel/);
  assert.match(page, /function openMarketConfiguration/);
  assert.match(page, /if \(tabId === "mercado"\) \{\s*if \(canUseAdminControls\) return;/);
  assert.match(page, /if \(requestedTab === "perfil"\) \{[\s\S]*setProfilePane\("ficha"\);[\s\S]*setSelectedPlayerId\(ownPlayer\?\.id \?\? selectedPlayerId \?\? players\[0\]\?\.id \?\? ""\)/);
  assert.match(page, /complete_pachanga_player_initial_assessment/);
  assert.match(page, /complete_pachanga_player_advanced_assessment/);
  assert.match(page, /Este test crea tu ficha real y solo se puede completar una vez por usuario/);
  assert.match(page, /Mejorar precisión de mi ficha/);
  assert.match(page, /openCreatePlayerProfile/);
  assert.match(page, /runCreateAction\(\(\) => void openCreatePlayerProfile\(\)\)/);
  assert.match(page, /showQuickForm\("venue"\)/);
  assert.match(page, /showQuickForm\("team"\)/);
  assert.match(page, /runCreateAction\(createMatch\)/);
  assert.match(page, /attachVenueAutocomplete/);
  assert.match(page, /NEXT_PUBLIC_GOOGLE_MAPS_API_KEY/);
  assert.match(page, /selectedVenuePlace/);
  assert.match(page, /Dirección verificada/);
  assert.match(page, /Google Places pendiente/);
  assert.match(page, /Mostrarme en mercado de fichajes/);
  assert.match(page, /marketZoneRadiusOptions/);
  assert.match(page, /Solo esta población/);
  assert.match(page, /marketZonesGeo/);
  assert.match(page, /appendMarketZoneGeo/);
  assert.match(page, /updateMarketZoneRadius/);
  assert.match(page, /marketModalitiesForPlayer/);
  assert.match(page, /syncOwnMarketProfile/);
  assert.match(page, /sync_pachanga_market_profile/);
  assert.match(page, /marketScoutUrl/);
  assert.match(page, /params\.set\("partido", activeMatch\.id\)/);
  assert.match(page, /params\.set\("modalidad", activeKind\)/);
  assert.match(page, /params\.set\("plazas", String\(missing\)\)/);
  assert.match(googlePlacesClient, /maps\/api\/js/);
  assert.match(googlePlacesClient, /libraries", "places"/);
  assert.match(googlePlacesClient, /callback", "__pachangasGooglePlacesReady"/);
  assert.match(googlePlacesClient, /importLibrary\?\.\("places"\)/);
  assert.match(googlePlacesClient, /PlaceAutocompleteElement/);
  assert.match(googlePlacesClient, /gmp-select/);
  assert.match(googlePlacesClient, /includedRegionCodes = \["es"\]/);
  assert.match(googlePlacesClient, /Autocomplete/);
  assert.match(googlePlacesClient, /componentRestrictions: \{ country: "es" \}/);
  assert.ok(
    googlePlacesClient.indexOf("const Autocomplete = googleMapsWindow().google?.maps?.places?.Autocomplete") <
      googlePlacesClient.indexOf("const newPlacesCleanup = attachNewPlaceAutocomplete"),
    "Google Places should keep the normal input as the primary autocomplete path",
  );
  assert.match(globalsCss, /\.pachangas-place-autocomplete/);
  assert.match(marketPage, /pachanga_market_profiles/);
  assert.match(marketPage, /pachanga_open_matches/);
  assert.match(marketPage, /zones_geo/);
  assert.match(marketPage, /zonesGeo/);
  assert.match(marketPage, /distanceKmBetween/);
  assert.match(marketPage, /profileZoneMatch/);
  assert.match(marketPage, /openMatchZoneMatch/);
  assert.match(marketPage, /activeMarketTarget/);
  assert.match(marketPage, /misma población/);
  assert.match(marketPage, /filteredOpenMatches/);
  assert.match(marketPage, /Partidos abiertos/);
  assert.match(marketPage, /pachanga_open_match_requests/);
  assert.match(marketPage, /requestOpenMatch/);
  assert.match(marketPage, /request_pachanga_open_match/);
  assert.match(marketPage, /operation_key: crypto\.randomUUID\(\)/);
  assert.match(marketPage, /target_open_match_id/);
  assert.match(marketPage, /requester_user_id/);
  assert.match(marketPage, /Solicitar plaza/);
  assert.match(marketPage, /Solicitud enviada/);
  assert.match(marketPage, /Admin acepta/);
  assert.match(marketPage, /Nivel equipo/);
  assert.match(marketPage, /Solo admins invitan/);
  assert.match(marketPage, /Invitar desde un partido/);
  assert.match(marketPage, /MarketMatchContext/);
  assert.match(marketPage, /Filtros aplicados desde el partido/);
  assert.match(marketPage, /copyMarketInvite/);
  assert.match(marketPage, /Copiar invitación/);
  assert.match(marketPage, /marketInviteText/);
  assert.doesNotMatch(page, /top-panel quick-create-form top-player-form/);
  assert.doesNotMatch(page, /Nombre del jugador/);
  assert.doesNotMatch(page, /Guardar jugador/);
  assert.match(page, /top-panel quick-create-form top-venue-form/);
  assert.match(page, /Crea tu primer partido desde “Crear”/);
  assert.match(page, /Campos guardados/);
  assert.match(page, /deleteVenue/);
  assert.match(page, /Los partidos históricos conservarán el nombre del campo/);
  assert.match(globalsCss, /\.saved-venues-panel/);
  assert.match(globalsCss, /\.saved-venue-list/);
  assert.match(globalsCss, /\.quick-create-form/);
  assert.ok(page.indexOf("top-panel quick-create-form top-venue-form") < page.indexOf("team-access-panel"));
  assert.match(globalsCss, /\.create-menu-panel/);
  assert.doesNotMatch(globalsCss, /\.top-player-form/);
  assert.match(page, /MobileAppNav/);
  assert.match(page, /mobileNavigationTabs/);
  assert.match(page, /activeMobileTab/);
  assert.match(page, /navigateMobileTab/);
  assert.match(page, /onNavigate=\{navigatePrimaryMobile\}/);
  assert.match(page, /id="partido"/);
  assert.match(page, /id="alineacion"/);
  assert.match(page, /className="panel teams-panel lineup-panel"/);
  assert.match(page, /team-player-column status-roster-column reserve-roster-column next-match-reserve-section/);
  assert.match(page, /team-player-column status-roster-column waiting-roster-column next-match-waiting-section/);
  assert.match(page, /team-player-column status-roster-column other-status-roster-column next-match-status-section/);
  assert.doesNotMatch(page, /className="reserve-section next-match-reserve-section"/);
  assert.match(page, /\{ value: "Mediocentro \/ pivote", line: "Medio", short: "PIV" \}/);
  assert.match(page, /<span className="player-meta" title=\{positionLabel\(player\)\} aria-label=\{positionLabel\(player\)\}>\s*\{positionShort\(player\)\}/);
  assert.match(page, /<small className="position-pill" title=\{positionLabel\(player\)\} aria-label=\{positionLabel\(player\)\}>/);
  assert.match(page, /id="ranking"/);
  assert.match(page, /if \(requestedTab === "equipo"\) \{[\s\S]*setProfilePane\("ranking"\);[\s\S]*setTeamGalleryOpen\(false\)/);
  assert.match(page, /if \(tabId === "equipo"\) \{[\s\S]*setProfilePane\("ranking"\);[\s\S]*setTeamGalleryOpen\(false\)/);
  assert.match(page, /RankingSort/);
  assert.match(page, /rankingSeason/);
  assert.match(page, /historySeason/);
  assert.match(page, /filteredClosedMatches/);
  assert.match(page, /result-score-field team-a-score/);
  assert.match(page, /Resultado equipo 1/);
  assert.match(page, /consecutiveAbsenceStreak/);
  assert.match(page, /absenceStreaks/);
  assert.match(page, /showAbsenceStreak/);
  assert.match(page, /sin venir/);
  assert.match(page, /matchCardAge/);
  assert.match(page, /player-age-inline/);
  assert.match(globalsCss, /\.player-age-inline/);
  assert.match(page, /playerRatingTrend/);
  assert.match(page, /renderRatingTrendChip/);
  assert.match(page, /Media subiendo/);
  assert.match(page, /Media bajando/);
  assert.match(page, /Media estable/);
  assert.match(page, /PlayerFormState/);
  assert.match(page, /hasData/);
  assert.match(page, /playerFormState/);
  assert.match(page, /visibleFormPercent/);
  assert.match(page, /playerFormStates/);
  assert.match(page, /matchFormRatingForPlayer/);
  assert.match(page, /playerReliability/);
  assert.match(page, /Forma actual/);
  assert.match(page, /Forma pendiente/);
  assert.match(page, /Valor para equilibrar/);
  assert.match(page, /media real, forma actual/);
  assert.match(page, /matchImpactForPlayer/);
  assert.match(page, /teamHasFixedKeeper/);
  assert.match(page, /portería a cero/);
  assert.match(page, /playerBalancePower/);
  assert.match(page, /playerGoalsPerMatch/);
  assert.match(page, /playerWinRate/);
  assert.match(page, /teamBalanceSummary/);
  assert.match(page, /Equilibrio de equipos/);
  assert.match(page, /leadingTeam/);
  assert.match(page, /weakerTeam/);
  assert.match(page, /compactEdge/);
  assert.match(page, /más fuerte/);
  assert.match(page, /goles\/partido/);
  assert.match(page, /footballSeasonStartMonth/);
  assert.match(page, /parsed\.getMonth\(\) >= footballSeasonStartMonth/);
  assert.match(page, /rankingSortLabels/);
  assert.match(page, /seasonKey/);
  assert.match(page, /matchSeason/);
  assert.match(page, /season: seasonKey/);
  assert.match(page, /season: seasonKey\(activeMatch\.date\)/);
  assert.doesNotMatch(page, /updateMatchSettings\(\{ \.\.\.activeMatch, season: event\.target\.value \}\)/);
  assert.match(page, /rankingBadgeText/);
  assert.match(page, /teamPhoto\?: string/);
  assert.match(page, /matchPhotoDataUrl/);
  assert.match(page, /canUploadTeamPhoto/);
  assert.match(page, /Añadir foto del partido/);
  assert.match(page, /Quitar foto/);
  assert.match(page, /history-photo/);
  assert.match(page, /history-season-filter/);
  assert.match(page, /No hay partidos en esta temporada/);
  assert.match(googleAuthPage, /safeReturnUrl/);
  assert.match(googleAuthPage, /url\.origin !== window\.location\.origin/);
  assert.match(page, /sha256Hex\(rawNonce\)/);
  assert.match(page, /authUrl\.searchParams\.set\("nonce", hashedNonce\)/);
  assert.match(page, /className="history-month"/);
  assert.match(page, /joinedAtLabel/);
  assert.match(page, /Voy desde/);
  assert.match(page, /perderá su posición/);
  assert.match(page, /Movimiento de plaza/);
  assert.match(page, /className="fifa-photo-action" title=\{selectedAvatarPreview \? "Cambiar foto" : "Añadir foto"\}/);
  assert.match(page, /playerPhotoPromptForChatGpt/);
  assert.match(page, /Crea un retrato profesional desde los hombros hacia arriba/);
  assert.match(page, /Prompt para ChatGPT/);
  assert.match(page, /Copiar prompt/);
  assert.match(page, /Salida final en PNG con fondo transparente/);
  assert.match(globalsCss, /\.side-history \.history/);
  assert.match(globalsCss, /\.side-history::after/);
  assert.match(globalsCss, /\.history-season-filter/);
  assert.match(globalsCss, /\.fifa-photo-action input/);
  assert.doesNotMatch(globalsCss, /\.fifa-player-card input\s*\{/);
  assert.match(globalsCss, /\.result-score-field span/);
  assert.match(globalsCss, /\.team-b-score/);
  assert.match(globalsCss, /data-match-manager-pane="resultado"[\s\S]*\.scorers-team/);
  assert.match(globalsCss, /data-match-manager-pane="resultado"[\s\S]*--scorer-accent/);
  assert.match(globalsCss, /data-match-manager-pane="resultado"[\s\S]*\.scorer-row/);
  assert.match(globalsCss, /::-webkit-calendar-picker-indicator/);
  assert.match(globalsCss, /\.absence-chip/);
  assert.match(globalsCss, /\.rating-trend-chip/);
  assert.match(globalsCss, /\.rating-trend-up/);
  assert.match(globalsCss, /\.rating-trend-down/);
  assert.match(globalsCss, /\.rating-trend-flat/);
  assert.match(globalsCss, /\.pitch-player-card \.rating-trend-chip/);
  assert.match(globalsCss, /\.form-chip/);
  assert.match(globalsCss, /\.form-state-card/);
  assert.match(globalsCss, /\.form-state-card\.form-pending/);
  assert.match(globalsCss, /\.balance-summary/);
  assert.match(globalsCss, /scrollbar-color:\s*#64748b #ebe7dc/);
  assert.match(globalsCss, /\.side-history \.history::\-webkit-scrollbar-thumb/);
  assert.match(globalsCss, /\.joined-at/);
  assert.match(globalsCss, /\.shared-link-gate/);
  assert.match(globalsCss, /\.gated-shell/);
  assert.doesNotMatch(globalsCss, /\.match-focus-card/);
  assert.match(globalsCss, /\.mobile-app-nav/);
  assert.match(globalsCss, /\.mobile-app-nav-item/);
  assert.match(globalsCss, /\.mobile-app-nav-item\.active/);
  assert.match(globalsCss, /--app-viewport-height:\s*100dvh/);
  assert.match(globalsCss, /--mobile-nav-height/);
  assert.match(globalsCss, /--game-side-nav-width/);
  assert.match(globalsCss, /--tap-target/);
  assert.match(globalsCss, /container-type:\s*inline-size/);
  assert.match(globalsCss, /@container \(max-width: 520px\)/);
  assert.match(globalsCss, /@container \(max-width: 360px\)/);
  assert.match(globalsCss, /@media \(orientation: landscape\) and \(max-height: 560px\) and \(max-width: 740px\)/);
  assert.match(globalsCss, /touch-action:\s*manipulation/);
  assert.match(globalsCss, /\.match-manager-subnav/);
  assert.match(globalsCss, /\.lineup-side-tools/);
  assert.match(globalsCss, /\.lineup-side-tools-kicker/);
  assert.doesNotMatch(globalsCss, /\.lineup-side-balance/);
  assert.match(globalsCss, /\.lineup-side-actions button/);
  assert.match(globalsCss, /\.lineup-side-state\.closed/);
  assert.match(globalsCss, /data-match-manager-pane="proximo"/);
  assert.match(globalsCss, /data-match-manager-pane="alineacion"/);
  assert.match(globalsCss, /data-match-manager-pane="resultado"/);
  assert.match(globalsCss, /data-match-manager-pane="historico"/);
  assert.match(globalsCss, /data-match-manager-pane="admin"/);
  assert.match(globalsCss, /data-match-manager-pane="admin"[\s\S]*\.next-match-roster-rail/);
  assert.match(globalsCss, /\.next-match-roster-rail/);
  assert.match(globalsCss, /grid-auto-flow:\s*column/);
  assert.match(globalsCss, /scroll-snap-type:\s*x proximity/);
  assert.match(globalsCss, /main\[data-mobile-tab="partido"\] \.team-player-column[\s\S]*grid-auto-rows:\s*max-content/);
  assert.match(globalsCss, /main\[data-mobile-tab="partido"\] \.player-card[\s\S]*min-height:\s*58px/);
  assert.match(globalsCss, /\.next-match-status-section/);
  assert.match(globalsCss, /\.status-roster-column/);
  assert.match(globalsCss, /\.reserve-roster-column/);
  assert.match(globalsCss, /\.other-status-roster-column/);
  assert.match(globalsCss, /\.status-roster-column > \.team-column-title/);
  assert.match(globalsCss, /\.mobile-account-sheet/);
  assert.match(globalsCss, /\.team-gallery-panel/);
  assert.match(globalsCss, /\.team-card-gallery/);
  assert.match(globalsCss, /grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(190px,\s*1fr\)\)/);
  assert.match(globalsCss, /\.team-mini-player-card/);
  assert.match(globalsCss, /\.team-access-role strong/);
  assert.match(globalsCss, /white-space:\s*nowrap/);
  assert.match(globalsCss, /\.settings-panel-header/);
  assert.match(globalsCss, /\.settings-actions/);
  assert.match(globalsCss, /\.panel-cancel-button/);
  assert.match(globalsCss, /border:\s*3px solid #202820/);
  assert.match(globalsCss, /\.team-player-main/);
  assert.match(globalsCss, /\.team-player-meta/);
  assert.match(globalsCss, /\.market-scout-card/);
  assert.match(globalsCss, /\.market-scout-icon/);
  assert.match(globalsCss, /\.profile-close-button/);
  assert.match(globalsCss, /\.player-facing-main \.readonly-editor/);
  assert.match(globalsCss, /\.ranking-toolbar/);
  assert.match(globalsCss, /\.ranking-season-filter/);
  assert.match(globalsCss, /\.ranking-sort-filter/);
  assert.match(globalsCss, /\.ranking-sort-buttons/);
  assert.match(globalsCss, /\.ranking-card-grid/);
  assert.match(globalsCss, /\.ranking-player-entry/);
  assert.match(globalsCss, /main\[data-mobile-tab="equipo"\] \.ranking-player-entry/);
  assert.match(globalsCss, /\.ranking-player-card/);
  assert.match(globalsCss, /\.ranking-player-stats/);
  assert.match(globalsCss, /\.ranking-stat-grid/);
  assert.match(globalsCss, /\.ranking-card-rank/);
  assert.match(globalsCss, /\.ranking-card-badge/);
  assert.match(globalsCss, /data-profile-pane="ficha"/);
  assert.match(globalsCss, /data-profile-pane="ranking"/);
  assert.match(globalsCss, /\.team-player-grid \+ \.market-scout-card/);
  assert.match(globalsCss, /\.market-scout-card-compact/);
  assert.match(globalsCss, /\.market-admin-panel/);
  assert.match(globalsCss, /main\[data-mobile-tab="mercado"\] > \.app-shell/);
  assert.match(globalsCss, /@media \(max-width:\s*760px\)\s*\{[\s\S]*\.legal-footer\s*\{\s*display:\s*none/);
  assert.match(globalsCss, /main\[data-mobile-tab="partido"\] > \.app-shell > \.main-panel,\s*main\[data-mobile-tab="partido"\] > \.app-shell > \.lineup-panel\s*\{\s*display:\s*grid/);
  assert.match(globalsCss, /main\[data-mobile-tab="inicio"\]\s*\{[\s\S]*grid-template-columns:\s*minmax\(230px,\s*0\.72fr\) minmax\(0,\s*1\.28fr\)/);
  assert.match(globalsCss, /main\[data-mobile-tab="partido"\] > \.app-shell > \.lineup-panel/);
  assert.match(globalsCss, /main\[data-mobile-tab="partido"\] \.lineup-panel\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/);
  assert.match(globalsCss, /main\[data-mobile-tab="equipo"\] > \.bottom-grid #ranking\s*\{[\s\S]*grid-template-rows:\s*auto auto minmax\(0,\s*1fr\)/);
  assert.match(globalsCss, /main\[data-mobile-tab="perfil"\] \.player-profile\s*\{[\s\S]*grid-template-columns:\s*minmax\(116px,\s*0\.44fr\)/);
  assert.match(globalsCss, /\.market-page\s*\{[\s\S]*grid-template-rows:\s*auto auto auto minmax\(0,\s*1fr\)/);
  assert.match(globalsCss, /\.team-photo-card/);
  assert.match(globalsCss, /\.history-item\.has-photo/);
  assert.match(globalsCss, /\.google-signin-button/);
  assert.match(globalsCss, /\.brand-hero-logo/);
  assert.match(globalsCss, /transform:\s*translateX\(clamp\(-92px,\s*-12vw,\s*-42px\)\)/);
  assert.match(globalsCss, /scroll-margin-top:\s*14px/);
  assert.match(globalsCss, /overflow-y:\s*auto/);
  assert.match(globalsCss, /\.hero-action-stack/);
  assert.match(globalsCss, /\.hero-account-row/);
  assert.match(globalsCss, /\.google-signout-button/);
  assert.match(globalsCss, /\.mobile-account-group/);
  assert.match(globalsCss, /\.mobile-account-session/);
  assert.match(globalsCss, /\.mobile-account-backdrop/);
  assert.match(globalsCss, /\.mobile-account-header/);
  assert.match(globalsCss, /\.player-actions \.team-move-label/);
  assert.match(page, /Valoraciones/);
  assert.match(globalsCss, /\.status-confirm-backdrop/);
  assert.match(globalsCss, /\.status-confirm-dialog/);
  assert.match(globalsCss, /overflow-x:\s*hidden/);
  assert.match(page, /Grupo de Pachangas/);
  assert.match(page, /groupOptionLabel/);
  assert.match(page, /compactUuid/);
  assert.match(page, /expandCompactUuid/);
  assert.match(page, /remoteInviteToken/);
  assert.match(page, /showGroupAccessPanel\s*=\s*isRegisteredUser/);
  assert.match(page, /canManageTeam\s*=\s*Boolean\(hasRealTeam\s*&&\s*isRegisteredUser/);
  assert.match(page, /canUseAdminControls\s*=\s*isDemoMode\s*\|\|\s*canManageTeam/);
  assert.match(page, /showTeamAdminPanel\s*=\s*canManageTeam/);
  assert.match(page, /showMatchAdminPanel\s*=\s*canUseAdminControls/);
  assert.match(page, /showTeamAdminPanel \? \(/);
  assert.match(page, /showMatchAdminPanel \? \(/);
  assert.match(page, /canEditMatchSettings\s*=\s*canUseAdminControls\s*&&\s*!matchFinalized/);
  assert.match(page, /registrationLockedByPreviousMatch/);
  assert.match(page, /registrationOpen/);
  assert.match(page, /showMatchRoster/);
  assert.match(page, /Inscripción pendiente/);
  assert.match(page, /Se abrirá cuando pase/);
  assert.match(page, /type PlayerProfileMode = "edit" \| "viewer"/);
  assert.match(page, /const \[playerProfileMode, setPlayerProfileMode\] = useState<PlayerProfileMode>\("edit"\)/);
  assert.match(page, /function openPlayerProfile\(playerId: string\)[\s\S]*setPlayerProfileMode\("viewer"\)/);
  assert.match(page, /async function openOwnPlayerProfile\(\)[\s\S]*setPlayerProfileMode\("edit"\)/);
  assert.match(page, /showPlayerSwitcher\s*=\s*Boolean\(playerProfileMode === "edit" && canUseAdminControls\s*&&\s*selectedPlayer\s*&&\s*!selectedPlayerIsOwn/);
  assert.match(page, /player-profile-viewer/);
  assert.match(page, /player-public-stats/);
  assert.match(globalsCss, /\.player-profile-viewer/);
  assert.match(page, /<\/div>\s*\{showMarketScoutCard \? \(\s*<div className=\{\`player-card market-scout-card market-scout-card-compact/);
  assert.match(page, /statusConfirmation/);
  assert.match(page, /status-confirm-dialog/);
  assert.match(page, /skipLeaveConfirmation/);
  assert.match(page, /Mantener plaza/);
  assert.match(page, /Demo interactiva/);
  assert.match(page, /Demo local: no modifica tu grupo real/);
  assert.match(page, /profile-player-switcher/);
  assert.match(page, /function scrollToPlayerProfile/);
  assert.match(page, /function openTeamGallery/);
  assert.match(page, /function openTeamGalleryPlayerProfile/);
  assert.match(page, /function closePlayerProfile/);
  assert.match(page, /teamGalleryReturnScrollYRef/);
  assert.match(page, /teamGalleryOpen/);
  assert.match(page, /teamGalleryPlayers/);
  assert.match(page, /renderTeamMiniCard/);
  assert.match(page, /team-player-main/);
  assert.match(page, /team-player-meta/);
  assert.match(page, /renderRankingMiniCard/);
  assert.match(page, /ranking-card-grid/);
  assert.match(page, /ranking-player-entry/);
  assert.match(page, /ranking-player-card/);
  assert.match(page, /ranking-player-stats/);
  assert.match(page, /ranking-stat-grid/);
  assert.match(page, /ranking-season-filter/);
  assert.match(page, /ranking-sort-filter/);
  assert.match(page, /Mi equipo/);
  assert.match(page, /function scrollToPanel/);
  assert.match(page, /function showQuickForm/);
  assert.match(page, /function selectMatch/);
  assert.match(page, /matchPanelRef/);
  assert.match(page, /settingsPanelRef/);
  assert.match(page, /scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(page, /selectedPlayerId === playerId/);
  assert.doesNotMatch(page, /onPlayerClick=\{openPlayerProfile\}/);
  assert.match(page, /onPlayerClick=\{setPitchPreviewPlayerId\}/);
  assert.match(page, /className=\{`pitch-player-card/);
  assert.match(page, /Ver ficha de \$\{playerDisplayName\(player\)\} desde el campo/);
  assert.match(page, /SearchLogo/);
  assert.match(page, /pitchZoomOpen/);
  assert.match(page, /pitchPreviewPlayer/);
  assert.match(page, /Ver campo en grande/);
  assert.match(page, /match-pitch-zoomed/);
  assert.match(page, /type TeamBalanceSummary = ReturnType<typeof teamBalanceSummary>/);
  assert.match(page, /balanceSummary=\{balanceSummary\}/);
  assert.match(page, /className="pitch-balance-hud"/);
  assert.match(page, /aria-label=\{`Equilibrio de equipos:/);
  assert.match(page, /balanceSummary\.compactEdge \? <em>\{balanceSummary\.compactEdge\}<\/em> : null/);
  assert.match(page, /const pitchRef = useRef<HTMLDivElement \| null>\(null\)/);
  assert.match(page, /const pointerAbortRef = useRef<AbortController \| null>\(null\)/);
  assert.match(page, /type PitchPointerState/);
  assert.match(page, /function nearestPitchDropTarget/);
  assert.match(page, /function activatePitchDrag/);
  assert.match(page, /function moveWindowPitchDrag/);
  assert.match(page, /window\.addEventListener\("pointermove", moveWindowPitchDrag, \{ passive: false, signal: pointerAbortRef\.current\.signal \}\)/);
  assert.match(page, /window\.addEventListener\("pointerup", finishWindowPitchDrag, \{ passive: false, signal: pointerAbortRef\.current\.signal \}\)/);
  assert.match(page, /suppressPitchPreviewUntilRef/);
  assert.match(page, /const teamATokens = placeTeam\(teamA, kind, isLandscapePitch \? "left" : "bottom"/);
  assert.match(page, /const teamBTokens = placeTeam\(teamB, kind, isLandscapePitch \? "right" : "top"/);
  assert.match(page, /<div className=\{`pitch-label \$\{isLandscapePitch \? "left" : "bottom"\}`\}>Equipo 1<\/div>/);
  assert.match(page, /<div className=\{`pitch-label \$\{isLandscapePitch \? "right" : "top"\}`\}>Equipo 2<\/div>/);
  assert.doesNotMatch(page, /onMouseDown=\{\(event\) => \{\s*if \(event\.currentTarget === event\.target\) setPitchZoomOpen\(false\);/);
  assert.doesNotMatch(page, /onPlayerClick=\{\(playerId\) => \{[\s\S]{0,120}setPitchZoomOpen\(false\);[\s\S]{0,120}setPitchPreviewPlayerId\(playerId\);/);
  assert.match(globalsCss, /\.pitch-zoom-button/);
  assert.match(globalsCss, /\.pitch-balance-hud/);
  assert.match(globalsCss, /\.pitch-modal-fullscreen \.pitch-balance-hud/);
  assert.match(globalsCss, /\.pitch-modal-backdrop/);
  assert.match(page, /saveSelectedPlayerProfile/);
  assert.match(page, /profileSaving/);
  assert.match(page, /setProfileSaving\(true\)/);
  assert.match(page, /setProfileSaving\(false\)/);
  assert.match(page, /withTimeout\(\s*Promise\.resolve\(\s*client\.rpc\("patch_pachanga_player_profile"/);
  assert.match(page, /Guardado agotado/);
  assert.match(page, /profile-save-area/);
  assert.match(page, /Guardar ficha/);
  assert.match(page, /avatarOffsetX\?: number/);
  assert.match(page, /avatarOffsetY\?: number/);
  assert.match(page, /type AvatarDraft/);
  assert.match(page, /avatarDrafts/);
  assert.match(page, /selectedAvatarPreview/);
  assert.match(page, /canAdjustSelectedAvatar/);
  assert.match(page, /clampAvatarOffset/);
  assert.match(page, /avatarImageStyle/);
  assert.match(page, /objectFit: "cover"/);
  assert.match(page, /withTimeout\(avatarDataUrl\(file\), 8000/);
  assert.match(page, /canvas\.width = 420/);
  assert.match(page, /canvas\.height = 540/);
  assert.match(page, /toDataURL\("image\/webp", 0\.86\)/);
  assert.match(page, /toDataURL\("image\/png"\)/);
  assert.match(page, /startAvatarDrag/);
  assert.match(page, /moveAvatarDrag/);
  assert.match(page, /finishAvatarDrag/);
  assert.match(page, /El encuadre se guarda al pulsar Guardar ficha/);
  assert.match(page, /birthDate\?: string/);
  assert.match(page, /playerAge/);
  assert.match(page, /Fecha nacimiento/);
  assert.match(page, /Edad/);
  assert.match(page, /currentDateValue/);
  assert.match(page, /profile-position-row/);
  assert.ok(page.indexOf("birthdate-row") < page.indexOf("profile-position-row"));
  assert.ok(page.indexOf("profile-position-row") < page.indexOf("profile-save-area"));
  assert.match(page, /birthDate:\s*normalizeBirthDate/);
  assert.match(globalsCss, /\.birthdate-row/);
  assert.match(globalsCss, /\.age-pill/);
  assert.match(globalsCss, /\.profile-position-row/);
  assert.match(globalsCss, /--ink:\s*#202820/);
  assert.match(globalsCss, /\.profile-save-area/);
  assert.match(globalsCss, /\.profile-save-button/);
  assert.match(globalsCss, /\.pitch-player-card/);
  assert.match(globalsCss, /\.pitch-player-card:hover/);
  assert.match(globalsCss, /\.lineup-drag-enabled \.pitch-player-card/);
  assert.match(globalsCss, /\.match-pitch\.lineup-drag-enabled/);
  assert.match(globalsCss, /\.pitch-player-card\.dragging-token/);
  assert.match(globalsCss, /\.pitch-player-card\.drop-target-token/);
  assert.match(globalsCss, /\.empty-token\.drop-target-token/);
  assert.match(globalsCss, /\.pitch-player-preview-card/);
  assert.match(globalsCss, /\.match-pitch\.match-pitch-horizontal/);
  assert.match(globalsCss, /\.match-pitch-horizontal \.center-circle\s*\{[\s\S]*width:\s*15\.4%/);
  assert.match(globalsCss, /linear-gradient\(90deg,\s*rgba\(255,\s*255,\s*255,\s*0\.07\) 50%,\s*transparent 50%\) 0 0 \/ 46px 100%/);
  assert.match(globalsCss, /\.pitch-modal-fullscreen-backdrop/);
  assert.match(globalsCss, /z-index:\s*220/);
  assert.match(globalsCss, /\.pitch-modal-fullscreen \.match-pitch\.match-pitch-horizontal\.match-pitch-zoomed/);
  assert.match(globalsCss, /data-match-manager-pane="alineacion"[\s\S]*\.lineup-panel > \.team\s*\{\s*display:\s*none/);
  assert.match(globalsCss, /data-match-manager-pane="alineacion"[\s\S]*\.lineup-panel > \.match-pitch\s*\{[\s\S]*aspect-ratio:\s*1\.78/);
  assert.match(globalsCss, /\.pitch-card-photo/);
  assert.match(globalsCss, /\.empty-token/);
  assert.match(globalsCss, /aspect-ratio:\s*0\.72/);
  assert.match(globalsCss, /\.empty-token::after/);
  assert.match(globalsCss, /\.payer-badge/);
  assert.match(globalsCss, /linear-gradient\(145deg, #fde68a 0%, #f59e0b 100%\)/);
  assert.match(page, /payerId === player\.id \? "payer-card" : ""/);
  assert.match(page, /playerRatingWindow\.canRate \? "rating-open-card" : ""/);
  assert.match(page, /playerRatingWindow\.canRate \? "Valorar" : "Valoraciones"/);
  assert.match(page, /const openCardProfile = \(event: ReactMouseEvent<HTMLElement>\)/);
  assert.match(page, /event\.target\.closest\("button,a,input,select,textarea,\[role='menu'\]"\)/);
  assert.match(globalsCss, /\.player-card\.payer-card/);
  assert.match(globalsCss, /\.player-card\.rating-open-card/);
  assert.match(globalsCss, /data-match-manager-pane="proximo"[\s\S]*\.rating-badge/);
  assert.match(globalsCss, /data-match-manager-pane="proximo"[\s\S]*\.payer-badge/);
  assert.match(globalsCss, /\.draggable-avatar/);
  assert.match(globalsCss, /\.avatar-prompt-help/);
  assert.match(globalsCss, /\.avatar-prompt-info/);
  assert.match(globalsCss, /\.avatar-prompt-copy/);
  assert.match(globalsCss, /\.avatar-dragging \.draggable-avatar/);
  assert.match(globalsCss, /\.avatar-adjust-hint/);
  assert.match(globalsCss, /touch-action:\s*none/);
  assert.match(page, /function swapLineupPlayers/);
  assert.match(page, /type LineupSlotPlayerId = string \| null/);
  assert.match(page, /type LineupSlots/);
  assert.match(page, /function automaticPitchSlotPlayerIds/);
  assert.match(page, /function pitchSlotPlayerIds/);
  assert.match(page, /function trimLineupSlots/);
  assert.match(page, /targetDropId\.startsWith\("slot:"\)/);
  assert.match(page, /lineupSlots:\s*cleanLineupSlots\(match\.lineupSlots, match\.teamA \?\? \[\], match\.teamB \?\? \[\]\)/);
  assert.match(page, /function pitchOrderedPlayers/);
  assert.match(page, /function pitchOrderedPlayerIds/);
  assert.match(page, /lineupSlots:\s*\{\s*teamA:\s*nextTeamA,\s*teamB:\s*nextTeamB/);
  assert.match(page, /placeTeam\(teamA, kind, isLandscapePitch \? "left" : "bottom", scoreForPlayer, lineupSlots\?\.teamA\)/);
  assert.match(page, /const usesManualSlots = Boolean\(lineupSlotIds\?\.length\)/);
  assert.match(page, /const manual = usesManualSlots \? slots\.find\(\(slot\) => !slot\.used\) : undefined/);
  assert.match(page, /onPlayerSwap=\{swapLineupPlayers\}/);
  assert.match(page, /setPitchPreviewPlayerId/);
  assert.match(page, /data-pitch-drop-id/);
  assert.match(page, /player:\$\{player\.id\}/);
  assert.match(page, /slot:\$\{slot\.side\}:\$\{slot\.slotIndex\}/);
  assert.match(page, /data-pitch-player-id/);
  assert.match(page, /goalkeeperRatingFacets/);
  assert.match(page, /type RatingRole = "field" \| "goalkeeper"/);
  assert.match(page, /outfieldPosition/);
  assert.match(page, /rememberedOutfieldPosition/);
  assert.match(page, /ratingRoleForPlayer/);
  assert.match(page, /ratingVotesForRole/);
  assert.match(page, /position:\s*goalkeeperOnly\s*\?\s*"Portero"\s*:\s*outfieldPosition/);
  assert.match(page, /Salidas/);
  assert.match(page, /Paradas/);
  assert.match(page, /Saque/);
  assert.match(page, /Reflejos/);
  assert.match(page, /Velocidad/);
  assert.match(page, /Posición/);
  assert.match(page, /short: "SAL"/);
  assert.match(page, /short: "PAR"/);
  assert.match(page, /short: "SAQ"/);
  assert.match(page, /short: "REF"/);
  assert.match(page, /short: "VEL"/);
  assert.match(page, /short: "POS"/);
  assert.match(page, /selectedRatingFacets\.map/);
  const facetGridStart = page.indexOf('<div className="facet-grid">');
  const facetGridEnd = page.indexOf('<button type="button" onClick={() => void addPeerRating', facetGridStart);
  assert.ok(facetGridStart > -1 && facetGridEnd > facetGridStart, "rating facet editor should render before the save button");
  const facetGridMarkup = page.slice(facetGridStart, facetGridEnd);
  assert.match(page, /const ratingFacetStep = 0\.5/);
  assert.match(facetGridMarkup, /facet-stepper/);
  assert.match(facetGridMarkup, /Bajar \$\{facet\.label\}/);
  assert.match(facetGridMarkup, /Subir \$\{facet\.label\}/);
  assert.doesNotMatch(facetGridMarkup, /type="range"/);
  assert.match(globalsCss, /\.facet-stepper/);
  assert.match(globalsCss, /\.rating-box \.facet-stepper button/);
  assert.match(page, /ratingFacetsForPlayer\(player\)/);
  assert.match(page, /ratingLinePath/);
  assert.match(page, /ratingSeriesOffset/);
  assert.match(page, /facetIndex, selectedRatingFacets\.length/);
  assert.match(page, /ratingChartX/);
  assert.match(page, /ratingVoteDateLabel/);
  assert.match(page, /rating-line-chart/);
  assert.match(page, /rating-chart-legend/);
  assert.match(page, /Evolución temporal de las valoraciones por habilidad/);
  assert.match(globalsCss, /\.rating-line-chart svg/);
  assert.match(globalsCss, /\.rating-chart-tick text/);
  assert.match(globalsCss, /background:\s*#64748b/);
  assert.match(globalsCss, /font-size:\s*9px/);
  assert.match(globalsCss, /min-height:\s*16px/);
  assert.match(page, /team-hero-logo/);
  assert.match(page, /Equipo: \{currentTeamName\}/);
  assert.match(page, /Instrucciones/);
  assert.match(page, /Copias de seguridad/);
  assert.match(page, /create_pachanga_group_backup/);
  assert.match(page, /restore_pachanga_group_backup/);
  assert.match(page, /payloadRevision/);
  assert.match(page, /remotePayloadRevisionRef/);
  assert.match(page, /payloadRef/);
  assert.match(page, /lastCommittedPayloadJsonRef/);
  assert.match(page, /autosaveInFlightRef/);
  assert.match(page, /function serializePayload/);
  assert.match(page, /function serializeLocalPayloadCache/);
  assert.match(page, /function parseLocalPayloadCache/);
  assert.match(page, /kind: "pachanga-iq-cache"/);
  assert.match(page, /remoteGroupId \? "server-cache" : "local-draft"/);
  assert.match(page, /payloadJson === lastCommittedPayloadJsonRef\.current/);
  assert.match(page, /autosaveInFlightRef\.current = true/);
  assert.match(page, /autosaveInFlightRef\.current = false/);
  assert.match(page, /save_pachanga_payload_if_current/);
  assert.match(page, /upsert_pachanga_own_player_profile/);
  assert.match(page, /function profilePatchFor/);
  assert.match(page, /function ownPlayerFromCommit/);
  assert.match(page, /Creando ficha/);
  assert.match(page, /Crear ficha con test/);
  assert.match(page, /complete_pachanga_player_initial_assessment/);
  assert.match(page, /complete_pachanga_player_advanced_assessment/);
  assert.match(page, /patch_pachanga_match_player_status/);
  assert.match(page, /patch_pachanga_match_player_paid/);
  assert.match(page, /patch_pachanga_match_scorers/);
  assert.match(page, /patch_pachanga_match_lineup_state/);
  assert.match(page, /operation_key: id\(\)/);
  assert.match(page, /set_pachanga_member_role/);
  assert.match(page, /patch_pachanga_player_profile/);
  assert.match(page, /append_pachanga_player_rating/);
  assert.match(page, /partido_guardado/);
  assert.match(page, /partido_finalizado/);
  assert.match(page, /equipo_borrado/);
  assert.match(page, /\.limit\(3\)/);
  assert.match(page, /solo las 3 últimas por grupo/);
  assert.doesNotMatch(page, /Añade asistentes para calcularlo/);
  assert.match(globalsCss, /\.backup-panel/);
  assert.match(globalsCss, /\.backup-list article/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_group_backups/);
  assert.match(supabaseSql, /backup_rank > 3/);
  assert.match(supabaseSql, /create or replace function public\.restore_pachanga_group_backup/);
  assert.match(supabaseSql, /payload_revision bigint not null default 0/);
  assert.match(supabaseSql, /create or replace function public\.is_registered_pachanga_user/);
  assert.match(supabaseSql, /create or replace function public\.save_pachanga_payload_if_current/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_player_status/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_player_paid/);
  assert.match(supabaseSql, /Close the lineup before changing payments/);
  assert.match(supabaseSql, /selected_match \? 'scoreA'/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_scorers/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_player_profiles/);
  assert.match(supabaseSql, /assessment_summary jsonb not null default '\{\}'::jsonb/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_player_assessments/);
  assert.match(supabaseSql, /unique index if not exists pachanga_player_assessments_user_kind_idx/);
  assert.match(supabaseSql, /create or replace function public\.complete_pachanga_player_initial_assessment/);
  assert.match(supabaseSql, /create or replace function public\.complete_pachanga_player_advanced_assessment/);
  assert.match(supabaseSql, /Complete the initial player assessment before creating a new profile/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_player_assessments/);
  assert.match(supabaseSql, /pachanga_player_assessments_user_kind_idx/);
  assert.match(supabaseSql, /Initial player assessment already completed/);
  assert.match(supabaseSql, /Complete the initial player assessment before creating a new profile/);
  assert.match(supabaseSql, /create unique index if not exists pachanga_player_profiles_user_id_idx/);
  assert.match(supabaseSql, /Users can read own universal player profile/);
  assert.match(supabaseSql, /player_profile_id uuid references public\.pachanga_player_profiles/);
  assert.match(supabaseSql, /create or replace function public\.upsert_pachanga_player_profile_from_player/);
  assert.match(supabaseSql, /create or replace function public\.sync_pachanga_player_profile_to_groups/);
  assert.match(supabaseSql, /revoke execute on function public\.sync_pachanga_player_profile_to_groups\(uuid, uuid\) from authenticated/);
  assert.match(supabaseSql, /globalPlayerProfileId/);
  assert.match(page, /globalPlayerProfileId/);
  assert.match(page, /Tu ficha universal/);
  assert.match(supabaseSql, /create or replace function public\.upsert_pachanga_own_player_profile/);
  assert.match(supabaseSql, /create or replace function public\.complete_pachanga_player_initial_assessment/);
  assert.match(supabaseSql, /create or replace function public\.complete_pachanga_player_advanced_assessment/);
  assert.match(supabaseSql, /Only group members can create a player profile/);
  assert.match(supabaseSql, /This player profile already belongs to another user/);
  assert.match(supabaseSql, /grant execute on function public\.upsert_pachanga_own_player_profile/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_player_profile/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_market_profiles/);
  assert.match(supabaseSql, /create or replace function public\.sync_pachanga_market_profile/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_open_matches/);
  assert.match(supabaseSql, /create or replace function public\.sync_pachanga_open_match/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_open_match_requests/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_match_read_model/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_match_participants/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_match_scorers/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_operation_receipts/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_group_events/);
  assert.match(supabaseSql, /pachanga_admin_invites_created_by_idx/);
  assert.match(supabaseSql, /pachanga_admin_invites_accepted_by_idx/);
  assert.match(supabaseSql, /pachanga_open_matches_created_by_idx/);
  assert.match(supabaseSql, /pachanga_group_events_actor_id_idx/);
  assert.match(supabaseSql, /unique\(group_id, operation_id\)/);
  assert.match(supabaseSql, /create or replace function public\.remember_pachanga_operation/);
  assert.match(supabaseSql, /create or replace function public\.record_pachanga_group_event/);
  assert.match(supabaseSql, /create or replace function public\.sync_pachanga_group_read_model/);
  assert.match(supabaseSql, /revoke execute on function public\.remember_pachanga_operation\(uuid, uuid, text, jsonb\) from authenticated/);
  assert.match(supabaseSql, /perform public\.sync_pachanga_group_read_model\(\s*group_record\.id,/);
  assert.match(supabaseSql, /create or replace function public\.request_pachanga_open_match/);
  assert.match(supabaseSql, /create or replace function public\.review_pachanga_open_match_request/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_lineup_state/);
  assert.match(supabaseSql, /operation_key uuid default null/);
  assert.match(supabaseSql, /Open the lineup before changing attendance/);
  assert.match(supabaseSql, /Match already finalized/);
  assert.match(supabaseSql, /Payer must belong to the closed lineup/);
  assert.match(supabaseSql, /La solicitud ya estaba decidida/);
  assert.match(supabaseSql, /requests\.status in \('accepted', 'pending'\) then requests\.requested_at/);
  assert.match(supabaseSql, /create or replace function public\.set_pachanga_member_role/);
  assert.match(supabaseSql, /Authenticated users can read active open matches/);
  assert.match(supabaseSql, /Users and admins can read open match requests/);
  assert.match(supabaseSql, /Members can read normalized matches/);
  assert.match(supabaseSql, /alter publication supabase_realtime add table public\.pachanga_group_events/);
  assert.match(supabaseSql, /grant execute on function public\.sync_pachanga_open_match\(uuid, text, jsonb, uuid\)/);
  assert.match(supabaseSql, /grant execute on function public\.request_pachanga_open_match/);
  assert.match(supabaseSql, /grant execute on function public\.review_pachanga_open_match_request/);
  assert.match(supabaseSql, /marketEnabled/);
  assert.match(supabaseSql, /marketModalities/);
  assert.match(supabaseSql, /zones_geo jsonb not null default '\[\]'::jsonb/);
  assert.match(supabaseSql, /pachanga_market_profiles_zones_geo_idx/);
  assert.match(supabaseSql, /marketZonesGeo/);
  assert.match(supabaseSql, /grant execute on function public\.sync_pachanga_market_profile/);
  assert.match(supabaseSql, /Authenticated users can read active market profiles/);
  assert.match(supabaseSql, /pachanga_market_profiles_zones_idx/);
  assert.match(supabaseSql, /create or replace function public\.append_pachanga_player_rating/);
  assert.match(supabaseSql, /birthDate/);
  assert.match(supabaseSql, /avatarOffsetX/);
  assert.match(supabaseSql, /avatarOffsetY/);
  assert.match(supabaseSql, /outfieldPosition/);
  assert.match(supabaseSql, /ratingRole/);
  assert.match(supabaseSql, /then 'goalkeeper'/);
  assert.match(supabaseSql, /Rating window closed for this player/);
  assert.match(supabaseSql, /last_vote_match_count \+ 3/);
  assert.match(supabaseSql, /player_appearances = 0 then 0 else 3/);
  assert.match(page, /isInitialWindow/);
  assert.match(page, /Valoración inicial abierta/);
  assert.match(supabaseSql, /current_group\.payload_revision <> expected_revision/);
  assert.match(supabaseSql, /current_group\.payload = next_payload/);
  assert.match(supabaseSql, /policy "Admins can update groups"/);
  assert.match(supabaseSql, /public\.is_registered_pachanga_user\(\)/);
  assert.doesNotMatch(supabaseSql, /policy "Members can update groups"/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, title:/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, brand:/);
  assert.match(page, /settingsDraft/);
  assert.match(page, /function saveSettingsPanel/);
  assert.match(page, /siteSettings: nextSettings/);
  assert.match(page, /await saveRemotePayload\(nextPayload\)/);
  assert.doesNotMatch(page, /if \(canUseAdminControls\) setSiteSettings\(settingsDraft\)/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, subtitle:/);
  assert.match(page, /update_pachanga_member_name/);
  assert.match(page, /if \(selectedPlayerIsOwn\) setProfileName\(normalizedName\)/);
  assert.doesNotMatch(page, /Guardar nombre/);
  assert.doesNotMatch(page, /Nombre en el equipo/);
  assert.doesNotMatch(page, /account-panel/);
  assert.doesNotMatch(page, /profile-name-field/);
  assert.doesNotMatch(globalsCss, /\.auth-panel/);
  assert.doesNotMatch(globalsCss, /\.profile-name-field/);
  assert.doesNotMatch(page, /onBlur=\{\(\) => setProfileName\(displayName\(profileName \|\| authDisplayName\(authUser\)\)\)\}/);
  assert.doesNotMatch(page, /const nextName = displayName\(profileName \|\| authDisplayName\(authUser\)\)/);
  assert.match(page, /Partido finalizado/);
  assert.doesNotMatch(page, /Modo local/);
  assert.match(page, /paymentReady/);
  assert.match(page, /const canConfigureMatchMarket = canUseAdminControls && showMatchRoster && !lineupClosed && !matchFinalized/);
  assert.match(page, /const showMarketScoutCard = canConfigureMatchMarket && \(missing > 0 \|\| Boolean\(activeMatch\.publicOpen\)\)/);
  assert.match(page, /const otherPlayers = registrationOpen/);
  assert.match(page, /const canChangeStatus = matchConfigured && registrationOpen/);
  assert.match(page, /const canChangeThisPlayerStatus = matchConfigured && registrationOpen/);
  assert.match(page, /Buscar en mercado/);
  assert.match(page, /Configurar mercado/);
  assert.match(page, /Solo admins y owner ven esta pantalla/);
  assert.match(page, /Abrir partido al público/);
  assert.match(page, /publicOpen/);
  assert.match(page, /publicMatchUrl/);
  assert.match(page, /sync_pachanga_open_match/);
  assert.match(page, /loadOpenMatchRequests/);
  assert.match(page, /reviewOpenMatchRequest/);
  assert.match(page, /target_request_id/);
  assert.match(page, /Solicitudes del mercado/);
  assert.match(page, /Aceptar/);
  assert.match(page, /Rechazar/);
  assert.match(page, /Nivel del equipo/);
  assert.match(page, /teamLevelScore/);
  assert.match(page, /Pago por persona/);
  assert.match(page, /type MatchWeather/);
  assert.match(page, /conditionType: string/);
  assert.match(page, /matchWeatherStatus/);
  assert.match(page, /\/api\/weather/);
  assert.match(page, /Tiempo previsto/);
  assert.match(page, /function WeatherIcon/);
  assert.match(page, /function WeatherMetricIcon/);
  assert.match(page, /weatherVisualKey/);
  assert.match(page, /weather-availability-message/);
  assert.match(page, /weatherForecastClientLimitMs = 7 \* weatherClientDayMs/);
  assert.match(page, /weatherClientShortCacheMs = 2 \* weatherClientHourMs/);
  assert.match(page, /weatherClientLongCacheMs = weatherClientDayMs/);
  assert.match(page, /matchWeatherClientCache/);
  assert.match(page, /msUntilMatch > weatherForecastClientLimitMs/);
  assert.match(weatherRoute, /Previsión del tiempo disponible en/);
  assert.match(page, /Previsión más cercana/);
  assert.match(page, /Elige un campo con ubicación para ver la previsión/);
  assert.doesNotMatch(page, /Google Places para ver la previsión/);
  assert.doesNotMatch(page, /<span>Toca<\/span>/);
  assert.match(page, /Cierra la alineación para calcular pago y finalizar/);
  assert.match(page, /disabled=\{!matchConfigured \|\| !lineupClosed \|\| !resultIsReady \|\| !canUseAdminControls\}/);
  assert.match(page, /const matchTimeOptions = Array\.from\(\{ length: 144 \}/);
  assert.match(page, /type="date"/);
  assert.match(page, /className="match-time-control"[\s\S]*?Hora[\s\S]*?<select/);
  assert.match(page, /className="match-field-control"/);
  assert.match(page, /className="match-price-control"/);
  assert.doesNotMatch(page, /type="datetime-local"/);
  assert.match(page, /const allPositionOptions = Array\.from/);
  assert.match(page, /value=\{selectablePositionValue\(selectedPlayer\.position\)\}/);
  assert.match(page, /\{allPositionOptions\.map\(\(option\) =>/);
  assert.match(page, /freeTrialMatchLimit\s*=\s*2/);
  assert.match(page, /groupBillingLocked/);
  assert.match(page, /startBillingCheckout/);
  assert.match(page, /openBillingPortal/);
  assert.match(page, /Suscripción del grupo/);
  assert.match(page, /Prueba terminada/);
  assert.match(page, /Mensual 5,99 €\/mes/);
  assert.match(page, /Anual 64,99 €\/año/);
  assert.match(page, /Aporte app por Bizum/);
  assert.match(page, /Esta cuota no se suma al campo/);
  assert.match(page, /subscriptionContributionPerPlayer/);
  assert.match(layout, /title:\s*"Pachangas IQ"/);
  assert.match(layout, /LegalFooter/);
  assert.match(legalData, /Aviso legal/);
  assert.match(legalData, /Política de privacidad/);
  assert.match(legalData, /Política de cookies/);
  assert.match(legalData, /Condiciones de contratación/);
  assert.match(legalData, /Datos legales del responsable pendientes de completar/);
  assert.match(globalsCss, /\.legal-footer/);
  assert.match(globalsCss, /\.legal-page-panel/);
  assert.match(layout, /appleWebApp/);
  assert.match(layout, /viewportFit:\s*"cover"/);
  assert.match(layout, /PwaRuntime/);
  assert.match(manifest, /display:\s*"standalone"/);
  assert.match(manifest, /display_override:\s*\["standalone", "minimal-ui", "browser"\]/);
  assert.match(manifest, /orientation:\s*"any"/);
  assert.match(manifest, /launch_handler/);
  assert.match(manifest, /client_mode:\s*"focus-existing"/);
  assert.match(manifest, /prefer_related_applications:\s*false/);
  assert.match(manifest, /purpose:\s*"maskable"/);
  assert.match(manifest, /\/icon-monochrome\.svg/);
  assert.match(manifest, /purpose:\s*"monochrome"/);
  assert.match(manifest, /shortcuts/);
  assert.match(manifest, /\/\?mobile=partido/);
  assert.match(manifest, /\/mercado/);
  assert.match(manifest, /\/\?mobile=equipo/);
  assert.match(manifest, /Abrir el ranking del equipo/);
  assert.match(pwaRuntime, /serviceWorker\.register\("\/sw\.js", \{ scope: "\/" \}\)/);
  assert.match(pwaRuntime, /dataDisplayMode|dataset\.displayMode/);
  assert.match(pwaRuntime, /visualViewport/);
  assert.match(pwaRuntime, /--app-viewport-height/);
  assert.match(pwaRuntime, /--app-viewport-width/);
  assert.match(pwaRuntime, /adaptiveWindowClass\(width, height\)/);
  assert.match(pwaRuntime, /dataset\.windowWidthClass/);
  assert.match(pwaRuntime, /dataset\.windowHeightClass/);
  assert.match(adaptiveWindow, /width >= 1600/);
  assert.match(adaptiveWindow, /width >= 1200/);
  assert.match(adaptiveWindow, /width >= 840/);
  assert.match(adaptiveWindow, /width >= 600/);
  assert.match(adaptiveWindow, /height >= 900/);
  assert.match(adaptiveWindow, /height >= 480/);
  assert.match(pwaRuntime, /supportsShare/);
  assert.match(pwaRuntime, /supportsClipboard/);
  assert.match(pwaRuntime, /supportsCamera/);
  assert.match(pwaRuntime, /supportsStorageEstimate/);
  assert.match(pwaRuntime, /storagePressure/);
  assert.match(serviceWorker, /CACHE_NAME = "pachangas-iq-pwa-v3"/);
  assert.match(serviceWorker, /CACHEABLE_NAVIGATION_PATHS/);
  assert.match(serviceWorker, /!url\.search/);
  assert.match(serviceWorker, /MAX_RUNTIME_CACHE_ENTRIES = 120/);
  assert.match(serviceWorker, /function trimRuntimeCache/);
  assert.match(serviceWorker, /navigationPreload\?\.enable\?\.\(\)/);
  assert.match(serviceWorker, /\/icon-monochrome\.svg/);
  assert.match(serviceWorker, /\/brand\/pachangas-logo-hero\.png/);
  assert.match(serviceWorker, /LIVE_SERVICE_HOST_PARTS/);
  assert.match(serviceWorker, /supabase\.co/);
  assert.match(serviceWorker, /stripe\.com/);
  assert.match(serviceWorker, /request\.mode === "navigate"/);
  assert.match(serviceWorker, /pathname\.startsWith\("\/api\/"\)/);
  assert.match(serviceWorker, /pathname\.startsWith\("\/auth\/"\)/);
  assert.match(nextConfig, /source: "\/sw\.js"/);
  assert.match(nextConfig, /Service-Worker-Allowed/);
  assert.match(nextConfig, /no-cache, no-store, must-revalidate/);
  assert.match(nextConfig, /\/icon-monochrome\.svg/);
  assert.match(globalsCss, /--app-viewport-width:\s*100vw/);
  assert.match(globalsCss, /--game-nav-offset:\s*calc\(var\(--game-nav-height\) \+ var\(--safe-top\)\)/);
  assert.match(globalsCss, /@supports not \(height: 100dvh\)/);
  assert.match(globalsCss, /@supports \(overflow: clip\)/);
  assert.match(globalsCss, /@media \(min-width: 600px\) and \(max-width: 1180px\) and \(pointer: coarse\)/);
  assert.match(globalsCss, /data-window-width-class/);
  assert.match(globalsCss, /data-window-height-class/);
  assert.match(globalsCss, /padding-top:\s*var\(--game-nav-offset\)/);
  assert.match(globalsCss, /height:\s*calc\(var\(--app-viewport-height\) - var\(--game-nav-offset\)\)/);
  assert.match(adaptiveDocs, /Pachangas QA Matrix/);
  assert.match(adaptiveDocs, /COMPAT_BASE_URL/);
  assert.match(page, /function copyTextWithFallback/);
  assert.match(page, /window\.prompt\(fallbackTitle, text\)/);
  assert.match(page, /Copia el enlace del partido/);
  assert.match(marketPage, /navigator\.clipboard\?\.writeText/);
  assert.match(packageJson, /"@supabase\/supabase-js"/);
  assert.match(packageJson, /"stripe"/);
  assert.match(supabaseClient, /NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY/);
  assert.match(billingShared, /FREE_TRIAL_MATCH_LIMIT = 2/);
  assert.match(billingShared, /priceIdForInterval/);
  assert.match(billingShared, /STRIPE_MONTHLY_PRODUCT_ID/);
  assert.match(billingShared, /STRIPE_YEARLY_PRODUCT_ID/);
  assert.match(billingShared, /billingGroupIsActive/);
  assert.match(billingCheckout, /checkout\.sessions\.create/);
  assert.match(billingCheckout, /mode:\s*"subscription"/);
  assert.match(billingCheckout, /allow_promotion_codes:\s*true/);
  assert.match(billingCheckout, /billingGroupIsActive\(group\)/);
  assert.match(billingCheckout, /billingPortal\.sessions\.create/);
  assert.match(billingPortal, /billingPortal\.sessions\.create/);
  assert.match(stripeWebhook, /constructEvent\(await request\.text\(\)/);
  assert.match(stripeWebhook, /checkout\.session\.completed/);
  assert.match(stripeWebhook, /customer\.subscription\.updated/);
  assert.match(stripeWebhook, /invoice\.payment_failed/);
  assert.match(stripeWebhook, /pachanga_stripe_webhook_events/);
  assert.match(stripeWebhook, /event_id: event\.id/);
  assert.match(stripeWebhook, /duplicate: true/);
  assert.match(stripeWebhook, /processing_status: "processed"/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_stripe_webhook_events/);
  assert.match(supabaseSql, /pachanga_stripe_webhook_events_status_check/);
  assert.match(supabaseSql, /billing_trial_finalized_matches/);
  assert.match(supabaseSql, /create or replace function public\.finalize_pachanga_match_if_current/);
  assert.match(supabaseSql, /Trial limit reached\. Subscription required\./);
  assert.match(supabaseSql, /Finalize matches with finalize_pachanga_match_if_current/);
  assert.match(envExample, /STRIPE_MONTHLY_PRODUCT_ID=prod_UyN3AQOFvB9Bdb/);
  assert.match(envExample, /STRIPE_YEARLY_PRODUCT_ID=prod_UyN51e1Sg6RwH1/);
  assert.match(envExample, /NEXT_PUBLIC_GOOGLE_MAPS_API_KEY/);
  assert.match(envExample, /GOOGLE_WEATHER_API_KEY/);
  assert.match(globalsCss, /\.weather-card/);
  assert.match(globalsCss, /\.weather-icon-rain/);
  assert.match(globalsCss, /\.weather-metric-icon/);
  assert.match(globalsCss, /\.weather-metrics/);
  assert.match(weatherRoute, /weather\.googleapis\.com\/v1\/forecast\/hours:lookup/);
  assert.match(weatherRoute, /GOOGLE_WEATHER_API_KEY/);
  assert.match(weatherRoute, /forecastHours/);
  assert.match(weatherRoute, /conditionType: closest\.weatherCondition\?\.type/);
  assert.match(weatherRoute, /location\.latitude/);
  assert.match(weatherRoute, /location\.longitude/);
  assert.match(weatherRoute, /weatherForecastLimitHours\s*=\s*7 \* 24/);
  assert.match(weatherRoute, /weatherShortCacheSeconds\s*=\s*2 \* 60 \* 60/);
  assert.match(weatherRoute, /weatherLongCacheSeconds\s*=\s*24 \* 60 \* 60/);
  assert.match(weatherRoute, /next: \{ revalidate: revalidateSeconds \}/);
  assert.match(weatherRoute, /publicCache\(cacheSeconds\)/);
  assert.match(weatherRoute, /languageCode", "es"/);
  assert.doesNotMatch(page, /SkeletonPreview/);
  assert.doesNotMatch(layout, /Starter Project|codex-preview/);
});
