import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds Pachangas IQ HTML", async () => {
  const html = await readFile(new URL("../.next/server/app/index.html", import.meta.url), "utf8");
  assert.match(html, /<html lang="es">/i);
  assert.match(html, /<title>Pachangas IQ<\/title>/i);
  assert.match(html, /El grupo del partido, pero con memoria\./);
  assert.match(html, /Confirmados/);
  assert.match(html, /Equipos sugeridos/i);
  assert.match(html, /Alineación abierta/);
  assert.match(html, /Continuar con Google/);
  assert.match(html, /Finalizar partido/);
  assert.match(html, /Añadir foto del partido/);
  assert.match(html, /Comparte este partido!/);
  assert.match(html, /Copiar link/);
  assert.match(html, /Próximos partidos/);
  assert.match(html, /Temporada/);
  assert.match(html, /Ordenar por/);
  assert.match(html, /2025-2026/);
  assert.match(html, /Navegación principal móvil/);
  assert.match(html, /Abrir manual de usuario/);
  assert.match(html, /\/brand\/pachangas-logo-hero\.png/);
  assert.match(html, /\/manifest\.webmanifest/);
  assert.match(html, /\/apple-touch-icon\.png/);
  assert.match(html, /\/icon-192\.png/);
  assert.doesNotMatch(html, /Manual de usuario<\/span>/);
  assert.doesNotMatch(html, /Registro/);
  assert.doesNotMatch(html, /Entra para crear tu equipo/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site|react-loading-skeleton/i);
});

test("builds the user manual as its own page", async () => {
  const html = await readFile(new URL("../.next/server/app/manual.html", import.meta.url), "utf8");
  assert.match(html, /Manual de usuario/);
  assert.match(html, /Primera entrada/);
  assert.match(html, /Crear partido/);
  assert.match(html, /Guardar partido/);
  assert.match(html, /fecha, modalidad/);
  assert.match(html, /se calcula desde la fecha y se guarda en la ficha del partido/);
  assert.match(html, /empieza en septiembre y termina en agosto/);
  assert.match(html, /Jugador y admin/);
  assert.match(html, /Si cambias de Voy a Duda o No/);
  assert.match(html, /Cualquier miembro puede subir una foto del partido/);
  assert.match(html, /foto en miniatura/);
  assert.match(html, /copias automáticas al guardar o finalizar un partido/);
  assert.match(html, /Borrar jugador lo deja fuera del grupo/);
  assert.match(html, /Ranking vivo/);
  assert.match(html, /Media, forma y equilibrio/);
  assert.match(html, /Media real = promedio/);
  assert.match(html, /Forma actual = porcentaje temporal/);
  assert.match(html, /Valor para equilibrar = media real multiplicada por forma actual/);
  assert.match(html, /Fiabilidad = 100% menos 7 puntos/);
  assert.match(html, /Volver/);
});

test("keeps the project wired to the Pachangas app", async () => {
  const [page, layout, packageJson, supabaseClient, globalsCss, googleAuthPage, supabaseSql] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/supabaseClient.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/auth/google/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../supabase/pachangas.sql", import.meta.url), "utf8"),
  ]);

  assert.match(page, /join_pachanga_team/);
  assert.match(page, /MemberRole/);
  assert.match(page, /incomingSharedLinkFromSearch/);
  assert.match(page, /needsLoginForSharedLink/);
  assert.match(page, /Continuar con Google y volver/);
  assert.match(page, /GoogleLogo/);
  assert.match(page, /google-signin-button/);
  assert.match(page, /Crea tu ficha para poder marcar/);
  assert.match(page, /gated-shell/);
  assert.doesNotMatch(page, /match-focus-card/);
  assert.doesNotMatch(page, /Resumen del partido/);
  assert.match(page, /create-menu/);
  assert.match(page, /create-menu-panel/);
  assert.match(page, /aria-haspopup="menu"/);
  assert.match(page, /Ficha jugador/);
  assert.match(page, /showQuickForm\("venue"\)/);
  assert.match(page, /showQuickForm\("team"\)/);
  assert.match(page, /runCreateAction\(createMatch\)/);
  assert.doesNotMatch(page, /top-panel quick-create-form top-player-form/);
  assert.doesNotMatch(page, /Nombre del jugador/);
  assert.doesNotMatch(page, /Guardar jugador/);
  assert.match(page, /top-panel quick-create-form top-venue-form/);
  assert.match(page, /Crea tu primer partido desde “Crear”/);
  assert.match(globalsCss, /\.quick-create-form/);
  assert.ok(page.indexOf("top-panel quick-create-form top-venue-form") < page.indexOf("team-access-panel"));
  assert.match(globalsCss, /\.create-menu-panel/);
  assert.doesNotMatch(globalsCss, /\.top-player-form/);
  assert.match(page, /mobile-tabbar/);
  assert.match(page, /id="partido"/);
  assert.match(page, /id="equipos"/);
  assert.match(page, /id="ranking"/);
  assert.match(page, /RankingSort/);
  assert.match(page, /rankingSeason/);
  assert.match(page, /historySeason/);
  assert.match(page, /filteredClosedMatches/);
  assert.match(page, /result-score-field team-a-score/);
  assert.match(page, /Resultado equipo 1/);
  assert.match(page, /consecutiveAbsenceStreak/);
  assert.match(page, /absenceStreaks/);
  assert.match(page, /showAbsenceStreak/);
  assert.match(page, /sin venir/);
  assert.match(page, /PlayerFormState/);
  assert.match(page, /playerFormState/);
  assert.match(page, /playerFormStates/);
  assert.match(page, /matchFormRatingForPlayer/);
  assert.match(page, /playerReliability/);
  assert.match(page, /Forma actual/);
  assert.match(page, /Valor para equilibrar/);
  assert.match(page, /media real, forma actual/);
  assert.match(page, /matchImpactForPlayer/);
  assert.match(page, /teamHasFixedKeeper/);
  assert.match(page, /portería a cero/);
  assert.match(page, /playerBalancePower/);
  assert.match(page, /playerGoalsPerMatch/);
  assert.match(page, /playerWinRate/);
  assert.match(page, /teamBalanceSummary/);
  assert.match(page, /Equilibrio de equipos/);
  assert.match(page, /goles\/partido/);
  assert.match(page, /footballSeasonStartMonth/);
  assert.match(page, /parsed\.getMonth\(\) >= footballSeasonStartMonth/);
  assert.match(page, /rankingSortLabels/);
  assert.match(page, /seasonKey/);
  assert.match(page, /matchSeason/);
  assert.match(page, /season: seasonKey/);
  assert.match(page, /season: seasonKey\(activeMatch\.date\)/);
  assert.doesNotMatch(page, /updateMatchSettings\(\{ \.\.\.activeMatch, season: event\.target\.value \}\)/);
  assert.match(page, /rankingBadgeText/);
  assert.match(page, /teamPhoto\?: string/);
  assert.match(page, /matchPhotoDataUrl/);
  assert.match(page, /canUploadTeamPhoto/);
  assert.match(page, /Añadir foto del partido/);
  assert.match(page, /Quitar foto/);
  assert.match(page, /history-photo/);
  assert.match(page, /history-season-filter/);
  assert.match(page, /No hay partidos en esta temporada/);
  assert.match(googleAuthPage, /safeReturnUrl/);
  assert.match(googleAuthPage, /url\.origin !== window\.location\.origin/);
  assert.match(page, /sha256Hex\(rawNonce\)/);
  assert.match(page, /authUrl\.searchParams\.set\("nonce", hashedNonce\)/);
  assert.match(page, /className="history-month"/);
  assert.match(page, /joinedAtLabel/);
  assert.match(page, /Voy desde/);
  assert.match(page, /perderás tu posición/);
  assert.match(globalsCss, /\.side-history \.history/);
  assert.match(globalsCss, /\.side-history::after/);
  assert.match(globalsCss, /\.history-season-filter/);
  assert.match(globalsCss, /\.result-score-field span/);
  assert.match(globalsCss, /\.team-b-score/);
  assert.match(globalsCss, /\.absence-chip/);
  assert.match(globalsCss, /\.form-chip/);
  assert.match(globalsCss, /\.form-state-card/);
  assert.match(globalsCss, /\.balance-summary/);
  assert.match(globalsCss, /scrollbar-color:\s*#64748b #ebe7dc/);
  assert.match(globalsCss, /\.side-history \.history::\-webkit-scrollbar-thumb/);
  assert.match(globalsCss, /\.joined-at/);
  assert.match(globalsCss, /\.shared-link-gate/);
  assert.match(globalsCss, /\.gated-shell/);
  assert.doesNotMatch(globalsCss, /\.match-focus-card/);
  assert.match(globalsCss, /\.mobile-tabbar/);
  assert.match(globalsCss, /\.player-facing-main \.readonly-editor/);
  assert.match(globalsCss, /\.ranking-toolbar/);
  assert.match(globalsCss, /\.ranking-sort-buttons/);
  assert.match(globalsCss, /\.team-photo-card/);
  assert.match(globalsCss, /\.history-item\.has-photo/);
  assert.match(globalsCss, /\.google-signin-button/);
  assert.match(globalsCss, /\.brand-hero-logo/);
  assert.match(globalsCss, /scroll-margin-top:\s*14px/);
  assert.match(globalsCss, /overflow-y:\s*auto/);
  assert.match(globalsCss, /\.hero-actions\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(globalsCss, /overflow-x:\s*hidden/);
  assert.match(page, /Equipo pachanguero/);
  assert.match(page, /equipo/);
  assert.match(page, /compactUuid/);
  assert.match(page, /expandCompactUuid/);
  assert.match(page, /remoteInviteToken/);
  assert.match(page, /canEditMatchSettings\s*=\s*canUseAdminControls\s*&&\s*!matchFinalized/);
  assert.match(page, /showPlayerSwitcher\s*=\s*Boolean\(canUseAdminControls\s*&&\s*selectedPlayer\s*&&\s*!selectedPlayerIsOwn/);
  assert.match(page, /profile-player-switcher/);
  assert.match(page, /function scrollToPlayerProfile/);
  assert.match(page, /function scrollToPanel/);
  assert.match(page, /function showQuickForm/);
  assert.match(page, /function selectMatch/);
  assert.match(page, /matchPanelRef/);
  assert.match(page, /settingsPanelRef/);
  assert.match(page, /scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(page, /selectedPlayerId === playerId/);
  assert.match(page, /saveSelectedPlayerProfile/);
  assert.match(page, /profile-save-area/);
  assert.match(page, /Guardar ficha/);
  assert.match(page, /birthDate\?: string/);
  assert.match(page, /playerAge/);
  assert.match(page, /Fecha nacimiento/);
  assert.match(page, /Edad/);
  assert.match(page, /currentDateValue/);
  assert.match(page, /birthDate:\s*normalizeBirthDate/);
  assert.match(globalsCss, /\.birthdate-row/);
  assert.match(globalsCss, /\.age-pill/);
  assert.match(globalsCss, /--ink:\s*#202820/);
  assert.match(globalsCss, /\.profile-save-area/);
  assert.match(globalsCss, /\.profile-save-button/);
  assert.match(page, /goalkeeperRatingFacets/);
  assert.match(page, /type RatingRole = "field" \| "goalkeeper"/);
  assert.match(page, /outfieldPosition/);
  assert.match(page, /rememberedOutfieldPosition/);
  assert.match(page, /ratingRoleForPlayer/);
  assert.match(page, /ratingVotesForRole/);
  assert.match(page, /position:\s*goalkeeperOnly\s*\?\s*"Portero"\s*:\s*outfieldPosition/);
  assert.match(page, /Salidas/);
  assert.match(page, /Paradas/);
  assert.match(page, /Saque/);
  assert.match(page, /Reflejos/);
  assert.match(page, /Velocidad/);
  assert.match(page, /Posición/);
  assert.match(page, /short: "SAL"/);
  assert.match(page, /short: "PAR"/);
  assert.match(page, /short: "SAQ"/);
  assert.match(page, /short: "REF"/);
  assert.match(page, /short: "VEL"/);
  assert.match(page, /short: "POS"/);
  assert.match(page, /selectedRatingFacets\.map/);
  assert.match(page, /ratingFacetsForPlayer\(player\)/);
  assert.match(page, /ratingLinePath/);
  assert.match(page, /ratingSeriesOffset/);
  assert.match(page, /facetIndex, selectedRatingFacets\.length/);
  assert.match(page, /ratingChartX/);
  assert.match(page, /ratingVoteDateLabel/);
  assert.match(page, /rating-line-chart/);
  assert.match(page, /rating-chart-legend/);
  assert.match(page, /Evolución temporal de las valoraciones por habilidad/);
  assert.match(globalsCss, /\.rating-line-chart svg/);
  assert.match(globalsCss, /\.rating-chart-tick text/);
  assert.match(globalsCss, /background:\s*#64748b/);
  assert.match(globalsCss, /font-size:\s*9px/);
  assert.match(globalsCss, /min-height:\s*16px/);
  assert.match(page, /team-hero-logo/);
  assert.match(page, /Equipo: \{currentTeamName\}/);
  assert.match(page, /Instrucciones/);
  assert.match(page, /Copias de seguridad/);
  assert.match(page, /create_pachanga_group_backup/);
  assert.match(page, /restore_pachanga_group_backup/);
  assert.match(page, /payloadRevision/);
  assert.match(page, /remotePayloadRevisionRef/);
  assert.match(page, /payloadRef/);
  assert.match(page, /save_pachanga_payload_if_current/);
  assert.match(page, /upsert_pachanga_own_player_profile/);
  assert.match(page, /function profilePatchFor/);
  assert.match(page, /function ownPlayerFromCommit/);
  assert.match(page, /Creando ficha/);
  assert.match(page, /Asignando ficha/);
  assert.match(page, /patch_pachanga_match_player_status/);
  assert.match(page, /patch_pachanga_match_player_paid/);
  assert.match(page, /patch_pachanga_match_scorers/);
  assert.match(page, /patch_pachanga_player_profile/);
  assert.match(page, /append_pachanga_player_rating/);
  assert.match(page, /partido_guardado/);
  assert.match(page, /partido_finalizado/);
  assert.match(page, /equipo_borrado/);
  assert.doesNotMatch(page, /Añade asistentes para calcularlo/);
  assert.match(globalsCss, /\.backup-panel/);
  assert.match(globalsCss, /\.backup-list article/);
  assert.match(supabaseSql, /create table if not exists public\.pachanga_group_backups/);
  assert.match(supabaseSql, /create or replace function public\.restore_pachanga_group_backup/);
  assert.match(supabaseSql, /payload_revision bigint not null default 0/);
  assert.match(supabaseSql, /create or replace function public\.is_registered_pachanga_user/);
  assert.match(supabaseSql, /create or replace function public\.save_pachanga_payload_if_current/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_player_status/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_player_paid/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_match_scorers/);
  assert.match(supabaseSql, /create or replace function public\.upsert_pachanga_own_player_profile/);
  assert.match(supabaseSql, /Only group members can create a player profile/);
  assert.match(supabaseSql, /This player profile already belongs to another user/);
  assert.match(supabaseSql, /grant execute on function public\.upsert_pachanga_own_player_profile/);
  assert.match(supabaseSql, /create or replace function public\.patch_pachanga_player_profile/);
  assert.match(supabaseSql, /create or replace function public\.append_pachanga_player_rating/);
  assert.match(supabaseSql, /birthDate/);
  assert.match(supabaseSql, /outfieldPosition/);
  assert.match(supabaseSql, /ratingRole/);
  assert.match(supabaseSql, /then 'goalkeeper'/);
  assert.match(supabaseSql, /Rating window closed for this player/);
  assert.match(supabaseSql, /last_vote_match_count \+ 3/);
  assert.match(supabaseSql, /current_group\.payload_revision <> expected_revision/);
  assert.match(supabaseSql, /policy "Admins can update groups"/);
  assert.match(supabaseSql, /public\.is_registered_pachanga_user\(\)/);
  assert.doesNotMatch(supabaseSql, /policy "Members can update groups"/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, title:/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, brand:/);
  assert.match(page, /update_pachanga_member_name/);
  assert.match(page, /if \(selectedPlayerIsOwn\) setProfileName\(normalizedName\)/);
  assert.doesNotMatch(page, /Guardar nombre/);
  assert.doesNotMatch(page, /Nombre en el equipo/);
  assert.doesNotMatch(page, /account-panel/);
  assert.doesNotMatch(page, /profile-name-field/);
  assert.doesNotMatch(globalsCss, /\.auth-panel/);
  assert.doesNotMatch(globalsCss, /\.profile-name-field/);
  assert.doesNotMatch(page, /onBlur=\{\(\) => setProfileName\(displayName\(profileName \|\| authDisplayName\(authUser\)\)\)\}/);
  assert.doesNotMatch(page, /const nextName = displayName\(profileName \|\| authDisplayName\(authUser\)\)/);
  assert.match(page, /Partido finalizado/);
  assert.doesNotMatch(page, /Modo local/);
  assert.match(layout, /title:\s*"Pachangas IQ"/);
  assert.match(layout, /appleWebApp/);
  assert.match(packageJson, /"@supabase\/supabase-js"/);
  assert.match(supabaseClient, /NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY/);
  assert.doesNotMatch(page, /SkeletonPreview/);
  assert.doesNotMatch(layout, /Starter Project|codex-preview/);
});
