import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds Pachangas IQ HTML", async () => {
  const html = await readFile(new URL("../.next/server/app/index.html", import.meta.url), "utf8");
  assert.match(html, /<html lang="es">/i);
  assert.match(html, /<title>Pachangas IQ<\/title>/i);
  assert.match(html, /El grupo del partido, pero con memoria\./);
  assert.match(html, /Confirmados/);
  assert.match(html, /Equipos sugeridos/i);
  assert.match(html, /Alineación abierta/);
  assert.match(html, /Continuar con Google/);
  assert.match(html, /Finalizar partido/);
  assert.match(html, /Añadir foto de equipo/);
  assert.match(html, /Comparte este partido!/);
  assert.match(html, /Copiar link/);
  assert.match(html, /Próximo partido/);
  assert.match(html, /Temporada/);
  assert.match(html, /Ordenar por/);
  assert.match(html, /2026-2027/);
  assert.match(html, /Navegación principal móvil/);
  assert.match(html, /Abrir manual de usuario/);
  assert.match(html, /\/manifest\.webmanifest/);
  assert.match(html, /\/apple-touch-icon\.png/);
  assert.match(html, /\/icon-192\.png/);
  assert.doesNotMatch(html, /Manual de usuario<\/span>/);
  assert.doesNotMatch(html, /Registro/);
  assert.doesNotMatch(html, /Entra para crear tu equipo/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site|react-loading-skeleton/i);
});

test("builds the user manual as its own page", async () => {
  const html = await readFile(new URL("../.next/server/app/manual.html", import.meta.url), "utf8");
  assert.match(html, /Manual de usuario/);
  assert.match(html, /Primera entrada/);
  assert.match(html, /Crear partido/);
  assert.match(html, /Guardar partido/);
  assert.match(html, /temporada, modalidad/);
  assert.match(html, /Jugador y admin/);
  assert.match(html, /Si cambias de Voy a Duda o No/);
  assert.match(html, /Cualquier miembro puede subir una foto de equipo/);
  assert.match(html, /foto en miniatura/);
  assert.match(html, /Borrar jugador lo deja fuera del grupo/);
  assert.match(html, /Ranking vivo/);
  assert.match(html, /Volver/);
});

test("keeps the project wired to the Pachangas app", async () => {
  const [page, layout, packageJson, supabaseClient, globalsCss, googleAuthPage] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
    readFile(new URL("../app/supabaseClient.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/auth/google/page.tsx", import.meta.url), "utf8"),
  ]);

  assert.match(page, /join_pachanga_team/);
  assert.match(page, /MemberRole/);
  assert.match(page, /incomingSharedLinkFromSearch/);
  assert.match(page, /needsLoginForSharedLink/);
  assert.match(page, /Continuar con Google y volver/);
  assert.match(page, /GoogleLogo/);
  assert.match(page, /google-signin-button/);
  assert.match(page, /Crea tu ficha para poder marcar/);
  assert.match(page, /gated-shell/);
  assert.match(page, /match-focus-card/);
  assert.match(page, /mobile-tabbar/);
  assert.match(page, /ownStatusText/);
  assert.match(page, /id="partido"/);
  assert.match(page, /id="equipos"/);
  assert.match(page, /id="ranking"/);
  assert.match(page, /RankingSort/);
  assert.match(page, /rankingSeason/);
  assert.match(page, /rankingSortLabels/);
  assert.match(page, /seasonKey/);
  assert.match(page, /matchSeason/);
  assert.match(page, /season: seasonKey/);
  assert.match(page, /season: activeMatchSeason/);
  assert.match(page, /rankingBadgeText/);
  assert.match(page, /teamPhoto\?: string/);
  assert.match(page, /matchPhotoDataUrl/);
  assert.match(page, /canUploadTeamPhoto/);
  assert.match(page, /Añadir foto de equipo/);
  assert.match(page, /Quitar foto/);
  assert.match(page, /history-photo/);
  assert.match(googleAuthPage, /safeReturnUrl/);
  assert.match(googleAuthPage, /url\.origin !== window\.location\.origin/);
  assert.match(page, /sha256Hex\(rawNonce\)/);
  assert.match(page, /authUrl\.searchParams\.set\("nonce", hashedNonce\)/);
  assert.match(page, /className="history-month"/);
  assert.match(page, /joinedAtLabel/);
  assert.match(page, /Voy desde/);
  assert.match(page, /perderás tu posición/);
  assert.match(globalsCss, /\.side-history \.history/);
  assert.match(globalsCss, /\.joined-at/);
  assert.match(globalsCss, /\.shared-link-gate/);
  assert.match(globalsCss, /\.gated-shell/);
  assert.match(globalsCss, /\.match-focus-card/);
  assert.match(globalsCss, /\.mobile-tabbar/);
  assert.match(globalsCss, /\.player-facing-main \.readonly-editor/);
  assert.match(globalsCss, /\.ranking-toolbar/);
  assert.match(globalsCss, /\.ranking-sort-buttons/);
  assert.match(globalsCss, /\.team-photo-card/);
  assert.match(globalsCss, /\.history-item\.has-photo/);
  assert.match(globalsCss, /\.google-signin-button/);
  assert.match(globalsCss, /scroll-margin-top:\s*14px/);
  assert.match(globalsCss, /overflow-y:\s*auto/);
  assert.match(globalsCss, /\.hero-actions\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(globalsCss, /overflow-x:\s*hidden/);
  assert.match(page, /Equipo pachanguero/);
  assert.match(page, /equipo/);
  assert.match(page, /compactUuid/);
  assert.match(page, /expandCompactUuid/);
  assert.match(page, /remoteInviteToken/);
  assert.match(page, /canEditMatchSettings\s*=\s*canUseAdminControls\s*&&\s*!matchFinalized/);
  assert.match(page, /showPlayerSwitcher\s*=\s*Boolean\(canUseAdminControls\s*&&\s*selectedPlayer\s*&&\s*!selectedPlayerIsOwn/);
  assert.match(page, /profile-player-switcher/);
  assert.match(page, /function scrollToPlayerProfile/);
  assert.match(page, /function scrollToPanel/);
  assert.match(page, /function toggleQuickForm/);
  assert.match(page, /function selectMatch/);
  assert.match(page, /matchPanelRef/);
  assert.match(page, /settingsPanelRef/);
  assert.match(page, /scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(page, /selectedPlayerId === playerId/);
  assert.match(page, /saveSelectedPlayerProfile/);
  assert.match(page, /Guardar ficha/);
  assert.match(page, /goalkeeperRatingFacets/);
  assert.match(page, /Salidas/);
  assert.match(page, /Paradas/);
  assert.match(page, /Saque/);
  assert.match(page, /Reflejos/);
  assert.match(page, /Velocidad/);
  assert.match(page, /Posición/);
  assert.match(page, /short: "SAL"/);
  assert.match(page, /short: "PAR"/);
  assert.match(page, /short: "SAQ"/);
  assert.match(page, /short: "REF"/);
  assert.match(page, /short: "VEL"/);
  assert.match(page, /short: "POS"/);
  assert.match(page, /selectedRatingFacets\.map/);
  assert.match(page, /ratingFacetsForPlayer\(player\)/);
  assert.match(page, /team-hero-logo/);
  assert.match(page, /Equipo: \{currentTeamName\}/);
  assert.match(page, /Instrucciones/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, title:/);
  assert.doesNotMatch(page, /setSiteSettings\(\{ \.\.\.siteSettings, brand:/);
  assert.match(page, /const nextName = displayName\(profileName\.trim\(\)\)/);
  assert.doesNotMatch(page, /onBlur=\{\(\) => setProfileName\(displayName\(profileName \|\| authDisplayName\(authUser\)\)\)\}/);
  assert.doesNotMatch(page, /const nextName = displayName\(profileName \|\| authDisplayName\(authUser\)\)/);
  assert.match(page, /Partido finalizado/);
  assert.doesNotMatch(page, /Modo local/);
  assert.match(layout, /title:\s*"Pachangas IQ"/);
  assert.match(layout, /appleWebApp/);
  assert.match(packageJson, /"@supabase\/supabase-js"/);
  assert.match(supabaseClient, /NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY/);
  assert.doesNotMatch(page, /SkeletonPreview/);
  assert.doesNotMatch(layout, /Starter Project|codex-preview/);
});
