export type PremiumArtDecision = "DESCARTAR" | "MANTENER" | "REVISAR";

export type PremiumArtProposal = {
  asset?: string;
  collection: "Base IQ" | "Fútbol de Barrio" | "Future IQ" | "Noche de Partido" | "Retro";
  decision: PremiumArtDecision;
  description: string;
  id: string;
  lod: string;
  name: string;
  performance: string;
  reuse: "Equipo" | "Jugador" | "Jugador + equipo";
  technique: "2D" | "3D prerender" | "Pseudo-3D";
  type: "Banner" | "Corona" | "Efecto" | "Estrella" | "Laureles" | "Material" | "Símbolo";
  visual: string;
};

export const PREMIUM_ART_PACK_V1: readonly PremiumArtProposal[] = [
  {
    asset: "/lab/premium-art-pack-v1/symbol-abstract-ball.svg",
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Balón reducido a pentágono, órbita y enlaces de juego.",
    id: "symbol-abstract-ball",
    lod: "Contorno + pentágono en 32px",
    name: "Balón Orbital IQ",
    performance: "SVG 1.0 KB",
    reuse: "Jugador + equipo",
    technique: "2D",
    type: "Símbolo",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/symbol-barrio-gate.svg",
    collection: "Fútbol de Barrio",
    decision: "MANTENER",
    description: "Portería y arco de barrio sin parecer un logotipo real.",
    id: "symbol-barrio-gate",
    lod: "Arco exterior en 32px",
    name: "Puerta del Barrio",
    performance: "SVG 0.8 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Símbolo",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/symbol-future-iq.svg",
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Red hexagonal con núcleo central para tecnología deportiva.",
    id: "symbol-future-node",
    lod: "Hexágono + núcleo en 32px",
    name: "Nodo Future IQ",
    performance: "SVG 0.9 KB",
    reuse: "Jugador + equipo",
    technique: "2D",
    type: "Símbolo",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/symbol-compass-ball.svg",
    collection: "Noche de Partido",
    decision: "REVISAR",
    description: "Brújula competitiva con núcleo de balón abstracto.",
    id: "symbol-compass-ball",
    lod: "Estrella de cuatro puntas en 32px",
    name: "Brújula de Partido",
    performance: "SVG 0.7 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Símbolo",
    visual: "asset",
  },
  {
    collection: "Fútbol de Barrio",
    decision: "MANTENER",
    description: "Torre con almenas y base compacta, refinada desde el catálogo actual.",
    id: "symbol-tower-elite",
    lod: "Silueta sin ventanas en 32px",
    name: "Torre Elite Mk II",
    performance: "CSS/SVG inline < 1 KB",
    reuse: "Equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "tower",
  },
  {
    collection: "Noche de Partido",
    decision: "MANTENER",
    description: "Dos rayos enfrentados con centro libre para las iniciales.",
    id: "symbol-twin-bolt",
    lod: "Un rayo en 24px",
    name: "Rayo Doble Táctico",
    performance: "CSS clip-path",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "twin-bolt",
  },
  {
    collection: "Retro",
    decision: "MANTENER",
    description: "Monograma en bloque con relieve sobrio y lectura de dos letras.",
    id: "symbol-block-monogram",
    lod: "Dos letras planas en 24px",
    name: "Monograma Bloque",
    performance: "HTML/CSS sin asset",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "monogram",
  },
  {
    collection: "Retro",
    decision: "REVISAR",
    description: "Insignia contenida dentro de una segunda geometría heráldica.",
    id: "symbol-nested-badge",
    lod: "Dos contornos en 32px",
    name: "Insignia Anidada",
    performance: "CSS 0 KB",
    reuse: "Equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "nested",
  },
  {
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Estrella técnica de ocho puntas con centro limpio.",
    id: "symbol-vector-star",
    lod: "Cuatro puntas en 24px",
    name: "Estrella Vector IQ",
    performance: "CSS clip-path",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "vector-star",
  },
  {
    collection: "Base IQ",
    decision: "REVISAR",
    description: "Corona compacta concebida como símbolo central, no como adorno superior.",
    id: "symbol-geometric-crown",
    lod: "Tres picos sólidos en 32px",
    name: "Corona Geométrica",
    performance: "CSS clip-path",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Símbolo",
    visual: "crown-symbol",
  },
  {
    asset: "/lab/premium-art-pack-v1/crown-barrio.svg",
    collection: "Fútbol de Barrio",
    decision: "MANTENER",
    description: "Corona forjada, ancha y robusta para identidad de barrio.",
    id: "crown-barrio",
    lod: "Silueta y base en 48px",
    name: "Corona Barrio",
    performance: "SVG 1.0 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Corona",
    visual: "asset-wide",
  },
  {
    asset: "/lab/premium-art-pack-v1/crown-elite-blender.webp",
    collection: "Noche de Partido",
    decision: "MANTENER",
    description: "Oro satinado, base oscura y tres puntos de luz cian.",
    id: "crown-elite",
    lod: "Prerender 768; silueta SVG futura en 48px",
    name: "Corona Elite",
    performance: "WebP 16 KB",
    reuse: "Jugador + equipo",
    technique: "3D prerender",
    type: "Corona",
    visual: "asset-wide",
  },
  {
    asset: "/lab/premium-art-pack-v1/crown-future-iq.svg",
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Tres nodos y trazado de circuito con aire tecnológico.",
    id: "crown-future",
    lod: "Trazado principal en 48px",
    name: "Corona Future IQ",
    performance: "SVG 1.0 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Corona",
    visual: "asset-wide",
  },
  {
    asset: "/lab/premium-art-pack-v1/crown-retro.svg",
    collection: "Retro",
    decision: "MANTENER",
    description: "Corona clásica con tres remaches y contraste marfil.",
    id: "crown-retro",
    lod: "Remaches omitidos en 48px",
    name: "Corona Retro Club",
    performance: "SVG 1.0 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Corona",
    visual: "asset-wide",
  },
  {
    collection: "Base IQ",
    decision: "MANTENER",
    description: "Estrella única sin animación para hitos legibles en pequeño.",
    id: "star-single",
    lod: "Misma silueta 24–210px",
    name: "Estrella Singular",
    performance: "CSS 0 KB",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Estrella",
    visual: "single-star",
  },
  {
    collection: "Retro",
    decision: "MANTENER",
    description: "Tres estrellas con jerarquía central y espaciado para 48px.",
    id: "star-trio",
    lod: "Una estrella en 24–32px",
    name: "Trío de Estrellas",
    performance: "HTML/CSS 0 KB",
    reuse: "Equipo",
    technique: "Pseudo-3D",
    type: "Estrella",
    visual: "star-trio",
  },
  {
    asset: "/lab/premium-art-pack-v1/star-medallion-blender.webp",
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Medallón de plata, esmalte navy y estrella cian prerenderizada.",
    id: "star-medallion",
    lod: "WebP grande; parche plano en 48px",
    name: "Medallón Future",
    performance: "WebP 32 KB",
    reuse: "Jugador + equipo",
    technique: "3D prerender",
    type: "Estrella",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/star-patch.svg",
    collection: "Noche de Partido",
    decision: "REVISAR",
    description: "Parche bordado preparado visualmente para una futura temporada, sin mapping.",
    id: "star-patch",
    lod: "Sin pespunte en 32px",
    name: "Parche Estrella",
    performance: "SVG 1.0 KB",
    reuse: "Jugador + equipo",
    technique: "2D",
    type: "Estrella",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/laurels-minted.svg",
    collection: "Retro",
    decision: "MANTENER",
    description: "Laureles metálicos con remate central; mejora propuesta para 25 partidos.",
    id: "laurels-minted",
    lod: "Ramas y cuatro hojas en 48px",
    name: "Laureles Minted",
    performance: "SVG 1.1 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Laureles",
    visual: "asset",
  },
  {
    asset: "/lab/premium-art-pack-v1/laurels-minted.svg",
    collection: "Retro",
    decision: "MANTENER",
    description: "Versión de lectura rápida validable a 64, 48 y 32px.",
    id: "laurels-compact",
    lod: "Oculta hojas alternas por CSS",
    name: "Laureles Compactos",
    performance: "Reutiliza el mismo SVG",
    reuse: "Equipo",
    technique: "2D",
    type: "Laureles",
    visual: "asset-compact",
  },
  {
    asset: "/lab/premium-art-pack-v1/banner-challenge.svg",
    collection: "Fútbol de Barrio",
    decision: "MANTENER",
    description: "Cinta robusta con placa central para el premio de 10 Retos.",
    id: "banner-challenge",
    lod: "Placa simple y sin texto en 48px",
    name: "Banner de Reto",
    performance: "SVG 0.9 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Banner",
    visual: "asset-wide",
  },
  {
    asset: "/lab/premium-art-pack-v1/banner-ribbon.svg",
    collection: "Future IQ",
    decision: "REVISAR",
    description: "Ribbon técnico con nodo y línea para colecciones futuras.",
    id: "banner-future",
    lod: "Cinta exterior omitida en 48px",
    name: "Ribbon Future IQ",
    performance: "SVG 1.0 KB",
    reuse: "Equipo",
    technique: "2D",
    type: "Banner",
    visual: "asset-wide",
  },
  {
    collection: "Fútbol de Barrio",
    decision: "REVISAR",
    description: "Placa corta que no compite con las iniciales del escudo.",
    id: "banner-plate",
    lod: "Rectángulo único en 32px",
    name: "Placa Barrio",
    performance: "CSS 0 KB",
    reuse: "Equipo",
    technique: "Pseudo-3D",
    type: "Banner",
    visual: "plate",
  },
  {
    collection: "Fútbol de Barrio",
    decision: "MANTENER",
    description: "Cobre cálido que separa geometría de material y conserva lectura.",
    id: "material-copper",
    lod: "Plano cobrizo en 24–32px",
    name: "Cobre Forjado",
    performance: "Gradiente CSS + textura actual",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Material",
    visual: "copper",
  },
  {
    collection: "Retro",
    decision: "MANTENER",
    description: "Plata satinada con brillo limitado para no perder texto.",
    id: "material-silver",
    lod: "Dos tonos en 24–32px",
    name: "Plata Satinada",
    performance: "Gradiente CSS + textura actual",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Material",
    visual: "silver",
  },
  {
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Carbono mate de baja reflexión con trama visible solo en grande.",
    id: "material-carbon",
    lod: "Negro mate sin trama en 32px",
    name: "Carbono Táctico",
    performance: "Dos gradientes CSS",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Material",
    visual: "carbon",
  },
  {
    collection: "Future IQ",
    decision: "REVISAR",
    description: "Cromo frío sobre base navy; reservado a superficies grandes.",
    id: "material-chrome-navy",
    lod: "Navy sólido en 24–48px",
    name: "Cromo Navy",
    performance: "Gradiente CSS",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Material",
    visual: "chrome-navy",
  },
  {
    collection: "Future IQ",
    decision: "MANTENER",
    description: "Resplandor limitado al contorno, visible sin dominar el escudo.",
    id: "effect-edge-glow",
    lod: "Halo estático en 24–48px",
    name: "Edge Glow Controlado",
    performance: "Box-shadow; sin asset",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Efecto",
    visual: "edge-glow",
  },
  {
    collection: "Noche de Partido",
    decision: "DESCARTAR",
    description: "La versión continua compite con la información y añade movimiento permanente.",
    id: "effect-holo-loop",
    lod: "No aplica",
    name: "Holo Loop Continuo",
    performance: "Animación permanente",
    reuse: "Jugador + equipo",
    technique: "Pseudo-3D",
    type: "Efecto",
    visual: "holo",
  },
] as const;
