const manualFlows = [
  {
    audience: "Todos",
    title: "Primera entrada",
    intro: "Al abrir Pachangas IQ puedes revisar una demo completa o entrar con Google para usar un grupo real.",
    steps: [
      "La demo muestra jugadores, partidos, historial, reservas, pagos, fichas y valoraciones para probar la web sin crear nada.",
      "Aunque ya tengas cuenta, puedes volver a la Demo interactiva desde el selector de grupo. La demo no modifica tus grupos reales.",
      "Para crear grupos, partidos, campos o administrar datos necesitas entrar con Google.",
      "Cuando creas un grupo real, empieza limpio: sin jugadores, sin campos y sin partidos de demo.",
      "Si llegas con un enlace de invitación, entras directamente al grupo correspondiente.",
    ],
  },
  {
    audience: "Todos",
    title: "Instalar la app y usar el modo juego",
    intro: "Pachangas IQ se puede instalar como PWA y adapta su interfaz al tamaño y la orientación del dispositivo.",
    steps: [
      "En Android o Chrome usa Instalar aplicación; en iPhone o iPad usa Compartir > Añadir a pantalla de inicio.",
      "En vertical verás la navegación rápida. Al girar un móvil o tablet compatible a horizontal aparece el modo juego con menú superior y submenú lateral.",
      "La rotación no recarga la página ni pierde el estado: solo reorganiza los mismos datos y controles.",
      "La lupa de Alineación abre el campo a pantalla completa. En navegadores compatibles también solicita pantalla completa para aprovechar más espacio.",
      "La barra de estado puede ocultarse en Android instalado; iPhone y iPad deciden si mantienen hora y batería visibles.",
      "Si hay una actualización obligatoria, la app pausa nuevas escrituras, actualiza su Service Worker y realiza una sola recarga controlada.",
    ],
  },
  {
    audience: "Todos",
    title: "Crear o entrar en un grupo de pachangas",
    intro: "El grupo de pachangas es el espacio privado donde se guardan jugadores, campos, partidos e historial.",
    steps: [
      "Si entras con una invitación al grupo, la web te pide Google si hace falta y después vuelve al grupo correcto.",
      "Tu ficha de jugador es universal: la misma identidad y carta base te acompañan en todos los grupos a los que perteneces.",
      "Cada grupo mantiene aparte sus miembros, partidos, goles, victorias, pagos e historial. Entrar en otro grupo no duplica ni reinicia tu ficha universal.",
      "Si empiezas desde cero, pulsa Crear > Grupo, escribe el nombre y guarda. El primer usuario queda como Owner / Admin.",
      "Cuando creas un grupo real, empieza limpio: sin jugadores, sin campos y sin partidos de demo.",
      "La invitación al grupo añade a la persona como jugador. Es distinta del enlace para compartir un partido y de la invitación como admin.",
      "Comparte la invitación del grupo con los iconos de copiar o WhatsApp para que entren los demás.",
    ],
  },
  {
    audience: "Jugador",
    title: "Tu cuenta y tu ficha",
    intro: "Cada usuario registrado tiene una única ficha universal, que sirve como identidad deportiva en toda Pachangas IQ.",
    steps: [
      "Entra con Google y cambia tu nombre visible en el grupo, por ejemplo Alberto.",
      "La primera vez debes completar el test inicial obligatorio para crear la carta. Solo puede completarse una vez, así que responde con la máxima sinceridad.",
      "El test pregunta modalidad, posición, nivel alcanzado, cuándo jugabas a ese nivel, frecuencia y situaciones técnicas. Si sales antes de terminar, no se guarda un resultado incompleto.",
      "Después puedes hacer una sola vez el test avanzado opcional desde Mi ficha > Mejorar precisión de mi ficha. Sus preguntas se adaptan al resultado inicial.",
      "Pulsa Mi ficha para editar tus datos personales permitidos: nombre, teléfono Bizum, foto, posición preferida y estado. El test y las valoraciones no se sustituyen escribiendo una media a mano.",
      "Puedes añadir foto desde archivo o cámara; la app intenta centrar el avatar y puedes arrastrarlo dentro de la carta antes de guardar.",
      "Solo tú y los admins podéis editar tu ficha. Las valoraciones las hacen compañeros, no puedes votarte a ti mismo.",
      "La carta base procede de tus tests; la carta calibrada incorpora valoraciones válidas y la carta actual añade el estado deportivo vigente.",
    ],
  },
  {
    audience: "Admin",
    title: "Prueba gratuita y suscripción",
    intro: "Cada grupo puede probar la app con partidos reales antes de pagar.",
    steps: [
      "El owner del grupo puede crear y finalizar 2 partidos gratis.",
      "Cuando se intenta crear, guardar o finalizar el tercer partido, la app pide activar un plan de Stripe.",
      "Solo paga el owner del grupo. Los admins y jugadores pueden usar el grupo sin pagar una cuenta propia.",
      "Plan mensual: 5,99 € al mes. Plan anual: 64,99 € al año.",
      "Fórmula del trial: partidos gratis restantes = 2 - partidos finalizados del grupo sin suscripción activa.",
      "Fórmula de acceso: si la suscripción está activa o en periodo trialing de Stripe, el grupo puede crear y finalizar partidos sin límite.",
    ],
  },
  {
    audience: "Admin",
    title: "Campos y ajustes iniciales",
    intro: "Antes de crear partidos conviene guardar los campos habituales y los ajustes básicos del sitio.",
    steps: [
      "Pulsa Crear > Campo para guardar un campo con nombre, precio y modalidad por defecto.",
      "El nombre del campo debe elegirse desde una sugerencia de Google Places para guardar una dirección real, placeId y ubicación aproximada.",
      "Esa ubicación sirve después para filtrar el mercado de fichajes por proximidad al partido sin pedir direcciones privadas a jugadores.",
      "También sirve para consultar Google Weather y mostrar la previsión del tiempo cuando el partido está dentro de los próximos 7 días.",
      "Para controlar consumo, la previsión se reutiliza 24 horas si falta más de 1 día y 2 horas durante las últimas 24 horas antes del partido.",
      "Google Places solo se usa al buscar o seleccionar direcciones; si el campo ya tiene placeId y coordenadas guardadas, la app reutiliza esos datos.",
      "La modalidad puede ser fútbol sala, fútbol 7 o fútbol 11.",
      "En Configurar puedes cambiar las instrucciones del grupo y los colores de los equipos.",
      "Desde Configurar también puedes borrar campos guardados que ya no usas o que se crearon mal. Los partidos históricos conservan el nombre del campo.",
      "Los colores elegidos se aplican a bloques, listas, fichas, campo y goleadores.",
      "También puedes activar Aporte app por Bizum para mostrar una referencia separada del precio del campo.",
    ],
  },
  {
    audience: "Admin",
    title: "Crear partido",
    intro: "Un partido nuevo nace como borrador para evitar que la gente se apunte antes de estar bien configurado.",
    steps: [
      "Pulsa Crear > Partido y revisa campo, fecha, modalidad, precio y reservas.",
      "La temporada no se elige a mano: se calcula desde la fecha y se guarda en la ficha del partido.",
      "Cada temporada empieza en septiembre y termina en agosto del año siguiente.",
      "Mientras no pulses Guardar partido, no aparece en Próximos partidos y nadie puede marcar asistencia.",
      "Al guardar se activan confirmaciones, compartir, alineación, resultado y pago.",
      "Si el campo tiene ubicación verificada, verás Tiempo previsto con temperatura, lluvia y viento aproximados durante el partido.",
      "Cualquier miembro del grupo puede compartir el enlace corto del partido con Copiar link o WhatsApp.",
      "Ese enlace no concede permisos: después de iniciar sesión solo abre el partido si la persona ya pertenece al grupo.",
      "Solo un admin puede crear una invitación distinta que conceda acceso limitado a ese partido concreto.",
      "Si te equivocas o el partido no se juega, puedes borrarlo con papelera y doble confirmación.",
    ],
  },
  {
    audience: "Jugador",
    title: "Apuntarte a un partido",
    intro: "Un partido solo acepta respuestas cuando el admin lo ha guardado.",
    steps: [
      "Si el partido está en borrador, verás que la alineación y las confirmaciones están pendientes.",
      "Si hay un partido anterior pendiente y su fecha todavía no ha pasado, la inscripción del siguiente partido queda cerrada hasta después de esa hora.",
      "Cuando el partido está guardado puedes marcar Voy, Duda o No.",
      "El orden de Voy se guarda con día y hora. Ese orden decide titulares, reservas y lista de espera.",
      "Si cambias de Voy a Duda o No, la app avisa de que perderás tu posición; si hay reservas, el primero sube.",
      "Si estás marcado como lesionado, apareces como No voy hasta que se quite la lesión.",
    ],
  },
  {
    audience: "Jugador",
    title: "Reservas y pago",
    intro: "Las reservas pueden quedar fuera o contar como asistentes según configure el admin.",
    steps: [
      "Si Reservas van y pagan está activo, las reservas dentro del máximo cuentan para el pago.",
      "Si no está activo, las reservas quedan como suplentes por orden y no entran en el reparto.",
      "El turno de pago del campo y el importe por jugador se calculan cuando el admin cierra la alineación.",
      "Hasta cerrar la alineación, Toca, Paga y Pagados aparecen pendientes porque la lista todavía puede cambiar.",
      "Una vez cerrada, el pagador aparece destacado con el dólar dorado.",
      "Cada jugador puede verse como pagado cuando se marque su dólar en verde.",
      "La cuota de la app, si el admin decide repartirla, se muestra aparte como aporte por Bizum al owner y no se suma al precio del campo.",
      "Fórmula del campo: toca por jugador = precio del campo / jugadores que pagan campo.",
      "Fórmula de aporte app: aporte por jugador = coste mensual o anual elegido / jugadores activos del grupo.",
    ],
  },
  {
    audience: "Admin",
    title: "Alineaciones",
    intro: "La app propone equipos y coloca fichas en el campo según modalidad y posiciones.",
    steps: [
      "Los porteros fijos se separan en equipos diferentes cuando hay dos disponibles.",
      "Puedes mover jugadores manualmente desde la lista o arrastrando sus fichas en el campo. Al soltarlos sobre un compañero intercambian posición; al soltarlos sobre un rival cambian de equipo.",
      "También puedes arrastrar una ficha a un hueco vacío del campo. Los cambios manuales se respetan hasta que vuelvas a pedir otro reparto.",
      "Aleatorio reparte al azar; Equilibrado intenta compensar medias y posiciones.",
      "Cerrar alineación bloquea la alineación para jugadores; Abrir alineación permite cambios de nuevo.",
      "Si alguien se baja, el primer reserva sube automáticamente aunque la alineación estuviera cerrada.",
      "En modo juego, un toque abre la ficha del jugador y una pulsación con arrastre mueve la ficha. La lupa amplía el campo sin desactivar estas acciones.",
      "El modo Pizarra permite mover fichas libremente, dibujar con los colores de ambos equipos, ocultar jugadores y borrar el dibujo. Es una ayuda temporal y no cambia la alineación oficial.",
    ],
  },
  {
    audience: "Admin",
    title: "Finalizar partido",
    intro: "Finalizar archiva el partido en historial y actualiza estadísticas.",
    steps: [
      "Primero rellena el resultado. Hasta entonces no se pueden asignar goles.",
      "Los goles se introducen por equipo y la app no deja superar el marcador de cada lado.",
      "Cualquier miembro puede subir una foto del partido como recuerdo; solo un admin puede quitarla.",
      "Al pulsar Finalizar partido, el partido pasa al historial.",
      "Después de finalizar, campo, fecha, modalidad, precio y reservas quedan bloqueados.",
      "La alineación, el equilibrio y las cartas quedan guardados como una fotografía de ese momento. Un histórico no usa después los niveles vivos de los jugadores.",
      "Si hubo un error, un admin puede corregir asistencia y goleadores mediante las opciones permitidas, manteniendo el historial auditado.",
    ],
  },
  {
    audience: "Todos",
    title: "Historial y ranking",
    intro: "La memoria del grupo vive en los partidos cerrados, el ranking y las fichas.",
    steps: [
      "Próximos partidos muestra solo partidos abiertos y guardados.",
      "Historial muestra los últimos partidos con separadores por mes, foto en miniatura y resumen de pago y goles.",
      "El ranking se puede filtrar por la temporada guardada en cada partido, de septiembre a agosto, y ordenar por media, goles, partidos o ganados.",
      "Cada carta del ranking abre la ficha del jugador para consultar detalle, estado y evolución.",
      "Al abrir un partido histórico verás su propia alineación y resultado. No se puede arrastrar, reequilibrar ni usar Pizarra porque representa lo que ocurrió ese día.",
      "Pulsa la foto del partido para verla ampliada y ciérrala para volver al histórico.",
    ],
  },
  {
    audience: "Todos",
    title: "Mercado de fichajes",
    intro: "El mercado vive en una página separada del grupo privado para encontrar jugadores por zona, horario y modalidad.",
    steps: [
      "Cada jugador decide si publica su ficha en el mercado desde su propia ficha. Es opt-in: si no lo activas, no apareces.",
      "Se publican datos base: nombre, foto, encuadre, edad, posición, media, zonas donde puedes jugar, disponibilidad y si aceptas invitaciones puntuales o de grupo.",
      "Cada zona se elige con Google Places y tiene radio propio: solo esta población, +5, +10, +20, +30 o +50 km.",
      "Si pones Sabadell con solo esta población no apareces para Barcelona; si pones Sabadell +20 km, puedes aparecer para campos dentro de ese radio.",
      "El mercado filtra primero con distancia aproximada por coordenadas guardadas, sin llamar a Google Routes ni consumir rutas de pago.",
      "No se publican votos concretos, teléfono Bizum, historial privado del grupo ni datos internos de pagos.",
      "Los jugadores normales pueden consultar y filtrar el mercado. Solo owners y admins pueden enviar invitaciones desde un partido guardado.",
      "La pestaña Jugadores disponibles muestra quién acepta invitaciones puntuales; Partidos abiertos permite solicitar plazas; Retos privados y Equipos retables reúnen los flujos entre equipos.",
    ],
  },
  {
    audience: "Admin",
    title: "Invitar a un jugador a un partido",
    intro: "Una invitación puntual se envía desde un partido concreto y nunca concede acceso al grupo ni permisos administrativos.",
    steps: [
      "Guarda el partido y abre Admin > Buscar jugadores, o entra en Mercado > Jugadores disponibles desde ese partido.",
      "Los filtros del partido usan su modalidad, ubicación y plazas. Solo puedes invitar a jugadores que hayan activado Invitado puntual.",
      "Pulsa Enviar invitación. Mientras esté pendiente puedes cancelarla; no se ocupa una plaza hasta que el jugador la acepta.",
      "El jugador recibe un aviso con Aceptar y Rechazar. La respuesta y el estado confirmado se actualizan en ambos dispositivos.",
      "Al aceptar, el jugador queda vinculado únicamente a ese partido y puede abrirlo desde Ver partido. No entra como miembro del grupo.",
      "También puedes crear un enlace de invitación al partido para alguien que todavía no esté registrado. Tras iniciar sesión podrá aceptar o rechazar el acceso limitado.",
    ],
  },
  {
    audience: "Jugador y admin",
    title: "Partidos públicos y solicitudes de plaza",
    intro: "Un admin puede publicar las plazas libres de un partido para que otros usuarios registrados soliciten entrar.",
    steps: [
      "En el Admin del partido, configura los filtros y pulsa Abrir al mercado. Puedes indicar plazas públicas, modalidad, nivel, posiciones y si el invitado paga.",
      "El partido aparece en Mercado > Partidos abiertos sin revelar teléfonos, pagos privados ni información interna del grupo.",
      "Un jugador pulsa Solicitar plaza. Mientras esté pendiente puede Cancelar solicitud; si fue rechazada, puede Solicitar otra vez mientras el partido siga abierto.",
      "El owner o admin recibe un aviso y decide Aceptar plaza o Rechazar. El solicitante recibe el resultado en sus avisos.",
      "Una solicitud pública nunca se confirma si ya no queda plaza. El servidor vuelve a comprobar el cupo en el momento de aceptar.",
      "El admin puede actualizar los filtros o Cerrar mercado sin borrar el partido.",
    ],
  },
  {
    audience: "Invitado",
    title: "Acceso a un partido como invitado",
    intro: "Una invitación o solicitud aceptada abre una vista segura del partido concreto, no del grupo completo.",
    steps: [
      "Desde el aviso o Mercado pulsa Ver partido para abrir la vista de invitado.",
      "Puedes ver fecha, campo, modalidad, confirmados, alineación abierta o cerrada, jugadores y resultado cuando exista.",
      "Los cambios de asistencia y alineación llegan en tiempo real y la pantalla recupera el estado oficial del servidor.",
      "No puedes editar a otros jugadores, administrar el partido ni consultar teléfonos, pagos, Bizum u otros datos sensibles del grupo.",
      "Si finalmente no vas, pulsa Abandonar partido y confirma. La plaza queda libre y pierdes el acceso inmediatamente.",
      "El admin recibe una incidencia de abandono y puede Confirmar abandono o Descartar. Esta incidencia de conducta no modifica la media ni las facetas deportivas.",
    ],
  },
  {
    audience: "Todos",
    title: "Centro de avisos",
    intro: "Avisos reúne las decisiones que requieren respuesta y se actualiza sin recargar toda la página.",
    steps: [
      "El contador muestra cuántas notificaciones quedan sin leer.",
      "Un jugador puede aceptar o rechazar una invitación puntual y abrir el partido cuando ya está aceptada.",
      "Un admin puede aceptar o rechazar solicitudes de plazas públicas y revisar abandonos de invitados.",
      "También puedes marcar un aviso como leído sin ejecutar ninguna acción.",
      "Los botones esperan la confirmación del servidor: un error de conexión nunca se presenta como una aceptación completada.",
    ],
  },
  {
    audience: "Admin",
    title: "Publicar un equipo retable",
    intro: "Cada grupo decide voluntariamente si quiere aparecer en el buscador público de equipos.",
    steps: [
      "En Mercado > Equipos retables, el owner o admin elige su grupo y pulsa Configurar mi ficha.",
      "Activa Disponible y define ciudad o comarca, radio de desplazamiento, nivel mínimo y máximo del rival, modalidades y franjas de días y horas.",
      "La ficha pública muestra una zona aproximada, nunca una dirección habitual. El campo exacto solo se comparte dentro de un reto privado.",
      "Cualquier miembro puede buscar por zona, distancia, nivel, día, hora y modalidad. Solo owners y admins pueden pulsar Preparar reto.",
      "La compatibilidad y el nivel mostrados proceden del estado confirmado del servidor.",
    ],
  },
  {
    audience: "Jugador y admin",
    title: "Retos privados entre equipos",
    intro: "Los retos permiten acordar un partido entre dos grupos sin publicar sus detalles exactos.",
    steps: [
      "Cada grupo tiene un código de equipo. Un owner o admin puede introducir el código rival o preparar el reto desde un equipo retable.",
      "Completa fecha y hora, fútbol sala, fútbol 7 o fútbol 11, campo, dirección, enlace opcional de Google Maps y un mensaje.",
      "El rival recibe el reto y sus admins pueden Aceptar, Rechazar o Proponer cambios. El equipo que lo envió también puede Cancelar o responder con otra contrapropuesta.",
      "Los miembros sin permisos de admin pueden consultar el estado, pero no aceptar ni modificar acuerdos.",
      "Los retos aceptados pasan a Retos acordados; los rechazados o cancelados quedan en Historial de retos.",
      "Después de finalizar y enlazar un partido contra otro grupo, ese equipo aparece en Rivales conocidos y se puede Retar de nuevo.",
    ],
  },
  {
    audience: "Jugador",
    title: "Valoraciones",
    intro: "Las valoraciones comparan a un compañero contigo en cada faceta; ya no permiten escribir notas absolutas.",
    steps: [
      "Puedes valorar inmediatamente a otro miembro activo de tu grupo aunque todavía no hayáis jugado juntos. No puedes valorarte a ti mismo.",
      "Para ritmo, tiro, pase, regate, defensa y físico eliges Mucho peor, Peor, Parecido, Mejor o Mucho mejor respecto a tu propia carta.",
      "Después de tu primera valoración, solo puedes sustituirla cuando ambos hayáis compartido 3 partidos finalizados adicionales.",
      "Solo existe una opinión activa por pareja. La nueva sustituye a la anterior, pero el historial queda conservado para auditoría.",
      "La identidad de quien valora es anónima para el evaluado, los demás miembros y los admins ordinarios. Tú sí puedes consultar tu propia opinión.",
      "La media social detallada permanece oculta hasta reunir 3 evaluadores independientes activos.",
      "Los admins pueden activar o desactivar las valoraciones del grupo y moderar una opinión con un identificador anónimo.",
      "La valoración específica de portero sigue pendiente; la app bloquea ese formulario en vez de inventar una fórmula incorrecta.",
      "La placa de la ficha cambia por media: bronce hasta 64, plata de 65 a 74 y oro desde 75.",
    ],
  },
  {
    audience: "Admin",
    title: "Valoraciones globales de un partido",
    intro: "Después de jugar contra gente externa, los admins pueden comparar el nivel global observado con el de su propia alineación.",
    steps: [
      "En el partido, añade un rival externo por nombre y zona o enlaza otro grupo registrado mediante su código.",
      "La valoración se hace sobre el equipo completo con Mucho peor, Peor, Parecido, Mejor o Mucho mejor; nunca se inventan fichas individuales de sus jugadores.",
      "Los invitados puntuales también pueden recibir una valoración global provisional respecto a vuestra alineación.",
      "Si quieres que un invitado valore a vuestro equipo, genera un enlace de un solo uso. El enlace caduca a las 24 horas.",
      "Cuando responden varios admins, el servidor combina sus respuestas en una única observación oficial por objetivo.",
    ],
  },
  {
    audience: "Todos",
    title: "Media, forma y equilibrio",
    intro: "La carta separa la base declarada, la calibración social y el estado actual para que cada cambio tenga un origen claro.",
    steps: [
      "Base = resultado del test inicial y, si lo completas, del test avanzado. Ningún compañero puede sobrescribirla directamente.",
      "Calibrada = base combinada en el servidor con una opinión activa por evaluador. Cada comparación tiene una influencia limitada para evitar subidas o bajadas bruscas.",
      "Actual = calibrada más los modificadores deportivos vigentes. Es la cifra principal que muestra la carta.",
      "El desglose social no aparece hasta reunir 3 evaluadores independientes. Antes se muestra el progreso de calibración, no una media engañosa.",
      "Forma actual = porcentaje temporal visible de 0 a 100 calculado con los últimos 5 partidos jugados, la racha sin venir, lesiones y fiabilidad; no se muestra hasta que el jugador tenga al menos un partido finalizado.",
      "Nota reciente de partido = 6.2 más ajustes por victoria, derrota ajustada o amplia, goles, portería a cero y pocos o muchos goles encajados.",
      "Antes de tener partidos, la app usa una forma neutral interna del 100% solo para equilibrar, pero la ficha muestra Forma pendiente para no inventar un dato.",
      "Una lesión o ausencia no reescribe la base ni la calibración social. Solo puede influir en el estado temporal usado para organizar el siguiente partido.",
      "Fiabilidad = 100% menos 7 puntos por cada cancelación tarde, con mínimo 70%. Afecta al equilibrio, no a la media.",
      "Valor para equilibrar = nivel actual multiplicado por forma actual. Ejemplo: nivel 80 y forma 92% cuentan como 74 para montar equipos.",
      "El equilibrio también suma goles por partido, victorias, experiencia, posición y bonus de portero/defensa para que el reparto sea más realista.",
      "Al finalizar un partido, el servidor guarda el nivel de cada participante y el equilibrio de esa fecha para que el histórico sea reconstruible.",
    ],
  },
  {
    audience: "Admin",
    title: "Gestión de jugadores",
    intro: "Los admins pueden crear fichas y mantener limpia la plantilla.",
    steps: [
      "Con Crear > Ficha jugador cada usuario puede crear su ficha. Los admins pueden ayudar a corregir datos si hace falta.",
      "Un jugador registrado puede reclamar o crear su propia ficha.",
      "Portero fijo ayuda a que el sistema lo coloque siempre en portería.",
      "Lesionado bloquea el Voy y muestra el icono de hospital en listados.",
      "Borrar jugador lo deja fuera del grupo, pero no elimina su histórico ni su ranking pasado.",
    ],
  },
  {
    audience: "Admin",
    title: "Configuración profunda y copias",
    intro: "Cuando el grupo ya funciona, Configurar reúne permisos, estética, instrucciones y rescates.",
    steps: [
      "En Miembros puedes ver usuarios del grupo y su rol actual.",
      "Solo el owner puede cambiar un jugador a Admin o devolverlo a Jugador desde Configurar.",
      "Solo el owner puede generar una invitación de admin para alguien que todavía no está registrado.",
      "La invitación de admin concede el rol Admin, nunca Owner. El enlace de grupo normal siempre incorpora como Jugador.",
      "Desde Configurar puedes crear una copia manual, ver las últimas copias del servidor y restaurar una copia si algo se ha borrado por error.",
      "La app crea copias automáticas al guardar o finalizar un partido, y también justo antes de borrar un grupo.",
      "El grupo se puede borrar con papelera y doble confirmación para evitar errores.",
    ],
  },
  {
    audience: "Todos",
    title: "Logros y premios postpartido",
    intro: "Los logros reconocen lo ocurrido en partidos confirmados sin cambiar nunca el nivel deportivo ni las facetas de una ficha.",
    steps: [
      "Los logros individuales son reconocimiento personal: quedan en el historial y muestran su contador, pero no entregan cajas, puntos ni cosméticos.",
      "Doblete, hat-trick, póker, repóker y doble hat-trick pueden repetirse. En cada partido solo cuenta el mayor de esos logros que corresponda a los goles asignados al jugador.",
      "En Identidad del equipo puedes separar Logros, Estadísticas y Récords. Allí aparecen partidos, victorias, goles, rivales distintos y mejores rachas calculados por el servidor.",
      "Los hitos personales de partidos, victorias, goles, rachas y rivales se guardan para tu historial, pero siguen sin entregar cajas.",
      "Los goles no asignados sí cuentan para el marcador y los logros colectivos del equipo, pero no inventan un logro individual.",
      "Los logros colectivos se guardan al confirmar el resultado y generan una caja separada para cada participante real del partido.",
      "Un 0-0 cuenta como portería a cero colectiva. En goles del equipo solo se concede el escalón mayor del partido, por ejemplo Manita al marcar cinco.",
      "La caja queda pendiente aunque cierres la app o cambies de dispositivo. Su contenido permanece oculto y solo se concede una vez cuando la abres.",
      "Una caja puede contener puntos de jugador, un cosmético personal o ambos. Los puntos quedan registrados con la caja, el partido y el logro que los originó.",
      "Si recibes un cosmético que ya posees, el servidor lo convierte automáticamente en puntos; nunca acumulas copias idénticas.",
      "Al entrar desde un aviso de premios puedes abrir en orden todas las cajas pendientes y después ver los logros personales de esos partidos.",
      "Si un resultado se corrige, las cajas pendientes dejan de ser válidas. Un premio ya abierto se conserva con una anotación auditable y nunca se descuenta de forma destructiva.",
      "Rating V2 es independiente: ningún logro, caja, punto o cosmético modifica la valoración, las facetas ni el GRL.",
    ],
  },
  {
    audience: "Jugador y admin",
    title: "Asistencia real y conducta",
    intro: "Después de un partido, asistencia y conducta se revisan de forma privada y nunca cambian el nivel deportivo.",
    steps: [
      "Hasta 48 horas después del partido, un owner o admin puede cerrar la asistencia completa de su propia plantilla indicando Jugó, Ausencia justificada, Cancelación tardía o No asistencia sin aviso.",
      "Cambiar Voy a No antes del partido sigue siendo una cancelación normal. No se convierte automáticamente en no-show ni abre una sanción.",
      "Si se registra una cancelación tardía o un no-show, el jugador recibe un aviso obligatorio y dispone de 72 horas para aceptarlo o solicitar una revisión privada.",
      "Una corrección conserva el estado original, quién actuó y cuándo. No se sobrescribe el historial en silencio.",
      "Desde el menú de un jugador en un partido histórico puedes usar Reportar conducta. El reporte exige una relación deportiva real, tiene categorías cerradas y admite un contexto opcional de hasta 500 caracteres.",
      "La persona reportada no conoce la identidad de quien informa. Los admins del grupo tampoco acceden a ella; solo el rol interno de seguridad puede revisar la evidencia completa.",
      "Varios reportes del mismo equipo e incidente se agrupan como una fuente correlacionada. Una fuente aislada nunca impone una sanción automática.",
      "El triage interno separa Solo registro, En observación, Revisión, Prioritario y Urgente. Es una recomendación explicable para ordenar trabajo humano, nunca una declaración de culpabilidad ni una puntuación de conducta.",
      "Las amenazas o violencia pueden llegar a revisión urgente con una sola fuente, pero tampoco generan un bloqueo automático. Un moderador revisa cada decisión negativa de forma individual.",
      "Los avisos formales y las limitaciones sociales requieren una decisión humana y pueden apelarse. Las limitaciones solo afectan mercado, retos o accesos públicos; no afectan grupos privados, Rating V2, GRL, facetas, ranking, logros ni premios.",
      "En Perfil > Avisos y conducta puedes responder cierres de asistencia, consultar avisos, limitaciones y apelaciones, y revisar tus propios reportes enviados.",
    ],
  },
  {
    audience: "Todos",
    title: "Sincronización, caché y uso sin conexión",
    intro: "El teléfono solicita acciones y el servidor confirma el resultado; la copia local solo acelera la lectura.",
    steps: [
      "Asistencia, plazas, reservas, pagos, alineaciones, resultados, valoraciones, invitaciones y retos solo cambian cuando el servidor acepta la operación.",
      "Si otro dispositivo hace un cambio, Realtime avisa y la app actualiza la entidad afectada con su snapshot oficial; no necesita recargar toda la página.",
      "Si dos móviles parten de una versión antigua, el servidor rechaza el cambio obsoleto y la app recupera la revisión más reciente en vez de sobrescribirla en silencio.",
      "La caché local conserva la estructura de la app, catálogos y lecturas recientes para abrir más rápido. Los partidos finalizados pueden reutilizarse durante más tiempo porque casi no cambian.",
      "Sin conexión puedes consultar contenido ya guardado, pero una acción deportiva o social pendiente nunca aparece como confirmada ni se encola para decidirla más tarde.",
      "Al borrar la PWA, el teléfono puede ofrecer eliminar varios megas de caché. Eso no borra tu cuenta, ficha, grupos ni partidos del servidor.",
    ],
  },
];

export function ManualContent() {
  return (
    <div className="manual-flow-list">
      {manualFlows.map((flow) => (
        <article key={flow.title} className="manual-flow-card">
          <header>
            <b>{flow.title}</b>
            <span>{flow.audience}</span>
          </header>
          <p>{flow.intro}</p>
          <ol>
            {flow.steps.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ol>
        </article>
      ))}
    </div>
  );
}
