export function refereeHttpStatus(message: string, code = "") {
  if (/AUTHENTICATION_REQUIRED/i.test(message)) return 401;
  if (/REFEREE_INTEGRATION_NOT_CONFIGURED|REFEREE_ASSIGNMENT_PRIVATE_BETA_DISABLED|REFEREE_ASSIGNMENTS_NOT_AVAILABLE_IN_LEAGUE_BETA|SERVICE_UNAVAILABLE/i.test(message) || code === "PT503") return 503;
  if (/STALE_REVISION|CONFLICT|ALREADY|SCHEDULE_CHANGED|SLOT_TAKEN|TIME_CONFLICT|RECONFIRMATION|TERMINAL|NOT_(?:PROPOSED|CONFIRMABLE|CANCELLABLE|REPLACEABLE|COUNTERABLE|ACCEPTABLE|DECLINABLE)/i.test(message) || code === "PT409") return 409;
  if (/FORBIDDEN|NOT_AUTHORIZED|NOT_ALLOWED|NOT_ASSIGNABLE|NOT_PARTICIPANT|NOT_PUBLISHED|NOT_OPEN|(?:AUTHORITY|OWNER|CAPABILITY|READ|WRITE|MANAGE|ADMIN|PARTICIPANT|ENTITLEMENT)_REQUIRED/i.test(message) || code === "42501") return 403;
  if (/NOT_FOUND/i.test(message) || code === "P0002") return 404;
  if (/RATE_LIMIT/i.test(message) || code === "PT429") return 429;
  return 400;
}
