import Link from "next/link";
import { IncidentControl } from "../_components/incident-control";
import { DataTable, Definition, Identifier, Metric, MetricGrid, PageHeader, Panel, StatusBadge, formatAdminDate } from "../_components/platform-ui";
import { requirePlatformPage } from "../_lib/platform-auth";
import { getPlatformDatabaseHealth, getPlatformSection } from "../_lib/platform-data";
import { getPlatformExternalHealth } from "../_lib/platform-external";
import styles from "../platform-admin.module.css";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function rows(value: unknown) { return Array.isArray(value) ? value.map(record) : []; }
function bytes(value: unknown) { const amount = Number(value); if (!Number.isFinite(amount)) return "No disponible"; return new Intl.NumberFormat("es-ES", { maximumFractionDigits: 1, style: "unit", unit: amount >= 1_073_741_824 ? "gigabyte" : "megabyte" }).format(amount / (amount >= 1_073_741_824 ? 1_073_741_824 : 1_048_576)); }

export default async function PlatformSystemPage({ searchParams }: { searchParams: SearchParams }) {
  const session = await requirePlatformPage("system.read");
  const raw = await searchParams;
  const refresh = first(raw.refresh) === "1";
  const [database, external, errors] = await Promise.all([getPlatformDatabaseHealth(session), getPlatformExternalHealth(refresh), getPlatformSection(session, "errors", 1, 50)]);
  const supabase = record(external.supabase); const vercel = record(external.vercel); const stripe = record(external.stripe); const app = record(external.app);
  const storage = record(database.storage); const deployments = rows(vercel.deployments); const errorItems = rows(errors.items);
  const canManageIncidents = session.access.role === "platform_owner" || session.access.role === "platform_admin" || session.access.role === "ops";
  return <><PageHeader title="Sistema" subtitle="Diagnóstico read-only. El estado UNKNOWN es explícito cuando faltan tokens, permisos o límites verificables." actions={<Link className={styles.secondaryButton} href="/admin/system?refresh=1">Actualizar métricas</Link>} />
    <MetricGrid><Metric label="Supabase" value={<StatusBadge>{String(supabase.state ?? "UNKNOWN")}</StatusBadge>} hint={String(supabase.reason ?? "Management API")} /><Metric label="Vercel" value={<StatusBadge>{String(vercel.state ?? "UNKNOWN")}</StatusBadge>} hint={String(vercel.reason ?? "Deployments REST API")} /><Metric label="Stripe" value={<StatusBadge>{String(stripe.state ?? "UNKNOWN")}</StatusBadge>} hint={String(stripe.reason ?? "API de solo lectura")} /><Metric label="Errores cliente" value={errorItems.length} tone={errorItems.length ? "warning" : "good"} hint="Fingerprints recientes" /><Metric label="Long-running DB" value={Number(database.longRunningQueries) || 0} tone={Number(database.longRunningQueries) ? "warning" : "good"} hint="> 30 segundos" /></MetricGrid>
    <div className={styles.detailGrid}>
      <section><h2>Aplicación / PWA</h2><dl className={styles.definitionList}><Definition label="Client version">{String(app.clientVersion ?? "-")}</Definition><Definition label="Worker">{String(app.serviceWorkerVersion ?? "-")}</Definition><Definition label="Mínimo">{String(app.minimumSupportedClientVersion ?? "-")}</Definition><Definition label="Build SHA"><Identifier value={typeof app.sourceRevision === "string" ? app.sourceRevision : null} /></Definition></dl></section>
      <section><h2>PostgreSQL</h2><dl className={styles.definitionList}><Definition label="DB total">{bytes(database.databaseBytes)}</Definition><Definition label="Conexiones">{String(database.connections ?? 0)}</Definition><Definition label="Activas">{String(database.activeConnections ?? 0)}</Definition><Definition label="Auth users">{String(database.authUsers ?? 0)}</Definition><Definition label="Migraciones">{String(database.migrationCount ?? 0)}</Definition><Definition label="Última"><Identifier value={typeof database.latestMigration === "string" ? database.latestMigration : null} /></Definition></dl></section>
      <section><h2>Storage</h2><dl className={styles.definitionList}><Definition label="Buckets">{String(storage.buckets ?? 0)}</Definition><Definition label="Archivos">{String(storage.files ?? 0)}</Definition><Definition label="Bytes">{bytes(storage.bytes)}</Definition><Definition label="Límite">No disponible</Definition></dl></section>
    </div>
    <Panel title="Top tablas por tamaño"><DataTable label="Tablas por tamaño"><thead><tr><th>Tabla</th><th>Esquema</th><th>Tamaño</th></tr></thead><tbody>{rows(database.topTables).map((item) => <tr key={`${String(item.schema)}.${String(item.table)}`}><td>{String(item.table)}</td><td>{String(item.schema)}</td><td>{bytes(item.bytes)}</td></tr>)}</tbody></DataTable></Panel>
    <Panel title="Supabase Management API"><div className={styles.healthSummary}><StatusBadge>{String(supabase.state ?? "UNKNOWN")}</StatusBadge><span>Proyecto: {String(supabase.projectRef ?? "No configurado")}</span><span>Límites del plan: {supabase.limitsAvailable ? "disponibles" : "no disponibles"}</span><span>Advisors: endpoint experimental/deprecated, solo conteos</span></div></Panel>
    <Panel title="Deployments Vercel"><DataTable label="Deployments Vercel"><thead><tr><th>Deployment</th><th>Entorno</th><th>Estado</th><th>SHA</th><th>Build</th><th>Fecha</th></tr></thead><tbody>{deployments.map((item) => <tr key={String(item.id)}><td>{item.url ? <a href={String(item.url)} target="_blank" rel="noreferrer">{String(item.name ?? item.id)}</a> : String(item.name ?? item.id)}</td><td>{String(item.target ?? "-")}</td><td><StatusBadge>{String(item.state ?? "UNKNOWN")}</StatusBadge></td><td><Identifier value={typeof item.sha === "string" ? item.sha : null} /></td><td>{item.buildDurationMs == null ? "-" : `${Math.round(Number(item.buildDurationMs) / 1000)} s`}</td><td>{formatAdminDate(item.createdAt)}</td></tr>)}</tbody></DataTable></Panel>
    <Panel title="Errores de cliente agregados (retención 30 días)"><DataTable label="Errores cliente"><thead><tr><th>Fingerprint</th><th>Ruta</th><th>Categoría</th><th>Versión</th><th>Entorno</th><th>Ocurrencias</th><th>Incidente</th><th>Último</th><th>Acción</th></tr></thead><tbody>{errorItems.map((item) => <tr key={`${String(item.fingerprint)}:${String(item.route)}`}><td><Identifier value={String(item.fingerprint)} /></td><td>{String(item.route ?? "-")}</td><td>{String(item.category ?? "-")}</td><td>{String(item.appVersion ?? "-")}</td><td>{String(item.browserFamily ?? "-")} · {String(item.platform ?? "-")}</td><td>{String(item.occurrences ?? 0)}</td><td><StatusBadge>{String(item.incidentState ?? "new")}</StatusBadge></td><td>{formatAdminDate(item.lastSeenAt)}</td><td>{canManageIncidents ? <IncidentControl fingerprint={String(item.fingerprint)} revision={Number(item.incidentRevision) || 0} state={String(item.incidentState ?? "new")} /> : null}</td></tr>)}</tbody></DataTable></Panel>
  </>;
}
