export const DEMO_SOCIAL_FIRST_TIME_SESSION_KEY = "pachangas-demo-social-first-time-v3f";

export const DEMO_SOCIAL_FIRST_TIME_STORIES = [
  "Usuario nuevo guarda perfil",
  "El estado cambia de Borrador local a Perfil confirmado simulado",
  "Elige Crear mi equipo",
  "Completa tres pasos",
  "Crea equipo localmente",
  "Queda como owner",
  "Se selecciona el nuevo equipo",
  "Abre la portada",
  "Comparte una invitación sintética",
  "Cambia a perspectiva de otro jugador",
  "Abre el enlace",
  "Confirma",
  "Aparece en plantilla",
  "Repite aceptación",
  "Demuestra cero membresía duplicada",
  "Owner revoca otro enlace",
  "Enlace revocado no permite unirse",
  "Código de equipo identifica pero no concede acceso",
  "Jugador ordinario no puede invitar",
  "Owner crea primer partido",
  "Abre V3B",
  "Cambia entre dos equipos",
  "Verifica Retos V3C",
  "Verifica Mercado V3D",
  "Prueba offline",
  "Reinicia Demo",
] as const;
