export const DEMO_SOCIAL_FIRST_TIME_SESSION_KEY = "pachangas-demo-social-first-time-v3e";

export const DEMO_SOCIAL_FIRST_TIME_STORIES = [
  "Abrir Demo como usuario nuevo",
  "Ver perfil mínimo incompleto",
  "Completar nombre, posición y modalidad",
  "Elegir zona y disponibilidad",
  "Omitir foto",
  "Llegar a Cómo quieres empezar",
  "Elegir Buscar una pachanga",
  "Abrir Mercado V3D",
  "Reiniciar Demo",
  "Elegir Unirme a un equipo",
  "Introducir código sintético",
  "Ver la ficha del equipo",
  "Confirmar unión local",
  "Ver Inicio con equipo activo",
  "Abrir Partidos V3B",
  "Abrir Retos V3C",
  "Reiniciar Demo",
  "Elegir Crear mi equipo",
  "Elegir nombre",
  "Elegir escudo inicial",
  "Elegir modalidad y zona",
  "Crear localmente",
  "Ver código de equipo",
  "Crear primer partido",
  "Abrir Mi perfil",
  "Ver carta inexistente",
  "Crear una vista previa de carta",
  "Activar perfil de Mercado",
  "Verlo desde la perspectiva de otro equipo",
  "Pausar visibilidad",
  "Probar usuario con varios equipos",
  "Cambiar equipo",
  "Probar offline",
  "Reiniciar Demo",
] as const;
