import Link from "next/link";
import { notFound } from "next/navigation";
import { DataTable, Definition, EmptyState, Identifier, PageHeader, Panel, StatusBadge, formatAdminDate } from "../../../_components/platform-ui";
import { requirePlatformPage } from "../../../_lib/platform-auth";
import { getPlatformMatchDetail } from "../../../_lib/platform-data";
import styles from "../../../platform-admin.module.css";

type Params = Promise<{ groupId: string; matchId: string }>;
function record(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }

export default async function PlatformMatchDetailPage({ params }: { params: Params }) {
  const session = await requirePlatformPage("matches.read");
  const { groupId, matchId } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(groupId) || !matchId || matchId.length > 160) notFound();
  const detail = await getPlatformMatchDetail(session, groupId, decodeURIComponent(matchId));
  const match = record(detail.match); const group = record(detail.group); const rating = record(detail.ratingSnapshot); const fact = record(detail.progressionFact);
  const cards = new Map(detail.ratingParticipants.map((item) => { const row = record(item); return [String(row.local_player_id), row]; }));
  return <>
    <PageHeader title={String(match.title ?? `Partido ${match.match_id}`)} subtitle="Estado canónico del partido y trazabilidad de alineación, resultado, progresión, rewards y avisos." actions={<><Link className={styles.secondaryButton} href="/admin/matches">Volver</Link><Link className={styles.secondaryButton} href={`/admin/teams/${groupId}`}>Ver equipo</Link></>} />
    <div className={styles.detailGrid}>
      <section><h2>Partido</h2><dl className={styles.definitionList}><Definition label="Match ID"><Identifier value={String(match.match_id)} /></Definition><Definition label="Equipo">{String(group.name ?? "Equipo")} · {String(group.team_code ?? "-")}</Definition><Definition label="Fecha">{formatAdminDate(match.date)}</Definition><Definition label="Campo">{String(match.place ?? "No normalizado")}</Definition><Definition label="Modalidad">{String(match.kind ?? "No normalizada")}</Definition></dl></section>
      <section><h2>Autoridad central</h2><dl className={styles.definitionList}><Definition label="Estado"><StatusBadge>{String(match.match_state)}</StatusBadge></Definition><Definition label="Revisión">{String(match.match_version)}</Definition><Definition label="Payload origen">{String(match.source_payload_revision)}</Definition><Definition label="Alineación"><StatusBadge>{match.lineup_closed ? "cerrada" : "abierta"}</StatusBadge></Definition><Definition label="Actualizado">{formatAdminDate(match.updated_at)}</Definition></dl></section>
      <section><h2>Resultado</h2><dl className={styles.definitionList}><Definition label="Marcador">{match.score_a == null ? "Pendiente" : `${String(match.score_a)} - ${String(match.score_b)}`}</Definition><Definition label="Finalizado"><StatusBadge>{match.finalized ? "sí" : "no"}</StatusBadge></Definition><Definition label="Pagador"><Identifier value={typeof match.payer_player_id === "string" ? match.payer_player_id : null} /></Definition><Definition label="Cupo">{String(match.target_players)} + {String(match.reserve_limit)} reservas</Definition></dl></section>
    </div>
    <Panel title={`Alineación y asistencia (${detail.participants.length})`}>{detail.participants.length ? <DataTable label="Participantes del partido"><thead><tr><th>Jugador</th><th>Equipo</th><th>Estado</th><th>Plaza</th><th>Pago</th><th>Snapshot</th></tr></thead><tbody>{detail.participants.map((item) => { const row = record(item); const card = cards.get(String(row.player_id)) ?? {}; const snapshot = record(card.card_snapshot); return <tr key={String(row.player_id)}><td>{String(snapshot.displayName ?? snapshot.name ?? row.player_id)}</td><td>{String(card.team_side ?? "-")}</td><td><StatusBadge>{String(row.status)}</StatusBadge></td><td>{String(row.seat_kind)}</td><td><StatusBadge>{row.paid ? "pagado" : "pendiente"}</StatusBadge></td><td>{card.attendance_confirmed ? `Confirmada · GRL ${String(snapshot.overall ?? snapshot.currentOverall ?? "-")}` : "Sin snapshot confirmado"}</td></tr>; })}</tbody></DataTable> : <EmptyState>El snapshot canónico no contiene participantes.</EmptyState>}</Panel>
    <div className={styles.overviewColumns}>
      <Panel title="Goleadores"><DataTable label="Goleadores"><thead><tr><th>Jugador</th><th>Goles</th><th>Actualizado</th></tr></thead><tbody>{detail.scorers.map((item) => { const row = record(item); return <tr key={String(row.player_id)}><td>{String(row.player_id)}</td><td>{String(row.goals)}</td><td>{formatAdminDate(row.updated_at)}</td></tr>; })}</tbody></DataTable></Panel>
      <Panel title="Snapshot Rating V2"><dl className={`${styles.definitionList} ${styles.panelDefinitions}`}><Definition label="Estado"><StatusBadge>{String(rating.state ?? "ausente")}</StatusBadge></Definition><Definition label="Nivel grupo">{rating.group_level == null ? "-" : Number(rating.group_level).toFixed(2)}</Definition><Definition label="Equipo A">{rating.lineup_a_level == null ? "-" : Number(rating.lineup_a_level).toFixed(2)}</Definition><Definition label="Equipo B">{rating.lineup_b_level == null ? "-" : Number(rating.lineup_b_level).toFixed(2)}</Definition><Definition label="Motor">{String(rating.engine_version ?? "-")}</Definition><Definition label="Finalizado">{formatAdminDate(rating.finalized_at)}</Definition></dl></Panel>
    </div>
    <Panel title="Hecho de progresión"><dl className={`${styles.definitionList} ${styles.panelDefinitions}`}><Definition label="Estado"><StatusBadge>{String(fact.state ?? "ausente")}</StatusBadge></Definition><Definition label="Origen">{String(fact.source_kind ?? "-")}</Definition><Definition label="Secuencia">{String(fact.server_sequence ?? "-")}</Definition><Definition label="Resultado">{String(fact.outcome ?? "-")} · {String(fact.goals_for ?? "-")}:{String(fact.goals_against ?? "-")}</Definition><Definition label="Aplicado">{formatAdminDate(fact.applied_at)}</Definition></dl></Panel>
    <div className={styles.overviewColumns}>
      <Panel title={`Achievements (${detail.achievements.length})`}><DataTable label="Achievements del partido"><thead><tr><th>Grant</th><th>Sujeto</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{detail.achievements.map((item) => { const row = record(item); return <tr key={String(row.id)}><td><Identifier value={String(row.id)} /></td><td>{String(row.subject_type)} · <Identifier value={String(row.subject_id)} /></td><td><StatusBadge>{String(row.state)}</StatusBadge></td><td>{formatAdminDate(row.awarded_at)}</td></tr>; })}</tbody></DataTable></Panel>
      <Panel title={`Rewards (${detail.rewards.length})`}><DataTable label="Rewards del partido"><thead><tr><th>Reward</th><th>Tipo</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{detail.rewards.map((item) => { const row = record(item); return <tr key={String(row.id)}><td>{String(row.reward_key)}</td><td>{String(row.reward_kind)}</td><td><StatusBadge>{String(row.state)}</StatusBadge></td><td>{formatAdminDate(row.granted_at)}</td></tr>; })}</tbody></DataTable></Panel>
    </div>
    <Panel title={`Notificaciones relacionadas (${detail.notifications.length})`}><DataTable label="Notificaciones relacionadas"><thead><tr><th>Notificación</th><th>Categoría</th><th>Prioridad</th><th>Secuencia</th><th>Fecha</th></tr></thead><tbody>{detail.notifications.map((item) => { const row = record(item); return <tr key={String(row.id)}><td>{String(row.title)}</td><td>{String(row.category)}</td><td><StatusBadge>{String(row.priority)}</StatusBadge></td><td>{String(row.server_sequence)}</td><td>{formatAdminDate(row.created_at)}</td></tr>; })}</tbody></DataTable></Panel>
  </>;
}
