-- Pachangas IQ rating system V2: shared authority and operation metadata.

alter table public.pachanga_individual_rating_evidence
  add column if not exists moderation_id uuid not null default gen_random_uuid();

create unique index if not exists pachanga_individual_rating_moderation_idx
  on public.pachanga_individual_rating_evidence(moderation_id);

alter table public.pachanga_operation_receipts
  add column if not exists expected_revision bigint,
  add column if not exists result_revision bigint,
  add column if not exists client_metadata jsonb not null default '{}'::jsonb,
  add column if not exists server_sequence bigint;

alter table public.pachanga_group_events
  add column if not exists server_sequence bigint generated by default as identity;

create unique index if not exists pachanga_group_events_server_sequence_idx
  on public.pachanga_group_events(server_sequence);

create or replace function public.pachanga_operation_replay_v2(
  target_group_id uuid,
  target_operation_id uuid,
  target_actor_id uuid
)
returns jsonb
language plpgsql
security definer
stable
set search_path = pg_catalog
as $$
declare
  stored_response jsonb;
  stored_actor uuid;
begin
  select receipts.response, receipts.user_id
  into stored_response, stored_actor
  from public.pachanga_operation_receipts receipts
  where receipts.group_id = target_group_id
    and receipts.operation_id = target_operation_id;
  if stored_response is not null and stored_actor is distinct from target_actor_id then
    raise exception 'Operation belongs to another actor';
  end if;
  return stored_response;
end;
$$;

create or replace function public.pachanga_group_snapshot_v2(target_group_id uuid)
returns jsonb
language sql
security definer
stable
set search_path = pg_catalog
as $$
  select jsonb_build_object(
    'groupId', groups.id,
    'payload', groups.payload,
    'payload_revision', groups.payload_revision,
    'confirmedRevision', groups.payload_revision,
    'updated_at', groups.updated_at,
    'ratingsEnabled', groups.ratings_enabled,
    'externallyCalibratedLevel', groups.externally_calibrated_level,
    'externalCalibrationSnapshot', groups.external_calibration_snapshot
  )
  from public.pachanga_groups groups
  where groups.id = target_group_id;
$$;

create or replace function public.pachanga_authoritative_response_v2(
  target_group_id uuid,
  target_operation_id uuid,
  target_operation_type text,
  target_expected_revision bigint,
  operation_result jsonb default '{}'::jsonb,
  target_client_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_user_id uuid := auth.uid();
  canonical jsonb;
  confirmed_revision bigint;
  confirmed_at timestamptz := clock_timestamp();
  event_sequence bigint;
  final_response jsonb;
  stored_response jsonb;
  stored_actor uuid;
begin
  if target_operation_id is null then
    raise exception 'Operation id required';
  end if;

  canonical := public.pachanga_group_snapshot_v2(target_group_id);
  if canonical is null then
    raise exception 'Group not found';
  end if;
  confirmed_revision := (canonical ->> 'confirmedRevision')::bigint;

  select receipts.user_id into stored_actor
  from public.pachanga_operation_receipts receipts
  where receipts.group_id = target_group_id
    and receipts.operation_id = target_operation_id;
  if found and stored_actor is distinct from current_user_id then
    raise exception 'Operation belongs to another actor';
  end if;

  select events.server_sequence
  into event_sequence
  from public.pachanga_group_events events
  where events.group_id = target_group_id
    and events.operation_id = target_operation_id
  order by events.server_sequence desc
  limit 1;

  final_response := canonical || coalesce(operation_result, '{}'::jsonb) || jsonb_build_object(
    'operationId', target_operation_id,
    'expectedRevision', target_expected_revision,
    'confirmedRevision', confirmed_revision,
    'confirmedAt', confirmed_at,
    'serverSequence', event_sequence
  );

  insert into public.pachanga_operation_receipts(
    group_id,
    operation_id,
    operation_type,
    user_id,
    response,
    expected_revision,
    result_revision,
    client_metadata,
    server_sequence
  ) values (
    target_group_id,
    target_operation_id,
    left(coalesce(nullif(trim(target_operation_type), ''), 'unknown'), 120),
    current_user_id,
    final_response,
    target_expected_revision,
    confirmed_revision,
    case when jsonb_typeof(target_client_metadata) = 'object' then target_client_metadata else '{}'::jsonb end,
    event_sequence
  )
  on conflict (group_id, operation_id) do update set
    expected_revision = coalesce(public.pachanga_operation_receipts.expected_revision, excluded.expected_revision),
    result_revision = coalesce(public.pachanga_operation_receipts.result_revision, excluded.result_revision),
    client_metadata = case
      when public.pachanga_operation_receipts.client_metadata = '{}'::jsonb then excluded.client_metadata
      else public.pachanga_operation_receipts.client_metadata
    end,
    server_sequence = coalesce(public.pachanga_operation_receipts.server_sequence, excluded.server_sequence),
    response = case
      when public.pachanga_operation_receipts.response ? 'confirmedRevision' then public.pachanga_operation_receipts.response
      else excluded.response
    end;

  select receipts.response
  into stored_response
  from public.pachanga_operation_receipts receipts
  where receipts.group_id = target_group_id
    and receipts.operation_id = target_operation_id;

  return stored_response;
end;
$$;

revoke all on function public.pachanga_group_snapshot_v2(uuid) from public, anon, authenticated;
revoke all on function public.pachanga_operation_replay_v2(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public.pachanga_authoritative_response_v2(uuid, uuid, text, bigint, jsonb, jsonb)
  from public, anon, authenticated;
