revoke all on function public.pachanga_assessment_clamp(numeric, numeric, numeric) from public;
revoke execute on function public.pachanga_assessment_clamp(numeric, numeric, numeric) from anon;
revoke execute on function public.pachanga_assessment_clamp(numeric, numeric, numeric) from authenticated;
revoke all on function public.pachanga_assessment_response_score(jsonb, text, numeric, boolean) from public;
revoke execute on function public.pachanga_assessment_response_score(jsonb, text, numeric, boolean) from anon;
revoke execute on function public.pachanga_assessment_response_score(jsonb, text, numeric, boolean) from authenticated;
revoke all on function public.pachanga_assessment_overall_weight(text, text) from public;
revoke execute on function public.pachanga_assessment_overall_weight(text, text) from anon;
revoke execute on function public.pachanga_assessment_overall_weight(text, text) from authenticated;
revoke all on function public.pachanga_assessment_mode_confidence(jsonb, text) from public;
revoke execute on function public.pachanga_assessment_mode_confidence(jsonb, text) from anon;
revoke execute on function public.pachanga_assessment_mode_confidence(jsonb, text) from authenticated;
revoke all on function public.pachanga_assessment_app_position(text) from public;
revoke execute on function public.pachanga_assessment_app_position(text) from anon;
revoke execute on function public.pachanga_assessment_app_position(text) from authenticated;
revoke all on function public.pachanga_assessment_facets_from_attributes(jsonb) from public;
revoke execute on function public.pachanga_assessment_facets_from_attributes(jsonb) from anon;
revoke execute on function public.pachanga_assessment_facets_from_attributes(jsonb) from authenticated;
revoke all on function public.calculate_pachanga_initial_assessment(jsonb) from public;
revoke execute on function public.calculate_pachanga_initial_assessment(jsonb) from anon;
revoke execute on function public.calculate_pachanga_initial_assessment(jsonb) from authenticated;
revoke all on function public.calculate_pachanga_advanced_assessment(jsonb, jsonb) from public;
revoke execute on function public.calculate_pachanga_advanced_assessment(jsonb, jsonb) from anon;
revoke execute on function public.calculate_pachanga_advanced_assessment(jsonb, jsonb) from authenticated;
revoke all on function public.pachanga_assessment_without_self_votes(jsonb, uuid) from public;
revoke execute on function public.pachanga_assessment_without_self_votes(jsonb, uuid) from anon;
revoke execute on function public.pachanga_assessment_without_self_votes(jsonb, uuid) from authenticated;
revoke all on function public.pachanga_assessment_summary_item(jsonb, timestamptz) from public;
revoke execute on function public.pachanga_assessment_summary_item(jsonb, timestamptz) from anon;
revoke execute on function public.pachanga_assessment_summary_item(jsonb, timestamptz) from authenticated;
revoke all on function public.complete_pachanga_player_initial_assessment(uuid, text, jsonb, jsonb, uuid) from public;
revoke execute on function public.complete_pachanga_player_initial_assessment(uuid, text, jsonb, jsonb, uuid) from anon;
grant execute on function public.complete_pachanga_player_initial_assessment(uuid, text, jsonb, jsonb, uuid) to authenticated;
revoke all on function public.complete_pachanga_player_advanced_assessment(uuid, text, jsonb, jsonb, uuid) from public;
revoke execute on function public.complete_pachanga_player_advanced_assessment(uuid, text, jsonb, jsonb, uuid) from anon;
grant execute on function public.complete_pachanga_player_advanced_assessment(uuid, text, jsonb, jsonb, uuid) to authenticated;
